method=repeat
width=6
height=6
tiles=textures/optifine/ctm/kelastrion_hewn/0 textures/optifine/ctm/kelastrion_hewn/1 textures/optifine/ctm/kelastrion_hewn/2 textures/optifine/ctm/kelastrion_hewn/3 textures/optifine/ctm/kelastrion_hewn/4 textures/optifine/ctm/kelastrion_hewn/5 textures/optifine/ctm/kelastrion_hewn/6 textures/optifine/ctm/kelastrion_hewn/7 textures/optifine/ctm/kelastrion_hewn/8 textures/optifine/ctm/kelastrion_hewn/9 textures/optifine/ctm/kelastrion_hewn/10 textures/optifine/ctm/kelastrion_hewn/11 textures/optifine/ctm/kelastrion_hewn/12 textures/optifine/ctm/kelastrion_hewn/13 textures/optifine/ctm/kelastrion_hewn/14 textures/optifine/ctm/kelastrion_hewn/15 textures/optifine/ctm/kelastrion_hewn/16 textures/optifine/ctm/kelastrion_hewn/17 textures/optifine/ctm/kelastrion_hewn/18 textures/optifine/ctm/kelastrion_hewn/19 textures/optifine/ctm/kelastrion_hewn/20 textures/optifine/ctm/kelastrion_hewn/21 textures/optifine/ctm/kelastrion_hewn/22 textures/optifine/ctm/kelastrion_hewn/23 textures/optifine/ctm/kelastrion_hewn/24 textures/optifine/ctm/kelastrion_hewn/25 textures/optifine/ctm/kelastrion_hewn/26 textures/optifine/ctm/kelastrion_hewn/27 textures/optifine/ctm/kelastrion_hewn/28 textures/optifine/ctm/kelastrion_hewn/29 textures/optifine/ctm/kelastrion_hewn/30 textures/optifine/ctm/kelastrion_hewn/31 textures/optifine/ctm/kelastrion_hewn/32 textures/optifine/ctm/kelastrion_hewn/33 textures/optifine/ctm/kelastrion_hewn/34 textures/optifine/ctm/kelastrion_hewn/35
matchBlocks=erydon:kelastrion_hewn_block \
  erydon:kelastrion_hewn_slab \
  erydon:kelastrion_hewn_layer \
  erydon:kelastrion_hewn_layer_vertical \
  erydon:kelastrion_hewn_slope \
  erydon:kelastrion_hewn_slope_shallow_lower \
  erydon:kelastrion_hewn_slope_shallow_upper \
  erydon:kelastrion_hewn_slope_steep_lower \
  erydon:kelastrion_hewn_slope_steep_upper \
  erydon:kelastrion_hewn_slope_vertical \
  erydon:kelastrion_hewn_slope_vertical_shallow_narrow \
  erydon:kelastrion_hewn_slope_vertical_shallow_broad \
  erydon:kelastrion_hewn_arch_romanesque \
  erydon:kelastrion_hewn_vertical_slice \
  erydon:kelastrion_hewn_horizontal_slice \
  erydon:kelastrion_hewn_post \
  erydon:kelastrion_hewn_stairs \
  erydon:kelastrion_hewn_wall \
  erydon:kelastrion_hewn_alcove_georgian \
  erydon:kelastrion_hewn_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
