method=repeat
width=6
height=6
tiles=textures/optifine/ctm/solistra/0 textures/optifine/ctm/solistra/1 textures/optifine/ctm/solistra/2 textures/optifine/ctm/solistra/3 textures/optifine/ctm/solistra/4 textures/optifine/ctm/solistra/5 textures/optifine/ctm/solistra/6 textures/optifine/ctm/solistra/7 textures/optifine/ctm/solistra/8 textures/optifine/ctm/solistra/9 textures/optifine/ctm/solistra/10 textures/optifine/ctm/solistra/11 textures/optifine/ctm/solistra/12 textures/optifine/ctm/solistra/13 textures/optifine/ctm/solistra/14 textures/optifine/ctm/solistra/15 textures/optifine/ctm/solistra/16 textures/optifine/ctm/solistra/17 textures/optifine/ctm/solistra/18 textures/optifine/ctm/solistra/19 textures/optifine/ctm/solistra/20 textures/optifine/ctm/solistra/21 textures/optifine/ctm/solistra/22 textures/optifine/ctm/solistra/23 textures/optifine/ctm/solistra/24 textures/optifine/ctm/solistra/25 textures/optifine/ctm/solistra/26 textures/optifine/ctm/solistra/27 textures/optifine/ctm/solistra/28 textures/optifine/ctm/solistra/29 textures/optifine/ctm/solistra/30 textures/optifine/ctm/solistra/31 textures/optifine/ctm/solistra/32 textures/optifine/ctm/solistra/33 textures/optifine/ctm/solistra/34 textures/optifine/ctm/solistra/35

matchBlocks=erydon:solistra_ceiling_coffered_guilloche_white_small
matchTiles=erydon:block/solistra_block

faces=all
connect=block
innerSeams=true
priority=10
