method=repeat

width=6

height=6

tiles=textures/optifine/ctm/solistra/0 textures/optifine/ctm/solistra/1 textures/optifine/ctm/solistra/2 textures/optifine/ctm/solistra/3 textures/optifine/ctm/solistra/4 textures/optifine/ctm/solistra/5 textures/optifine/ctm/solistra/6 textures/optifine/ctm/solistra/7 textures/optifine/ctm/solistra/8 textures/optifine/ctm/solistra/9 textures/optifine/ctm/solistra/10 textures/optifine/ctm/solistra/11 textures/optifine/ctm/solistra/12 textures/optifine/ctm/solistra/13 textures/optifine/ctm/solistra/14 textures/optifine/ctm/solistra/15 textures/optifine/ctm/solistra/16 textures/optifine/ctm/solistra/17 textures/optifine/ctm/solistra/18 textures/optifine/ctm/solistra/19 textures/optifine/ctm/solistra/20 textures/optifine/ctm/solistra/21 textures/optifine/ctm/solistra/22 textures/optifine/ctm/solistra/23 textures/optifine/ctm/solistra/24 textures/optifine/ctm/solistra/25 textures/optifine/ctm/solistra/26 textures/optifine/ctm/solistra/27 textures/optifine/ctm/solistra/28 textures/optifine/ctm/solistra/29 textures/optifine/ctm/solistra/30 textures/optifine/ctm/solistra/31 textures/optifine/ctm/solistra/32 textures/optifine/ctm/solistra/33 textures/optifine/ctm/solistra/34 textures/optifine/ctm/solistra/35

matchBlocks=erydon:solistra_block \
  erydon:solistra_stairs \
  erydon:solistra_stairs_shallow_bottom \
  erydon:solistra_stairs_shallow_top \
  erydon:solistra_slab \
  erydon:solistra_wall \
  erydon:solistra_layer \
  erydon:solistra_layer_multiface \
  erydon:solistra_layer_vertical \
  erydon:solistra_slope \
  erydon:solistra_slope_shallow_upper \
  erydon:solistra_slope_steep_lower \
  erydon:solistra_slope_steep_upper \
  erydon:solistra_slope_shallow_lower \
  erydon:solistra_slope_vertical \
  erydon:solistra_slope_vertical_shallow_narrow \
  erydon:solistra_arch_romanesque \
  erydon:solistra_slope_vertical_shallow_broad \
  erydon:solistra_column_circular \
  erydon:solistra_column_gothic \
  erydon:solistra_column_square \
  erydon:solistra_cornice_modern \
  erydon:solistra_cornice_georgian \
  erydon:solistra_cornice_guilloche \
  erydon:solistra_cornice_gothic \
  erydon:solistra_surround_georgian \
  erydon:solistra_surround_guilloche \
  erydon:solistra_surround_gothic_ornate \
  erydon:solistra_surround_modern \
  erydon:solistra_stairs_spiral_large \
  erydon:solistra_light_modern \
  erydon:solistra_chimney_circular \
  erydon:solistra_vertical_slice \
  erydon:solistra_horizontal_slice \
  erydon:solistra_post \
  erydon:solistra_wall_georgian \
  erydon:solistra_alcove_georgian \
  erydon:solistra_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
