method=repeat
width=6
height=6
tiles=textures/optifine/ctm/solistra/0 textures/optifine/ctm/solistra/1 textures/optifine/ctm/solistra/2 textures/optifine/ctm/solistra/3 textures/optifine/ctm/solistra/4 textures/optifine/ctm/solistra/5 textures/optifine/ctm/solistra/6 textures/optifine/ctm/solistra/7 textures/optifine/ctm/solistra/8 textures/optifine/ctm/solistra/9 textures/optifine/ctm/solistra/10 textures/optifine/ctm/solistra/11 textures/optifine/ctm/solistra/12 textures/optifine/ctm/solistra/13 textures/optifine/ctm/solistra/14 textures/optifine/ctm/solistra/15 textures/optifine/ctm/solistra/16 textures/optifine/ctm/solistra/17 textures/optifine/ctm/solistra/18 textures/optifine/ctm/solistra/19 textures/optifine/ctm/solistra/20 textures/optifine/ctm/solistra/21 textures/optifine/ctm/solistra/22 textures/optifine/ctm/solistra/23 textures/optifine/ctm/solistra/24 textures/optifine/ctm/solistra/25 textures/optifine/ctm/solistra/26 textures/optifine/ctm/solistra/27 textures/optifine/ctm/solistra/28 textures/optifine/ctm/solistra/29 textures/optifine/ctm/solistra/30 textures/optifine/ctm/solistra/31 textures/optifine/ctm/solistra/32 textures/optifine/ctm/solistra/33 textures/optifine/ctm/solistra/34 textures/optifine/ctm/solistra/35
matchBlocks=erydon:solistra_block_silvertrim \
  erydon:solistra_trim_silver_stairs \
  erydon:solistra_trim_silver_stairs_shallow_bottom \
  erydon:solistra_trim_silver_stairs_shallow_top \
  erydon:solistra_trim_silver_layer_multiface \
  erydon:solistra_trim_silver_slope \
  erydon:solistra_trim_silver_slope_shallow_lower \
  erydon:solistra_trim_silver_slope_shallow_upper \
  erydon:solistra_trim_silver_slope_steep_lower \
  erydon:solistra_trim_silver_slope_steep_upper \
  erydon:solistra_trim_silver_slope_vertical \
  erydon:solistra_trim_silver_slope_vertical_shallow_broad \
  erydon:solistra_trim_silver_slope_vertical_shallow_narrow \
  erydon:solistra_block_bronzetrim \
  erydon:solistra_trim_bronze_stairs \
  erydon:solistra_trim_bronze_stairs_shallow_bottom \
  erydon:solistra_trim_bronze_stairs_shallow_top \
  erydon:solistra_trim_bronze_layer_multiface \
  erydon:solistra_trim_bronze_slope \
  erydon:solistra_trim_bronze_slope_shallow_lower \
  erydon:solistra_trim_bronze_slope_shallow_upper \
  erydon:solistra_trim_bronze_slope_steep_lower \
  erydon:solistra_trim_bronze_slope_steep_upper \
  erydon:solistra_trim_bronze_slope_vertical \
  erydon:solistra_trim_bronze_slope_vertical_shallow_broad \
  erydon:solistra_trim_bronze_slope_vertical_shallow_narrow \
  erydon:solistra_block_bronzequatrefoil \
  erydon:solistra_quatrefoil_bronze_stairs \
  erydon:solistra_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:solistra_quatrefoil_bronze_stairs_shallow_top \
  erydon:solistra_quatrefoil_bronze_layer_multiface \
  erydon:solistra_quatrefoil_bronze_slope \
  erydon:solistra_quatrefoil_bronze_slope_shallow_lower \
  erydon:solistra_quatrefoil_bronze_slope_shallow_upper \
  erydon:solistra_quatrefoil_bronze_slope_steep_lower \
  erydon:solistra_quatrefoil_bronze_slope_steep_upper \
  erydon:solistra_quatrefoil_bronze_slope_vertical \
  erydon:solistra_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:solistra_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:solistra_block_silverquatrefoil \
  erydon:solistra_quatrefoil_silver_stairs \
  erydon:solistra_quatrefoil_silver_stairs_shallow_bottom \
  erydon:solistra_quatrefoil_silver_stairs_shallow_top \
  erydon:solistra_quatrefoil_silver_layer_multiface \
  erydon:solistra_quatrefoil_silver_slope \
  erydon:solistra_quatrefoil_silver_slope_shallow_lower \
  erydon:solistra_quatrefoil_silver_slope_shallow_upper \
  erydon:solistra_quatrefoil_silver_slope_steep_lower \
  erydon:solistra_quatrefoil_silver_slope_steep_upper \
  erydon:solistra_quatrefoil_silver_slope_vertical \
  erydon:solistra_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:solistra_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:solistra_block_silverrose \
  erydon:solistra_rosette_silver_stairs \
  erydon:solistra_rosette_silver_stairs_shallow_bottom \
  erydon:solistra_rosette_silver_stairs_shallow_top \
  erydon:solistra_rosette_silver_layer_multiface \
  erydon:solistra_rosette_silver_slope \
  erydon:solistra_rosette_silver_slope_shallow_lower \
  erydon:solistra_rosette_silver_slope_shallow_upper \
  erydon:solistra_rosette_silver_slope_steep_lower \
  erydon:solistra_rosette_silver_slope_steep_upper \
  erydon:solistra_rosette_silver_slope_vertical \
  erydon:solistra_rosette_silver_slope_vertical_shallow_broad \
  erydon:solistra_rosette_silver_slope_vertical_shallow_narrow \
  erydon:solistra_block_bronzerose \
  erydon:solistra_rosette_bronze_stairs \
  erydon:solistra_rosette_bronze_stairs_shallow_bottom \
  erydon:solistra_rosette_bronze_stairs_shallow_top \
  erydon:solistra_rosette_bronze_layer_multiface \
  erydon:solistra_rosette_bronze_slope \
  erydon:solistra_rosette_bronze_slope_shallow_lower \
  erydon:solistra_rosette_bronze_slope_shallow_upper \
  erydon:solistra_rosette_bronze_slope_steep_lower \
  erydon:solistra_rosette_bronze_slope_steep_upper \
  erydon:solistra_rosette_bronze_slope_vertical \
  erydon:solistra_rosette_bronze_slope_vertical_shallow_broad \
  erydon:solistra_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:solistra_block_silverguilloche \
  erydon:solistra_guilloche_silver_stairs \
  erydon:solistra_guilloche_silver_stairs_shallow_bottom \
  erydon:solistra_guilloche_silver_stairs_shallow_top \
  erydon:solistra_guilloche_silver_layer_multiface \
  erydon:solistra_guilloche_silver_slope \
  erydon:solistra_guilloche_silver_slope_shallow_lower \
  erydon:solistra_guilloche_silver_slope_shallow_upper \
  erydon:solistra_guilloche_silver_slope_steep_lower \
  erydon:solistra_guilloche_silver_slope_steep_upper \
  erydon:solistra_guilloche_silver_slope_vertical \
  erydon:solistra_guilloche_silver_slope_vertical_shallow_broad \
  erydon:solistra_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:solistra_block_bronzeguilloche \
  erydon:solistra_guilloche_bronze_stairs \
  erydon:solistra_guilloche_bronze_stairs_shallow_bottom \
  erydon:solistra_guilloche_bronze_stairs_shallow_top \
  erydon:solistra_guilloche_bronze_layer_multiface \
  erydon:solistra_guilloche_bronze_slope \
  erydon:solistra_guilloche_bronze_slope_shallow_lower \
  erydon:solistra_guilloche_bronze_slope_shallow_upper \
  erydon:solistra_guilloche_bronze_slope_steep_lower \
  erydon:solistra_guilloche_bronze_slope_steep_upper \
  erydon:solistra_guilloche_bronze_slope_vertical \
  erydon:solistra_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:solistra_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
