method=repeat
width=6
height=6
tiles=textures/optifine/ctm/brectite_aged/0 textures/optifine/ctm/brectite_aged/1 textures/optifine/ctm/brectite_aged/2 textures/optifine/ctm/brectite_aged/3 textures/optifine/ctm/brectite_aged/4 textures/optifine/ctm/brectite_aged/5 textures/optifine/ctm/brectite_aged/6 textures/optifine/ctm/brectite_aged/7 textures/optifine/ctm/brectite_aged/8 textures/optifine/ctm/brectite_aged/9 textures/optifine/ctm/brectite_aged/10 textures/optifine/ctm/brectite_aged/11 textures/optifine/ctm/brectite_aged/12 textures/optifine/ctm/brectite_aged/13 textures/optifine/ctm/brectite_aged/14 textures/optifine/ctm/brectite_aged/15 textures/optifine/ctm/brectite_aged/16 textures/optifine/ctm/brectite_aged/17 textures/optifine/ctm/brectite_aged/18 textures/optifine/ctm/brectite_aged/19 textures/optifine/ctm/brectite_aged/20 textures/optifine/ctm/brectite_aged/21 textures/optifine/ctm/brectite_aged/22 textures/optifine/ctm/brectite_aged/23 textures/optifine/ctm/brectite_aged/24 textures/optifine/ctm/brectite_aged/25 textures/optifine/ctm/brectite_aged/26 textures/optifine/ctm/brectite_aged/27 textures/optifine/ctm/brectite_aged/28 textures/optifine/ctm/brectite_aged/29 textures/optifine/ctm/brectite_aged/30 textures/optifine/ctm/brectite_aged/31 textures/optifine/ctm/brectite_aged/32 textures/optifine/ctm/brectite_aged/33 textures/optifine/ctm/brectite_aged/34 textures/optifine/ctm/brectite_aged/35
matchBlocks=erydon:brectite_block_aged \
  erydon:brectite_stairs_aged \
  erydon:brectite_stairs_shallow_bottom_aged \
  erydon:brectite_stairs_shallow_top_aged \
  erydon:brectite_slab_aged \
  erydon:brectite_wall_aged \
  erydon:brectite_layer_aged \
  erydon:brectite_layer_multiface_aged \
  erydon:brectite_layer_vertical_aged \
  erydon:brectite_slope_aged \
  erydon:brectite_slope_shallow_upper_aged \
  erydon:brectite_slope_steep_lower_aged \
  erydon:brectite_slope_steep_upper_aged \
  erydon:brectite_slope_shallow_lower_aged \
  erydon:brectite_slope_vertical_aged \
  erydon:brectite_slope_vertical_shallow_narrow_aged \
  erydon:brectite_arch_romanesque_aged \
  erydon:brectite_slope_vertical_shallow_broad_aged \
  erydon:brectite_column_circular_aged \
  erydon:brectite_aged_column_gothic \
  erydon:brectite_column_square_aged \
  erydon:brectite_cornice_modern_aged \
  erydon:brectite_cornice_georgian_aged \
  erydon:brectite_cornice_guilloche_aged \
  erydon:brectite_aged_cornice_gothic \
  erydon:brectite_surround_georgian_aged \
  erydon:brectite_surround_guilloche_aged \
  erydon:brectite_aged_surround_gothic_ornate \
  erydon:brectite_surround_modern_aged \
  erydon:brectite_stairs_spiral_large_aged \
  erydon:brectite_chimney_circular_aged \
  erydon:brectite_vertical_slice_aged \
  erydon:brectite_horizontal_slice_aged \
  erydon:brectite_post_aged \
  erydon:brectite_wall_georgian_aged \
  erydon:brectite_aged_alcove_georgian \
  erydon:brectite_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
