method=repeat

width=6

height=6

tiles=textures/optifine/ctm/porphyros/0 textures/optifine/ctm/porphyros/1 textures/optifine/ctm/porphyros/2 textures/optifine/ctm/porphyros/3 textures/optifine/ctm/porphyros/4 textures/optifine/ctm/porphyros/5 textures/optifine/ctm/porphyros/6 textures/optifine/ctm/porphyros/7 textures/optifine/ctm/porphyros/8 textures/optifine/ctm/porphyros/9 textures/optifine/ctm/porphyros/10 textures/optifine/ctm/porphyros/11 textures/optifine/ctm/porphyros/12 textures/optifine/ctm/porphyros/13 textures/optifine/ctm/porphyros/14 textures/optifine/ctm/porphyros/15 textures/optifine/ctm/porphyros/16 textures/optifine/ctm/porphyros/17 textures/optifine/ctm/porphyros/18 textures/optifine/ctm/porphyros/19 textures/optifine/ctm/porphyros/20 textures/optifine/ctm/porphyros/21 textures/optifine/ctm/porphyros/22 textures/optifine/ctm/porphyros/23 textures/optifine/ctm/porphyros/24 textures/optifine/ctm/porphyros/25 textures/optifine/ctm/porphyros/26 textures/optifine/ctm/porphyros/27 textures/optifine/ctm/porphyros/28 textures/optifine/ctm/porphyros/29 textures/optifine/ctm/porphyros/30 textures/optifine/ctm/porphyros/31 textures/optifine/ctm/porphyros/32 textures/optifine/ctm/porphyros/33 textures/optifine/ctm/porphyros/34 textures/optifine/ctm/porphyros/35

matchBlocks=erydon:porphyros_block \
  erydon:porphyros_stairs \
  erydon:porphyros_stairs_shallow_bottom \
  erydon:porphyros_stairs_shallow_top \
  erydon:porphyros_slab \
  erydon:porphyros_wall \
  erydon:porphyros_layer \
  erydon:porphyros_layer_multiface \
  erydon:porphyros_layer_vertical \
  erydon:porphyros_slope \
  erydon:porphyros_slope_shallow_upper \
  erydon:porphyros_slope_steep_lower \
  erydon:porphyros_slope_steep_upper \
  erydon:porphyros_slope_shallow_lower \
  erydon:porphyros_slope_vertical \
  erydon:porphyros_slope_vertical_shallow_narrow \
  erydon:porphyros_arch_romanesque \
  erydon:porphyros_slope_vertical_shallow_broad \
  erydon:porphyros_column_circular \
  erydon:porphyros_column_gothic \
  erydon:porphyros_column_square \
  erydon:porphyros_cornice_modern \
  erydon:porphyros_cornice_georgian \
  erydon:porphyros_cornice_guilloche \
  erydon:porphyros_cornice_gothic \
  erydon:porphyros_surround_georgian \
  erydon:porphyros_surround_guilloche \
  erydon:porphyros_surround_gothic_ornate \
  erydon:porphyros_surround_modern \
  erydon:porphyros_stairs_spiral_large \
  erydon:porphyros_light_modern \
  erydon:porphyros_chimney_circular \
  erydon:porphyros_vertical_slice \
  erydon:porphyros_horizontal_slice \
  erydon:porphyros_post \
  erydon:porphyros_wall_georgian \
  erydon:porphyros_alcove_georgian \
  erydon:porphyros_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
