method=repeat
width=6
height=6
tiles=textures/optifine/ctm/porphyros/0 textures/optifine/ctm/porphyros/1 textures/optifine/ctm/porphyros/2 textures/optifine/ctm/porphyros/3 textures/optifine/ctm/porphyros/4 textures/optifine/ctm/porphyros/5 textures/optifine/ctm/porphyros/6 textures/optifine/ctm/porphyros/7 textures/optifine/ctm/porphyros/8 textures/optifine/ctm/porphyros/9 textures/optifine/ctm/porphyros/10 textures/optifine/ctm/porphyros/11 textures/optifine/ctm/porphyros/12 textures/optifine/ctm/porphyros/13 textures/optifine/ctm/porphyros/14 textures/optifine/ctm/porphyros/15 textures/optifine/ctm/porphyros/16 textures/optifine/ctm/porphyros/17 textures/optifine/ctm/porphyros/18 textures/optifine/ctm/porphyros/19 textures/optifine/ctm/porphyros/20 textures/optifine/ctm/porphyros/21 textures/optifine/ctm/porphyros/22 textures/optifine/ctm/porphyros/23 textures/optifine/ctm/porphyros/24 textures/optifine/ctm/porphyros/25 textures/optifine/ctm/porphyros/26 textures/optifine/ctm/porphyros/27 textures/optifine/ctm/porphyros/28 textures/optifine/ctm/porphyros/29 textures/optifine/ctm/porphyros/30 textures/optifine/ctm/porphyros/31 textures/optifine/ctm/porphyros/32 textures/optifine/ctm/porphyros/33 textures/optifine/ctm/porphyros/34 textures/optifine/ctm/porphyros/35

matchBlocks=erydon:porphyros_light_wall
matchTiles=erydon:block/porphyros_block

faces=all
connect=block
innerSeams=true
priority=10
