method=repeat

width=6

height=6

tiles=textures/optifine/ctm/chrysonyx/0 textures/optifine/ctm/chrysonyx/1 textures/optifine/ctm/chrysonyx/2 textures/optifine/ctm/chrysonyx/3 textures/optifine/ctm/chrysonyx/4 textures/optifine/ctm/chrysonyx/5 textures/optifine/ctm/chrysonyx/6 textures/optifine/ctm/chrysonyx/7 textures/optifine/ctm/chrysonyx/8 textures/optifine/ctm/chrysonyx/9 textures/optifine/ctm/chrysonyx/10 textures/optifine/ctm/chrysonyx/11 textures/optifine/ctm/chrysonyx/12 textures/optifine/ctm/chrysonyx/13 textures/optifine/ctm/chrysonyx/14 textures/optifine/ctm/chrysonyx/15 textures/optifine/ctm/chrysonyx/16 textures/optifine/ctm/chrysonyx/17 textures/optifine/ctm/chrysonyx/18 textures/optifine/ctm/chrysonyx/19 textures/optifine/ctm/chrysonyx/20 textures/optifine/ctm/chrysonyx/21 textures/optifine/ctm/chrysonyx/22 textures/optifine/ctm/chrysonyx/23 textures/optifine/ctm/chrysonyx/24 textures/optifine/ctm/chrysonyx/25 textures/optifine/ctm/chrysonyx/26 textures/optifine/ctm/chrysonyx/27 textures/optifine/ctm/chrysonyx/28 textures/optifine/ctm/chrysonyx/29 textures/optifine/ctm/chrysonyx/30 textures/optifine/ctm/chrysonyx/31 textures/optifine/ctm/chrysonyx/32 textures/optifine/ctm/chrysonyx/33 textures/optifine/ctm/chrysonyx/34 textures/optifine/ctm/chrysonyx/35

matchBlocks=erydon:chrysonyx_block \
  erydon:chrysonyx_stairs \
  erydon:chrysonyx_stairs_shallow_bottom \
  erydon:chrysonyx_stairs_shallow_top \
  erydon:chrysonyx_slab \
  erydon:chrysonyx_wall \
  erydon:chrysonyx_layer \
  erydon:chrysonyx_layer_multiface \
  erydon:chrysonyx_layer_vertical \
  erydon:chrysonyx_slope \
  erydon:chrysonyx_slope_shallow_upper \
  erydon:chrysonyx_slope_steep_lower \
  erydon:chrysonyx_slope_steep_upper \
  erydon:chrysonyx_slope_shallow_lower \
  erydon:chrysonyx_slope_vertical \
  erydon:chrysonyx_slope_vertical_shallow_narrow \
  erydon:chrysonyx_arch_romanesque \
  erydon:chrysonyx_slope_vertical_shallow_broad \
  erydon:chrysonyx_column_circular \
  erydon:chrysonyx_column_gothic \
  erydon:chrysonyx_column_square \
  erydon:chrysonyx_cornice_modern \
  erydon:chrysonyx_cornice_georgian \
  erydon:chrysonyx_cornice_guilloche \
  erydon:chrysonyx_cornice_gothic \
  erydon:chrysonyx_surround_georgian \
  erydon:chrysonyx_surround_guilloche \
  erydon:chrysonyx_surround_gothic_ornate \
  erydon:chrysonyx_surround_modern \
  erydon:chrysonyx_stairs_spiral_large \
  erydon:chrysonyx_light_modern \
  erydon:chrysonyx_chimney_circular \
  erydon:chrysonyx_vertical_slice \
  erydon:chrysonyx_horizontal_slice \
  erydon:chrysonyx_post \
  erydon:chrysonyx_wall_georgian \
  erydon:chrysonyx_alcove_georgian \
  erydon:chrysonyx_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
