method=repeat
width=6
height=6
tiles=textures/optifine/ctm/chrysonyx/0 textures/optifine/ctm/chrysonyx/1 textures/optifine/ctm/chrysonyx/2 textures/optifine/ctm/chrysonyx/3 textures/optifine/ctm/chrysonyx/4 textures/optifine/ctm/chrysonyx/5 textures/optifine/ctm/chrysonyx/6 textures/optifine/ctm/chrysonyx/7 textures/optifine/ctm/chrysonyx/8 textures/optifine/ctm/chrysonyx/9 textures/optifine/ctm/chrysonyx/10 textures/optifine/ctm/chrysonyx/11 textures/optifine/ctm/chrysonyx/12 textures/optifine/ctm/chrysonyx/13 textures/optifine/ctm/chrysonyx/14 textures/optifine/ctm/chrysonyx/15 textures/optifine/ctm/chrysonyx/16 textures/optifine/ctm/chrysonyx/17 textures/optifine/ctm/chrysonyx/18 textures/optifine/ctm/chrysonyx/19 textures/optifine/ctm/chrysonyx/20 textures/optifine/ctm/chrysonyx/21 textures/optifine/ctm/chrysonyx/22 textures/optifine/ctm/chrysonyx/23 textures/optifine/ctm/chrysonyx/24 textures/optifine/ctm/chrysonyx/25 textures/optifine/ctm/chrysonyx/26 textures/optifine/ctm/chrysonyx/27 textures/optifine/ctm/chrysonyx/28 textures/optifine/ctm/chrysonyx/29 textures/optifine/ctm/chrysonyx/30 textures/optifine/ctm/chrysonyx/31 textures/optifine/ctm/chrysonyx/32 textures/optifine/ctm/chrysonyx/33 textures/optifine/ctm/chrysonyx/34 textures/optifine/ctm/chrysonyx/35
matchBlocks=erydon:chrysonyx_block_silvertrim \
  erydon:chrysonyx_trim_silver_stairs \
  erydon:chrysonyx_trim_silver_stairs_shallow_bottom \
  erydon:chrysonyx_trim_silver_stairs_shallow_top \
  erydon:chrysonyx_trim_silver_layer_multiface \
  erydon:chrysonyx_trim_silver_slope \
  erydon:chrysonyx_trim_silver_slope_shallow_lower \
  erydon:chrysonyx_trim_silver_slope_shallow_upper \
  erydon:chrysonyx_trim_silver_slope_steep_lower \
  erydon:chrysonyx_trim_silver_slope_steep_upper \
  erydon:chrysonyx_trim_silver_slope_vertical \
  erydon:chrysonyx_trim_silver_slope_vertical_shallow_broad \
  erydon:chrysonyx_trim_silver_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_bronzetrim \
  erydon:chrysonyx_trim_bronze_stairs \
  erydon:chrysonyx_trim_bronze_stairs_shallow_bottom \
  erydon:chrysonyx_trim_bronze_stairs_shallow_top \
  erydon:chrysonyx_trim_bronze_layer_multiface \
  erydon:chrysonyx_trim_bronze_slope \
  erydon:chrysonyx_trim_bronze_slope_shallow_lower \
  erydon:chrysonyx_trim_bronze_slope_shallow_upper \
  erydon:chrysonyx_trim_bronze_slope_steep_lower \
  erydon:chrysonyx_trim_bronze_slope_steep_upper \
  erydon:chrysonyx_trim_bronze_slope_vertical \
  erydon:chrysonyx_trim_bronze_slope_vertical_shallow_broad \
  erydon:chrysonyx_trim_bronze_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_bronzequatrefoil \
  erydon:chrysonyx_quatrefoil_bronze_stairs \
  erydon:chrysonyx_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:chrysonyx_quatrefoil_bronze_stairs_shallow_top \
  erydon:chrysonyx_quatrefoil_bronze_layer_multiface \
  erydon:chrysonyx_quatrefoil_bronze_slope \
  erydon:chrysonyx_quatrefoil_bronze_slope_shallow_lower \
  erydon:chrysonyx_quatrefoil_bronze_slope_shallow_upper \
  erydon:chrysonyx_quatrefoil_bronze_slope_steep_lower \
  erydon:chrysonyx_quatrefoil_bronze_slope_steep_upper \
  erydon:chrysonyx_quatrefoil_bronze_slope_vertical \
  erydon:chrysonyx_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:chrysonyx_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_silverquatrefoil \
  erydon:chrysonyx_quatrefoil_silver_stairs \
  erydon:chrysonyx_quatrefoil_silver_stairs_shallow_bottom \
  erydon:chrysonyx_quatrefoil_silver_stairs_shallow_top \
  erydon:chrysonyx_quatrefoil_silver_layer_multiface \
  erydon:chrysonyx_quatrefoil_silver_slope \
  erydon:chrysonyx_quatrefoil_silver_slope_shallow_lower \
  erydon:chrysonyx_quatrefoil_silver_slope_shallow_upper \
  erydon:chrysonyx_quatrefoil_silver_slope_steep_lower \
  erydon:chrysonyx_quatrefoil_silver_slope_steep_upper \
  erydon:chrysonyx_quatrefoil_silver_slope_vertical \
  erydon:chrysonyx_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:chrysonyx_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_silverrose \
  erydon:chrysonyx_rosette_silver_stairs \
  erydon:chrysonyx_rosette_silver_stairs_shallow_bottom \
  erydon:chrysonyx_rosette_silver_stairs_shallow_top \
  erydon:chrysonyx_rosette_silver_layer_multiface \
  erydon:chrysonyx_rosette_silver_slope \
  erydon:chrysonyx_rosette_silver_slope_shallow_lower \
  erydon:chrysonyx_rosette_silver_slope_shallow_upper \
  erydon:chrysonyx_rosette_silver_slope_steep_lower \
  erydon:chrysonyx_rosette_silver_slope_steep_upper \
  erydon:chrysonyx_rosette_silver_slope_vertical \
  erydon:chrysonyx_rosette_silver_slope_vertical_shallow_broad \
  erydon:chrysonyx_rosette_silver_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_bronzerose \
  erydon:chrysonyx_rosette_bronze_stairs \
  erydon:chrysonyx_rosette_bronze_stairs_shallow_bottom \
  erydon:chrysonyx_rosette_bronze_stairs_shallow_top \
  erydon:chrysonyx_rosette_bronze_layer_multiface \
  erydon:chrysonyx_rosette_bronze_slope \
  erydon:chrysonyx_rosette_bronze_slope_shallow_lower \
  erydon:chrysonyx_rosette_bronze_slope_shallow_upper \
  erydon:chrysonyx_rosette_bronze_slope_steep_lower \
  erydon:chrysonyx_rosette_bronze_slope_steep_upper \
  erydon:chrysonyx_rosette_bronze_slope_vertical \
  erydon:chrysonyx_rosette_bronze_slope_vertical_shallow_broad \
  erydon:chrysonyx_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_silverguilloche \
  erydon:chrysonyx_guilloche_silver_stairs \
  erydon:chrysonyx_guilloche_silver_stairs_shallow_bottom \
  erydon:chrysonyx_guilloche_silver_stairs_shallow_top \
  erydon:chrysonyx_guilloche_silver_layer_multiface \
  erydon:chrysonyx_guilloche_silver_slope \
  erydon:chrysonyx_guilloche_silver_slope_shallow_lower \
  erydon:chrysonyx_guilloche_silver_slope_shallow_upper \
  erydon:chrysonyx_guilloche_silver_slope_steep_lower \
  erydon:chrysonyx_guilloche_silver_slope_steep_upper \
  erydon:chrysonyx_guilloche_silver_slope_vertical \
  erydon:chrysonyx_guilloche_silver_slope_vertical_shallow_broad \
  erydon:chrysonyx_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:chrysonyx_block_bronzeguilloche \
  erydon:chrysonyx_guilloche_bronze_stairs \
  erydon:chrysonyx_guilloche_bronze_stairs_shallow_bottom \
  erydon:chrysonyx_guilloche_bronze_stairs_shallow_top \
  erydon:chrysonyx_guilloche_bronze_layer_multiface \
  erydon:chrysonyx_guilloche_bronze_slope \
  erydon:chrysonyx_guilloche_bronze_slope_shallow_lower \
  erydon:chrysonyx_guilloche_bronze_slope_shallow_upper \
  erydon:chrysonyx_guilloche_bronze_slope_steep_lower \
  erydon:chrysonyx_guilloche_bronze_slope_steep_upper \
  erydon:chrysonyx_guilloche_bronze_slope_vertical \
  erydon:chrysonyx_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:chrysonyx_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
