method=repeat
width=6
height=6
tiles=textures/optifine/ctm/psamatheon_hewn/0 textures/optifine/ctm/psamatheon_hewn/1 textures/optifine/ctm/psamatheon_hewn/2 textures/optifine/ctm/psamatheon_hewn/3 textures/optifine/ctm/psamatheon_hewn/4 textures/optifine/ctm/psamatheon_hewn/5 textures/optifine/ctm/psamatheon_hewn/6 textures/optifine/ctm/psamatheon_hewn/7 textures/optifine/ctm/psamatheon_hewn/8 textures/optifine/ctm/psamatheon_hewn/9 textures/optifine/ctm/psamatheon_hewn/10 textures/optifine/ctm/psamatheon_hewn/11 textures/optifine/ctm/psamatheon_hewn/12 textures/optifine/ctm/psamatheon_hewn/13 textures/optifine/ctm/psamatheon_hewn/14 textures/optifine/ctm/psamatheon_hewn/15 textures/optifine/ctm/psamatheon_hewn/16 textures/optifine/ctm/psamatheon_hewn/17 textures/optifine/ctm/psamatheon_hewn/18 textures/optifine/ctm/psamatheon_hewn/19 textures/optifine/ctm/psamatheon_hewn/20 textures/optifine/ctm/psamatheon_hewn/21 textures/optifine/ctm/psamatheon_hewn/22 textures/optifine/ctm/psamatheon_hewn/23 textures/optifine/ctm/psamatheon_hewn/24 textures/optifine/ctm/psamatheon_hewn/25 textures/optifine/ctm/psamatheon_hewn/26 textures/optifine/ctm/psamatheon_hewn/27 textures/optifine/ctm/psamatheon_hewn/28 textures/optifine/ctm/psamatheon_hewn/29 textures/optifine/ctm/psamatheon_hewn/30 textures/optifine/ctm/psamatheon_hewn/31 textures/optifine/ctm/psamatheon_hewn/32 textures/optifine/ctm/psamatheon_hewn/33 textures/optifine/ctm/psamatheon_hewn/34 textures/optifine/ctm/psamatheon_hewn/35
matchBlocks=erydon:psamatheon_hewn_block \
  erydon:psamatheon_hewn_slab \
  erydon:psamatheon_hewn_layer \
  erydon:psamatheon_hewn_layer_vertical \
  erydon:psamatheon_hewn_slope \
  erydon:psamatheon_hewn_slope_shallow_lower \
  erydon:psamatheon_hewn_slope_shallow_upper \
  erydon:psamatheon_hewn_slope_steep_lower \
  erydon:psamatheon_hewn_slope_steep_upper \
  erydon:psamatheon_hewn_slope_vertical \
  erydon:psamatheon_hewn_slope_vertical_shallow_narrow \
  erydon:psamatheon_hewn_slope_vertical_shallow_broad \
  erydon:psamatheon_hewn_arch_romanesque \
  erydon:psamatheon_hewn_vertical_slice \
  erydon:psamatheon_hewn_horizontal_slice \
  erydon:psamatheon_hewn_post \
  erydon:psamatheon_hewn_stairs \
  erydon:psamatheon_hewn_wall \
  erydon:psamatheon_hewn_alcove_georgian \
  erydon:psamatheon_hewn_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
