method=repeat

width=6

height=6

tiles=textures/optifine/ctm/calacattum_ashlar/0 textures/optifine/ctm/calacattum_ashlar/1 textures/optifine/ctm/calacattum_ashlar/2 textures/optifine/ctm/calacattum_ashlar/3 textures/optifine/ctm/calacattum_ashlar/4 textures/optifine/ctm/calacattum_ashlar/5 textures/optifine/ctm/calacattum_ashlar/6 textures/optifine/ctm/calacattum_ashlar/7 textures/optifine/ctm/calacattum_ashlar/8 textures/optifine/ctm/calacattum_ashlar/9 textures/optifine/ctm/calacattum_ashlar/10 textures/optifine/ctm/calacattum_ashlar/11 textures/optifine/ctm/calacattum_ashlar/12 textures/optifine/ctm/calacattum_ashlar/13 textures/optifine/ctm/calacattum_ashlar/14 textures/optifine/ctm/calacattum_ashlar/15 textures/optifine/ctm/calacattum_ashlar/16 textures/optifine/ctm/calacattum_ashlar/17 textures/optifine/ctm/calacattum_ashlar/18 textures/optifine/ctm/calacattum_ashlar/19 textures/optifine/ctm/calacattum_ashlar/20 textures/optifine/ctm/calacattum_ashlar/21 textures/optifine/ctm/calacattum_ashlar/22 textures/optifine/ctm/calacattum_ashlar/23 textures/optifine/ctm/calacattum_ashlar/24 textures/optifine/ctm/calacattum_ashlar/25 textures/optifine/ctm/calacattum_ashlar/26 textures/optifine/ctm/calacattum_ashlar/27 textures/optifine/ctm/calacattum_ashlar/28 textures/optifine/ctm/calacattum_ashlar/29 textures/optifine/ctm/calacattum_ashlar/30 textures/optifine/ctm/calacattum_ashlar/31 textures/optifine/ctm/calacattum_ashlar/32 textures/optifine/ctm/calacattum_ashlar/33 textures/optifine/ctm/calacattum_ashlar/34 textures/optifine/ctm/calacattum_ashlar/35

matchBlocks=erydon:calacattum_ashlar_block \
  erydon:calacattum_ashlar_slab \
  erydon:calacattum_ashlar_wall \
  erydon:calacattum_ashlar_layer \
  erydon:calacattum_ashlar_layer_multiface \
  erydon:calacattum_ashlar_layer_vertical \
  erydon:calacattum_ashlar_slope \
  erydon:calacattum_ashlar_slope_shallow_upper \
  erydon:calacattum_ashlar_slope_steep_lower \
  erydon:calacattum_ashlar_slope_steep_upper \
  erydon:calacattum_ashlar_slope_shallow_lower \
  erydon:calacattum_ashlar_slope_vertical \
  erydon:calacattum_ashlar_stairs_spiral_large \
  erydon:calacattum_ashlar_slope_vertical_shallow_narrow \
  erydon:calacattum_ashlar_arch_romanesque \
  erydon:calacattum_ashlar_slope_vertical_shallow_broad \
  erydon:calacattum_ashlar_chimney_circular \
  erydon:calacattum_ashlar_vertical_slice \
  erydon:calacattum_ashlar_horizontal_slice \
  erydon:calacattum_ashlar_post \
  erydon:calacattum_ashlar_wall_georgian \
  erydon:calacattum_ashlar_alcove_georgian \
  erydon:calacattum_ashlar_alcove_gothic
faces=top bottom north south east west

connect=block

innerSeams=true

priority=10
