method=repeat
width=6
height=6
tiles=textures/optifine/ctm/glacium/0 textures/optifine/ctm/glacium/1 textures/optifine/ctm/glacium/2 textures/optifine/ctm/glacium/3 textures/optifine/ctm/glacium/4 textures/optifine/ctm/glacium/5 textures/optifine/ctm/glacium/6 textures/optifine/ctm/glacium/7 textures/optifine/ctm/glacium/8 textures/optifine/ctm/glacium/9 textures/optifine/ctm/glacium/10 textures/optifine/ctm/glacium/11 textures/optifine/ctm/glacium/12 textures/optifine/ctm/glacium/13 textures/optifine/ctm/glacium/14 textures/optifine/ctm/glacium/15 textures/optifine/ctm/glacium/16 textures/optifine/ctm/glacium/17 textures/optifine/ctm/glacium/18 textures/optifine/ctm/glacium/19 textures/optifine/ctm/glacium/20 textures/optifine/ctm/glacium/21 textures/optifine/ctm/glacium/22 textures/optifine/ctm/glacium/23 textures/optifine/ctm/glacium/24 textures/optifine/ctm/glacium/25 textures/optifine/ctm/glacium/26 textures/optifine/ctm/glacium/27 textures/optifine/ctm/glacium/28 textures/optifine/ctm/glacium/29 textures/optifine/ctm/glacium/30 textures/optifine/ctm/glacium/31 textures/optifine/ctm/glacium/32 textures/optifine/ctm/glacium/33 textures/optifine/ctm/glacium/34 textures/optifine/ctm/glacium/35
matchBlocks=erydon:glacium_block_silvertrim \
  erydon:glacium_block_bronzetrim \
  erydon:glacium_block_bronzequatrefoil \
  erydon:glacium_block_silverquatrefoil \
  erydon:glacium_block_silverrose \
  erydon:glacium_block_bronzerose \
  erydon:glacium_block_silverguilloche \
  erydon:glacium_block_bronzeguilloche
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
