method=repeat
width=6
height=6
tiles=textures/optifine/ctm/imperium/0 textures/optifine/ctm/imperium/1 textures/optifine/ctm/imperium/2 textures/optifine/ctm/imperium/3 textures/optifine/ctm/imperium/4 textures/optifine/ctm/imperium/5 textures/optifine/ctm/imperium/6 textures/optifine/ctm/imperium/7 textures/optifine/ctm/imperium/8 textures/optifine/ctm/imperium/9 textures/optifine/ctm/imperium/10 textures/optifine/ctm/imperium/11 textures/optifine/ctm/imperium/12 textures/optifine/ctm/imperium/13 textures/optifine/ctm/imperium/14 textures/optifine/ctm/imperium/15 textures/optifine/ctm/imperium/16 textures/optifine/ctm/imperium/17 textures/optifine/ctm/imperium/18 textures/optifine/ctm/imperium/19 textures/optifine/ctm/imperium/20 textures/optifine/ctm/imperium/21 textures/optifine/ctm/imperium/22 textures/optifine/ctm/imperium/23 textures/optifine/ctm/imperium/24 textures/optifine/ctm/imperium/25 textures/optifine/ctm/imperium/26 textures/optifine/ctm/imperium/27 textures/optifine/ctm/imperium/28 textures/optifine/ctm/imperium/29 textures/optifine/ctm/imperium/30 textures/optifine/ctm/imperium/31 textures/optifine/ctm/imperium/32 textures/optifine/ctm/imperium/33 textures/optifine/ctm/imperium/34 textures/optifine/ctm/imperium/35

matchBlocks=erydon:imperium_ceiling_coffered_guilloche_white_small
matchTiles=erydon:block/imperium_block

faces=all
connect=block
innerSeams=true
priority=10
