method=repeat
width=6
height=6
tiles=textures/optifine/ctm/imperium/0 textures/optifine/ctm/imperium/1 textures/optifine/ctm/imperium/2 textures/optifine/ctm/imperium/3 textures/optifine/ctm/imperium/4 textures/optifine/ctm/imperium/5 textures/optifine/ctm/imperium/6 textures/optifine/ctm/imperium/7 textures/optifine/ctm/imperium/8 textures/optifine/ctm/imperium/9 textures/optifine/ctm/imperium/10 textures/optifine/ctm/imperium/11 textures/optifine/ctm/imperium/12 textures/optifine/ctm/imperium/13 textures/optifine/ctm/imperium/14 textures/optifine/ctm/imperium/15 textures/optifine/ctm/imperium/16 textures/optifine/ctm/imperium/17 textures/optifine/ctm/imperium/18 textures/optifine/ctm/imperium/19 textures/optifine/ctm/imperium/20 textures/optifine/ctm/imperium/21 textures/optifine/ctm/imperium/22 textures/optifine/ctm/imperium/23 textures/optifine/ctm/imperium/24 textures/optifine/ctm/imperium/25 textures/optifine/ctm/imperium/26 textures/optifine/ctm/imperium/27 textures/optifine/ctm/imperium/28 textures/optifine/ctm/imperium/29 textures/optifine/ctm/imperium/30 textures/optifine/ctm/imperium/31 textures/optifine/ctm/imperium/32 textures/optifine/ctm/imperium/33 textures/optifine/ctm/imperium/34 textures/optifine/ctm/imperium/35
matchBlocks=erydon:imperium_block_silvertrim \
  erydon:imperium_trim_silver_stairs \
  erydon:imperium_trim_silver_stairs_shallow_bottom \
  erydon:imperium_trim_silver_stairs_shallow_top \
  erydon:imperium_trim_silver_layer_multiface \
  erydon:imperium_trim_silver_slope \
  erydon:imperium_trim_silver_slope_shallow_lower \
  erydon:imperium_trim_silver_slope_shallow_upper \
  erydon:imperium_trim_silver_slope_steep_lower \
  erydon:imperium_trim_silver_slope_steep_upper \
  erydon:imperium_trim_silver_slope_vertical \
  erydon:imperium_trim_silver_slope_vertical_shallow_broad \
  erydon:imperium_trim_silver_slope_vertical_shallow_narrow \
  erydon:imperium_block_bronzetrim \
  erydon:imperium_trim_bronze_stairs \
  erydon:imperium_trim_bronze_stairs_shallow_bottom \
  erydon:imperium_trim_bronze_stairs_shallow_top \
  erydon:imperium_trim_bronze_layer_multiface \
  erydon:imperium_trim_bronze_slope \
  erydon:imperium_trim_bronze_slope_shallow_lower \
  erydon:imperium_trim_bronze_slope_shallow_upper \
  erydon:imperium_trim_bronze_slope_steep_lower \
  erydon:imperium_trim_bronze_slope_steep_upper \
  erydon:imperium_trim_bronze_slope_vertical \
  erydon:imperium_trim_bronze_slope_vertical_shallow_broad \
  erydon:imperium_trim_bronze_slope_vertical_shallow_narrow \
  erydon:imperium_block_bronzequatrefoil \
  erydon:imperium_quatrefoil_bronze_stairs \
  erydon:imperium_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:imperium_quatrefoil_bronze_stairs_shallow_top \
  erydon:imperium_quatrefoil_bronze_layer_multiface \
  erydon:imperium_quatrefoil_bronze_slope \
  erydon:imperium_quatrefoil_bronze_slope_shallow_lower \
  erydon:imperium_quatrefoil_bronze_slope_shallow_upper \
  erydon:imperium_quatrefoil_bronze_slope_steep_lower \
  erydon:imperium_quatrefoil_bronze_slope_steep_upper \
  erydon:imperium_quatrefoil_bronze_slope_vertical \
  erydon:imperium_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:imperium_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:imperium_block_silverquatrefoil \
  erydon:imperium_quatrefoil_silver_stairs \
  erydon:imperium_quatrefoil_silver_stairs_shallow_bottom \
  erydon:imperium_quatrefoil_silver_stairs_shallow_top \
  erydon:imperium_quatrefoil_silver_layer_multiface \
  erydon:imperium_quatrefoil_silver_slope \
  erydon:imperium_quatrefoil_silver_slope_shallow_lower \
  erydon:imperium_quatrefoil_silver_slope_shallow_upper \
  erydon:imperium_quatrefoil_silver_slope_steep_lower \
  erydon:imperium_quatrefoil_silver_slope_steep_upper \
  erydon:imperium_quatrefoil_silver_slope_vertical \
  erydon:imperium_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:imperium_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:imperium_block_silverrose \
  erydon:imperium_rosette_silver_stairs \
  erydon:imperium_rosette_silver_stairs_shallow_bottom \
  erydon:imperium_rosette_silver_stairs_shallow_top \
  erydon:imperium_rosette_silver_layer_multiface \
  erydon:imperium_rosette_silver_slope \
  erydon:imperium_rosette_silver_slope_shallow_lower \
  erydon:imperium_rosette_silver_slope_shallow_upper \
  erydon:imperium_rosette_silver_slope_steep_lower \
  erydon:imperium_rosette_silver_slope_steep_upper \
  erydon:imperium_rosette_silver_slope_vertical \
  erydon:imperium_rosette_silver_slope_vertical_shallow_broad \
  erydon:imperium_rosette_silver_slope_vertical_shallow_narrow \
  erydon:imperium_block_bronzerose \
  erydon:imperium_rosette_bronze_stairs \
  erydon:imperium_rosette_bronze_stairs_shallow_bottom \
  erydon:imperium_rosette_bronze_stairs_shallow_top \
  erydon:imperium_rosette_bronze_layer_multiface \
  erydon:imperium_rosette_bronze_slope \
  erydon:imperium_rosette_bronze_slope_shallow_lower \
  erydon:imperium_rosette_bronze_slope_shallow_upper \
  erydon:imperium_rosette_bronze_slope_steep_lower \
  erydon:imperium_rosette_bronze_slope_steep_upper \
  erydon:imperium_rosette_bronze_slope_vertical \
  erydon:imperium_rosette_bronze_slope_vertical_shallow_broad \
  erydon:imperium_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:imperium_block_silverguilloche \
  erydon:imperium_guilloche_silver_stairs \
  erydon:imperium_guilloche_silver_stairs_shallow_bottom \
  erydon:imperium_guilloche_silver_stairs_shallow_top \
  erydon:imperium_guilloche_silver_layer_multiface \
  erydon:imperium_guilloche_silver_slope \
  erydon:imperium_guilloche_silver_slope_shallow_lower \
  erydon:imperium_guilloche_silver_slope_shallow_upper \
  erydon:imperium_guilloche_silver_slope_steep_lower \
  erydon:imperium_guilloche_silver_slope_steep_upper \
  erydon:imperium_guilloche_silver_slope_vertical \
  erydon:imperium_guilloche_silver_slope_vertical_shallow_broad \
  erydon:imperium_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:imperium_block_bronzeguilloche \
  erydon:imperium_guilloche_bronze_stairs \
  erydon:imperium_guilloche_bronze_stairs_shallow_bottom \
  erydon:imperium_guilloche_bronze_stairs_shallow_top \
  erydon:imperium_guilloche_bronze_layer_multiface \
  erydon:imperium_guilloche_bronze_slope \
  erydon:imperium_guilloche_bronze_slope_shallow_lower \
  erydon:imperium_guilloche_bronze_slope_shallow_upper \
  erydon:imperium_guilloche_bronze_slope_steep_lower \
  erydon:imperium_guilloche_bronze_slope_steep_upper \
  erydon:imperium_guilloche_bronze_slope_vertical \
  erydon:imperium_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:imperium_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
