method=repeat

width=6

height=6

tiles=textures/optifine/ctm/latmion/0 textures/optifine/ctm/latmion/1 textures/optifine/ctm/latmion/2 textures/optifine/ctm/latmion/3 textures/optifine/ctm/latmion/4 textures/optifine/ctm/latmion/5 textures/optifine/ctm/latmion/6 textures/optifine/ctm/latmion/7 textures/optifine/ctm/latmion/8 textures/optifine/ctm/latmion/9 textures/optifine/ctm/latmion/10 textures/optifine/ctm/latmion/11 textures/optifine/ctm/latmion/12 textures/optifine/ctm/latmion/13 textures/optifine/ctm/latmion/14 textures/optifine/ctm/latmion/15 textures/optifine/ctm/latmion/16 textures/optifine/ctm/latmion/17 textures/optifine/ctm/latmion/18 textures/optifine/ctm/latmion/19 textures/optifine/ctm/latmion/20 textures/optifine/ctm/latmion/21 textures/optifine/ctm/latmion/22 textures/optifine/ctm/latmion/23 textures/optifine/ctm/latmion/24 textures/optifine/ctm/latmion/25 textures/optifine/ctm/latmion/26 textures/optifine/ctm/latmion/27 textures/optifine/ctm/latmion/28 textures/optifine/ctm/latmion/29 textures/optifine/ctm/latmion/30 textures/optifine/ctm/latmion/31 textures/optifine/ctm/latmion/32 textures/optifine/ctm/latmion/33 textures/optifine/ctm/latmion/34 textures/optifine/ctm/latmion/35

matchBlocks=erydon:latmion_block \
  erydon:latmion_stairs \
  erydon:latmion_stairs_shallow_bottom \
  erydon:latmion_stairs_shallow_top \
  erydon:latmion_slab \
  erydon:latmion_wall \
  erydon:latmion_layer \
  erydon:latmion_layer_multiface \
  erydon:latmion_layer_vertical \
  erydon:latmion_slope \
  erydon:latmion_slope_shallow_upper \
  erydon:latmion_slope_steep_lower \
  erydon:latmion_slope_steep_upper \
  erydon:latmion_slope_shallow_lower \
  erydon:latmion_slope_vertical \
  erydon:latmion_slope_vertical_shallow_narrow \
  erydon:latmion_arch_romanesque \
  erydon:latmion_slope_vertical_shallow_broad \
  erydon:latmion_column_circular \
  erydon:latmion_column_gothic \
  erydon:latmion_column_square \
  erydon:latmion_cornice_modern \
  erydon:latmion_cornice_georgian \
  erydon:latmion_cornice_guilloche \
  erydon:latmion_cornice_gothic \
  erydon:latmion_surround_georgian \
  erydon:latmion_surround_guilloche \
  erydon:latmion_surround_gothic_ornate \
  erydon:latmion_surround_modern \
  erydon:latmion_stairs_spiral_large \
  erydon:latmion_light_modern \
  erydon:latmion_chimney_circular \
  erydon:latmion_vertical_slice \
  erydon:latmion_horizontal_slice \
  erydon:latmion_post \
  erydon:latmion_wall_georgian \
  erydon:latmion_alcove_georgian \
  erydon:latmion_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
