method=repeat
width=6
height=6
tiles=textures/optifine/ctm/latmion/0 textures/optifine/ctm/latmion/1 textures/optifine/ctm/latmion/2 textures/optifine/ctm/latmion/3 textures/optifine/ctm/latmion/4 textures/optifine/ctm/latmion/5 textures/optifine/ctm/latmion/6 textures/optifine/ctm/latmion/7 textures/optifine/ctm/latmion/8 textures/optifine/ctm/latmion/9 textures/optifine/ctm/latmion/10 textures/optifine/ctm/latmion/11 textures/optifine/ctm/latmion/12 textures/optifine/ctm/latmion/13 textures/optifine/ctm/latmion/14 textures/optifine/ctm/latmion/15 textures/optifine/ctm/latmion/16 textures/optifine/ctm/latmion/17 textures/optifine/ctm/latmion/18 textures/optifine/ctm/latmion/19 textures/optifine/ctm/latmion/20 textures/optifine/ctm/latmion/21 textures/optifine/ctm/latmion/22 textures/optifine/ctm/latmion/23 textures/optifine/ctm/latmion/24 textures/optifine/ctm/latmion/25 textures/optifine/ctm/latmion/26 textures/optifine/ctm/latmion/27 textures/optifine/ctm/latmion/28 textures/optifine/ctm/latmion/29 textures/optifine/ctm/latmion/30 textures/optifine/ctm/latmion/31 textures/optifine/ctm/latmion/32 textures/optifine/ctm/latmion/33 textures/optifine/ctm/latmion/34 textures/optifine/ctm/latmion/35

matchBlocks=erydon:latmion_light_wall
matchTiles=erydon:block/latmion_block

faces=all
connect=block
innerSeams=true
priority=10
