method=repeat
width=6
height=6
tiles=textures/optifine/ctm/nerium_aged/0 textures/optifine/ctm/nerium_aged/1 textures/optifine/ctm/nerium_aged/2 textures/optifine/ctm/nerium_aged/3 textures/optifine/ctm/nerium_aged/4 textures/optifine/ctm/nerium_aged/5 textures/optifine/ctm/nerium_aged/6 textures/optifine/ctm/nerium_aged/7 textures/optifine/ctm/nerium_aged/8 textures/optifine/ctm/nerium_aged/9 textures/optifine/ctm/nerium_aged/10 textures/optifine/ctm/nerium_aged/11 textures/optifine/ctm/nerium_aged/12 textures/optifine/ctm/nerium_aged/13 textures/optifine/ctm/nerium_aged/14 textures/optifine/ctm/nerium_aged/15 textures/optifine/ctm/nerium_aged/16 textures/optifine/ctm/nerium_aged/17 textures/optifine/ctm/nerium_aged/18 textures/optifine/ctm/nerium_aged/19 textures/optifine/ctm/nerium_aged/20 textures/optifine/ctm/nerium_aged/21 textures/optifine/ctm/nerium_aged/22 textures/optifine/ctm/nerium_aged/23 textures/optifine/ctm/nerium_aged/24 textures/optifine/ctm/nerium_aged/25 textures/optifine/ctm/nerium_aged/26 textures/optifine/ctm/nerium_aged/27 textures/optifine/ctm/nerium_aged/28 textures/optifine/ctm/nerium_aged/29 textures/optifine/ctm/nerium_aged/30 textures/optifine/ctm/nerium_aged/31 textures/optifine/ctm/nerium_aged/32 textures/optifine/ctm/nerium_aged/33 textures/optifine/ctm/nerium_aged/34 textures/optifine/ctm/nerium_aged/35
matchBlocks=erydon:nerium_block_aged \
  erydon:nerium_stairs_aged \
  erydon:nerium_stairs_shallow_bottom_aged \
  erydon:nerium_stairs_shallow_top_aged \
  erydon:nerium_slab_aged \
  erydon:nerium_wall_aged \
  erydon:nerium_layer_aged \
  erydon:nerium_layer_multiface_aged \
  erydon:nerium_layer_vertical_aged \
  erydon:nerium_slope_aged \
  erydon:nerium_slope_shallow_upper_aged \
  erydon:nerium_slope_steep_lower_aged \
  erydon:nerium_slope_steep_upper_aged \
  erydon:nerium_slope_shallow_lower_aged \
  erydon:nerium_slope_vertical_aged \
  erydon:nerium_slope_vertical_shallow_narrow_aged \
  erydon:nerium_arch_romanesque_aged \
  erydon:nerium_slope_vertical_shallow_broad_aged \
  erydon:nerium_column_circular_aged \
  erydon:nerium_aged_column_gothic \
  erydon:nerium_column_square_aged \
  erydon:nerium_cornice_modern_aged \
  erydon:nerium_cornice_georgian_aged \
  erydon:nerium_cornice_guilloche_aged \
  erydon:nerium_aged_cornice_gothic \
  erydon:nerium_surround_georgian_aged \
  erydon:nerium_surround_guilloche_aged \
  erydon:nerium_aged_surround_gothic_ornate \
  erydon:nerium_surround_modern_aged \
  erydon:nerium_stairs_spiral_large_aged \
  erydon:nerium_chimney_circular_aged \
  erydon:nerium_vertical_slice_aged \
  erydon:nerium_horizontal_slice_aged \
  erydon:nerium_post_aged \
  erydon:nerium_wall_georgian_aged \
  erydon:nerium_aged_alcove_georgian \
  erydon:nerium_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
