method=repeat

width=6

height=6

tiles=textures/optifine/ctm/aganite/0 textures/optifine/ctm/aganite/1 textures/optifine/ctm/aganite/2 textures/optifine/ctm/aganite/3 textures/optifine/ctm/aganite/4 textures/optifine/ctm/aganite/5 textures/optifine/ctm/aganite/6 textures/optifine/ctm/aganite/7 textures/optifine/ctm/aganite/8 textures/optifine/ctm/aganite/9 textures/optifine/ctm/aganite/10 textures/optifine/ctm/aganite/11 textures/optifine/ctm/aganite/12 textures/optifine/ctm/aganite/13 textures/optifine/ctm/aganite/14 textures/optifine/ctm/aganite/15 textures/optifine/ctm/aganite/16 textures/optifine/ctm/aganite/17 textures/optifine/ctm/aganite/18 textures/optifine/ctm/aganite/19 textures/optifine/ctm/aganite/20 textures/optifine/ctm/aganite/21 textures/optifine/ctm/aganite/22 textures/optifine/ctm/aganite/23 textures/optifine/ctm/aganite/24 textures/optifine/ctm/aganite/25 textures/optifine/ctm/aganite/26 textures/optifine/ctm/aganite/27 textures/optifine/ctm/aganite/28 textures/optifine/ctm/aganite/29 textures/optifine/ctm/aganite/30 textures/optifine/ctm/aganite/31 textures/optifine/ctm/aganite/32 textures/optifine/ctm/aganite/33 textures/optifine/ctm/aganite/34 textures/optifine/ctm/aganite/35

matchBlocks=erydon:aganite_block \
  erydon:aganite_stairs \
  erydon:aganite_stairs_shallow_bottom \
  erydon:aganite_stairs_shallow_top \
  erydon:aganite_slab \
  erydon:aganite_wall \
  erydon:aganite_layer \
  erydon:aganite_layer_multiface \
  erydon:aganite_layer_vertical \
  erydon:aganite_slope \
  erydon:aganite_slope_shallow_upper \
  erydon:aganite_slope_steep_lower \
  erydon:aganite_slope_steep_upper \
  erydon:aganite_slope_shallow_lower \
  erydon:aganite_slope_vertical \
  erydon:aganite_slope_vertical_shallow_narrow \
  erydon:aganite_arch_romanesque \
  erydon:aganite_slope_vertical_shallow_broad \
  erydon:aganite_column_circular \
  erydon:aganite_column_gothic \
  erydon:aganite_column_square \
  erydon:aganite_cornice_modern \
  erydon:aganite_cornice_georgian \
  erydon:aganite_cornice_guilloche \
  erydon:aganite_cornice_gothic \
  erydon:aganite_surround_georgian \
  erydon:aganite_surround_guilloche \
  erydon:aganite_surround_gothic_ornate \
  erydon:aganite_surround_modern \
  erydon:aganite_stairs_spiral_large \
  erydon:aganite_light_modern \
  erydon:aganite_chimney_circular \
  erydon:aganite_vertical_slice \
  erydon:aganite_horizontal_slice \
  erydon:aganite_post \
  erydon:aganite_wall_georgian \
  erydon:aganite_alcove_georgian \
  erydon:aganite_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
