method=repeat
width=6
height=6
tiles=textures/optifine/ctm/aganite/0 textures/optifine/ctm/aganite/1 textures/optifine/ctm/aganite/2 textures/optifine/ctm/aganite/3 textures/optifine/ctm/aganite/4 textures/optifine/ctm/aganite/5 textures/optifine/ctm/aganite/6 textures/optifine/ctm/aganite/7 textures/optifine/ctm/aganite/8 textures/optifine/ctm/aganite/9 textures/optifine/ctm/aganite/10 textures/optifine/ctm/aganite/11 textures/optifine/ctm/aganite/12 textures/optifine/ctm/aganite/13 textures/optifine/ctm/aganite/14 textures/optifine/ctm/aganite/15 textures/optifine/ctm/aganite/16 textures/optifine/ctm/aganite/17 textures/optifine/ctm/aganite/18 textures/optifine/ctm/aganite/19 textures/optifine/ctm/aganite/20 textures/optifine/ctm/aganite/21 textures/optifine/ctm/aganite/22 textures/optifine/ctm/aganite/23 textures/optifine/ctm/aganite/24 textures/optifine/ctm/aganite/25 textures/optifine/ctm/aganite/26 textures/optifine/ctm/aganite/27 textures/optifine/ctm/aganite/28 textures/optifine/ctm/aganite/29 textures/optifine/ctm/aganite/30 textures/optifine/ctm/aganite/31 textures/optifine/ctm/aganite/32 textures/optifine/ctm/aganite/33 textures/optifine/ctm/aganite/34 textures/optifine/ctm/aganite/35
matchBlocks=erydon:aganite_block_silvertrim \
  erydon:aganite_block_bronzetrim \
  erydon:aganite_block_bronzequatrefoil \
  erydon:aganite_block_silverquatrefoil \
  erydon:aganite_block_silverrose \
  erydon:aganite_block_bronzerose \
  erydon:aganite_block_silverguilloche \
  erydon:aganite_block_bronzeguilloche
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
