method=repeat
width=6
height=6
tiles=textures/optifine/ctm/glacium_aged/0 textures/optifine/ctm/glacium_aged/1 textures/optifine/ctm/glacium_aged/2 textures/optifine/ctm/glacium_aged/3 textures/optifine/ctm/glacium_aged/4 textures/optifine/ctm/glacium_aged/5 textures/optifine/ctm/glacium_aged/6 textures/optifine/ctm/glacium_aged/7 textures/optifine/ctm/glacium_aged/8 textures/optifine/ctm/glacium_aged/9 textures/optifine/ctm/glacium_aged/10 textures/optifine/ctm/glacium_aged/11 textures/optifine/ctm/glacium_aged/12 textures/optifine/ctm/glacium_aged/13 textures/optifine/ctm/glacium_aged/14 textures/optifine/ctm/glacium_aged/15 textures/optifine/ctm/glacium_aged/16 textures/optifine/ctm/glacium_aged/17 textures/optifine/ctm/glacium_aged/18 textures/optifine/ctm/glacium_aged/19 textures/optifine/ctm/glacium_aged/20 textures/optifine/ctm/glacium_aged/21 textures/optifine/ctm/glacium_aged/22 textures/optifine/ctm/glacium_aged/23 textures/optifine/ctm/glacium_aged/24 textures/optifine/ctm/glacium_aged/25 textures/optifine/ctm/glacium_aged/26 textures/optifine/ctm/glacium_aged/27 textures/optifine/ctm/glacium_aged/28 textures/optifine/ctm/glacium_aged/29 textures/optifine/ctm/glacium_aged/30 textures/optifine/ctm/glacium_aged/31 textures/optifine/ctm/glacium_aged/32 textures/optifine/ctm/glacium_aged/33 textures/optifine/ctm/glacium_aged/34 textures/optifine/ctm/glacium_aged/35
matchBlocks=erydon:glacium_block_aged \
  erydon:glacium_stairs_aged \
  erydon:glacium_stairs_shallow_bottom_aged \
  erydon:glacium_stairs_shallow_top_aged \
  erydon:glacium_slab_aged \
  erydon:glacium_wall_aged \
  erydon:glacium_layer_aged \
  erydon:glacium_layer_multiface_aged \
  erydon:glacium_layer_vertical_aged \
  erydon:glacium_slope_aged \
  erydon:glacium_slope_shallow_upper_aged \
  erydon:glacium_slope_steep_lower_aged \
  erydon:glacium_slope_steep_upper_aged \
  erydon:glacium_slope_shallow_lower_aged \
  erydon:glacium_slope_vertical_aged \
  erydon:glacium_slope_vertical_shallow_narrow_aged \
  erydon:glacium_arch_romanesque_aged \
  erydon:glacium_slope_vertical_shallow_broad_aged \
  erydon:glacium_column_circular_aged \
  erydon:glacium_aged_column_gothic \
  erydon:glacium_column_square_aged \
  erydon:glacium_cornice_modern_aged \
  erydon:glacium_cornice_georgian_aged \
  erydon:glacium_cornice_guilloche_aged \
  erydon:glacium_aged_cornice_gothic \
  erydon:glacium_surround_georgian_aged \
  erydon:glacium_surround_guilloche_aged \
  erydon:glacium_aged_surround_gothic_ornate \
  erydon:glacium_surround_modern_aged \
  erydon:glacium_stairs_spiral_large_aged \
  erydon:glacium_chimney_circular_aged \
  erydon:glacium_vertical_slice_aged \
  erydon:glacium_horizontal_slice_aged \
  erydon:glacium_post_aged \
  erydon:glacium_wall_georgian_aged \
  erydon:glacium_aged_alcove_georgian \
  erydon:glacium_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
