method=repeat

width=6

height=6

tiles=textures/optifine/ctm/etruscus/0 textures/optifine/ctm/etruscus/1 textures/optifine/ctm/etruscus/2 textures/optifine/ctm/etruscus/3 textures/optifine/ctm/etruscus/4 textures/optifine/ctm/etruscus/5 textures/optifine/ctm/etruscus/6 textures/optifine/ctm/etruscus/7 textures/optifine/ctm/etruscus/8 textures/optifine/ctm/etruscus/9 textures/optifine/ctm/etruscus/10 textures/optifine/ctm/etruscus/11 textures/optifine/ctm/etruscus/12 textures/optifine/ctm/etruscus/13 textures/optifine/ctm/etruscus/14 textures/optifine/ctm/etruscus/15 textures/optifine/ctm/etruscus/16 textures/optifine/ctm/etruscus/17 textures/optifine/ctm/etruscus/18 textures/optifine/ctm/etruscus/19 textures/optifine/ctm/etruscus/20 textures/optifine/ctm/etruscus/21 textures/optifine/ctm/etruscus/22 textures/optifine/ctm/etruscus/23 textures/optifine/ctm/etruscus/24 textures/optifine/ctm/etruscus/25 textures/optifine/ctm/etruscus/26 textures/optifine/ctm/etruscus/27 textures/optifine/ctm/etruscus/28 textures/optifine/ctm/etruscus/29 textures/optifine/ctm/etruscus/30 textures/optifine/ctm/etruscus/31 textures/optifine/ctm/etruscus/32 textures/optifine/ctm/etruscus/33 textures/optifine/ctm/etruscus/34 textures/optifine/ctm/etruscus/35

matchBlocks=erydon:etruscus_block \
  erydon:etruscus_stairs \
  erydon:etruscus_stairs_shallow_bottom \
  erydon:etruscus_stairs_shallow_top \
  erydon:etruscus_slab \
  erydon:etruscus_wall \
  erydon:etruscus_layer \
  erydon:etruscus_layer_multiface \
  erydon:etruscus_layer_vertical \
  erydon:etruscus_slope \
  erydon:etruscus_slope_shallow_upper \
  erydon:etruscus_slope_steep_lower \
  erydon:etruscus_slope_steep_upper \
  erydon:etruscus_slope_shallow_lower \
  erydon:etruscus_slope_vertical \
  erydon:etruscus_slope_vertical_shallow_narrow \
  erydon:etruscus_arch_romanesque \
  erydon:etruscus_slope_vertical_shallow_broad \
  erydon:etruscus_column_circular \
  erydon:etruscus_column_gothic \
  erydon:etruscus_column_square \
  erydon:etruscus_cornice_modern \
  erydon:etruscus_cornice_georgian \
  erydon:etruscus_cornice_guilloche \
  erydon:etruscus_cornice_gothic \
  erydon:etruscus_surround_georgian \
  erydon:etruscus_surround_guilloche \
  erydon:etruscus_surround_gothic_ornate \
  erydon:etruscus_surround_modern \
  erydon:etruscus_stairs_spiral_large \
  erydon:etruscus_light_modern \
  erydon:etruscus_chimney_circular \
  erydon:etruscus_vertical_slice \
  erydon:etruscus_horizontal_slice \
  erydon:etruscus_post \
  erydon:etruscus_wall_georgian \
  erydon:etruscus_alcove_georgian \
  erydon:etruscus_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
