method=repeat
width=6
height=6
tiles=textures/optifine/ctm/hesperion/0 textures/optifine/ctm/hesperion/1 textures/optifine/ctm/hesperion/2 textures/optifine/ctm/hesperion/3 textures/optifine/ctm/hesperion/4 textures/optifine/ctm/hesperion/5 textures/optifine/ctm/hesperion/6 textures/optifine/ctm/hesperion/7 textures/optifine/ctm/hesperion/8 textures/optifine/ctm/hesperion/9 textures/optifine/ctm/hesperion/10 textures/optifine/ctm/hesperion/11 textures/optifine/ctm/hesperion/12 textures/optifine/ctm/hesperion/13 textures/optifine/ctm/hesperion/14 textures/optifine/ctm/hesperion/15 textures/optifine/ctm/hesperion/16 textures/optifine/ctm/hesperion/17 textures/optifine/ctm/hesperion/18 textures/optifine/ctm/hesperion/19 textures/optifine/ctm/hesperion/20 textures/optifine/ctm/hesperion/21 textures/optifine/ctm/hesperion/22 textures/optifine/ctm/hesperion/23 textures/optifine/ctm/hesperion/24 textures/optifine/ctm/hesperion/25 textures/optifine/ctm/hesperion/26 textures/optifine/ctm/hesperion/27 textures/optifine/ctm/hesperion/28 textures/optifine/ctm/hesperion/29 textures/optifine/ctm/hesperion/30 textures/optifine/ctm/hesperion/31 textures/optifine/ctm/hesperion/32 textures/optifine/ctm/hesperion/33 textures/optifine/ctm/hesperion/34 textures/optifine/ctm/hesperion/35
matchBlocks=erydon:hesperion_block_silvertrim \
  erydon:hesperion_trim_silver_stairs \
  erydon:hesperion_trim_silver_stairs_shallow_bottom \
  erydon:hesperion_trim_silver_stairs_shallow_top \
  erydon:hesperion_trim_silver_layer_multiface \
  erydon:hesperion_trim_silver_slope \
  erydon:hesperion_trim_silver_slope_shallow_lower \
  erydon:hesperion_trim_silver_slope_shallow_upper \
  erydon:hesperion_trim_silver_slope_steep_lower \
  erydon:hesperion_trim_silver_slope_steep_upper \
  erydon:hesperion_trim_silver_slope_vertical \
  erydon:hesperion_trim_silver_slope_vertical_shallow_broad \
  erydon:hesperion_trim_silver_slope_vertical_shallow_narrow \
  erydon:hesperion_block_bronzetrim \
  erydon:hesperion_trim_bronze_stairs \
  erydon:hesperion_trim_bronze_stairs_shallow_bottom \
  erydon:hesperion_trim_bronze_stairs_shallow_top \
  erydon:hesperion_trim_bronze_layer_multiface \
  erydon:hesperion_trim_bronze_slope \
  erydon:hesperion_trim_bronze_slope_shallow_lower \
  erydon:hesperion_trim_bronze_slope_shallow_upper \
  erydon:hesperion_trim_bronze_slope_steep_lower \
  erydon:hesperion_trim_bronze_slope_steep_upper \
  erydon:hesperion_trim_bronze_slope_vertical \
  erydon:hesperion_trim_bronze_slope_vertical_shallow_broad \
  erydon:hesperion_trim_bronze_slope_vertical_shallow_narrow \
  erydon:hesperion_block_bronzequatrefoil \
  erydon:hesperion_quatrefoil_bronze_stairs \
  erydon:hesperion_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:hesperion_quatrefoil_bronze_stairs_shallow_top \
  erydon:hesperion_quatrefoil_bronze_layer_multiface \
  erydon:hesperion_quatrefoil_bronze_slope \
  erydon:hesperion_quatrefoil_bronze_slope_shallow_lower \
  erydon:hesperion_quatrefoil_bronze_slope_shallow_upper \
  erydon:hesperion_quatrefoil_bronze_slope_steep_lower \
  erydon:hesperion_quatrefoil_bronze_slope_steep_upper \
  erydon:hesperion_quatrefoil_bronze_slope_vertical \
  erydon:hesperion_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:hesperion_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:hesperion_block_silverquatrefoil \
  erydon:hesperion_quatrefoil_silver_stairs \
  erydon:hesperion_quatrefoil_silver_stairs_shallow_bottom \
  erydon:hesperion_quatrefoil_silver_stairs_shallow_top \
  erydon:hesperion_quatrefoil_silver_layer_multiface \
  erydon:hesperion_quatrefoil_silver_slope \
  erydon:hesperion_quatrefoil_silver_slope_shallow_lower \
  erydon:hesperion_quatrefoil_silver_slope_shallow_upper \
  erydon:hesperion_quatrefoil_silver_slope_steep_lower \
  erydon:hesperion_quatrefoil_silver_slope_steep_upper \
  erydon:hesperion_quatrefoil_silver_slope_vertical \
  erydon:hesperion_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:hesperion_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:hesperion_block_silverrose \
  erydon:hesperion_rosette_silver_stairs \
  erydon:hesperion_rosette_silver_stairs_shallow_bottom \
  erydon:hesperion_rosette_silver_stairs_shallow_top \
  erydon:hesperion_rosette_silver_layer_multiface \
  erydon:hesperion_rosette_silver_slope \
  erydon:hesperion_rosette_silver_slope_shallow_lower \
  erydon:hesperion_rosette_silver_slope_shallow_upper \
  erydon:hesperion_rosette_silver_slope_steep_lower \
  erydon:hesperion_rosette_silver_slope_steep_upper \
  erydon:hesperion_rosette_silver_slope_vertical \
  erydon:hesperion_rosette_silver_slope_vertical_shallow_broad \
  erydon:hesperion_rosette_silver_slope_vertical_shallow_narrow \
  erydon:hesperion_block_bronzerose \
  erydon:hesperion_rosette_bronze_stairs \
  erydon:hesperion_rosette_bronze_stairs_shallow_bottom \
  erydon:hesperion_rosette_bronze_stairs_shallow_top \
  erydon:hesperion_rosette_bronze_layer_multiface \
  erydon:hesperion_rosette_bronze_slope \
  erydon:hesperion_rosette_bronze_slope_shallow_lower \
  erydon:hesperion_rosette_bronze_slope_shallow_upper \
  erydon:hesperion_rosette_bronze_slope_steep_lower \
  erydon:hesperion_rosette_bronze_slope_steep_upper \
  erydon:hesperion_rosette_bronze_slope_vertical \
  erydon:hesperion_rosette_bronze_slope_vertical_shallow_broad \
  erydon:hesperion_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:hesperion_block_silverguilloche \
  erydon:hesperion_guilloche_silver_stairs \
  erydon:hesperion_guilloche_silver_stairs_shallow_bottom \
  erydon:hesperion_guilloche_silver_stairs_shallow_top \
  erydon:hesperion_guilloche_silver_layer_multiface \
  erydon:hesperion_guilloche_silver_slope \
  erydon:hesperion_guilloche_silver_slope_shallow_lower \
  erydon:hesperion_guilloche_silver_slope_shallow_upper \
  erydon:hesperion_guilloche_silver_slope_steep_lower \
  erydon:hesperion_guilloche_silver_slope_steep_upper \
  erydon:hesperion_guilloche_silver_slope_vertical \
  erydon:hesperion_guilloche_silver_slope_vertical_shallow_broad \
  erydon:hesperion_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:hesperion_block_bronzeguilloche \
  erydon:hesperion_guilloche_bronze_stairs \
  erydon:hesperion_guilloche_bronze_stairs_shallow_bottom \
  erydon:hesperion_guilloche_bronze_stairs_shallow_top \
  erydon:hesperion_guilloche_bronze_layer_multiface \
  erydon:hesperion_guilloche_bronze_slope \
  erydon:hesperion_guilloche_bronze_slope_shallow_lower \
  erydon:hesperion_guilloche_bronze_slope_shallow_upper \
  erydon:hesperion_guilloche_bronze_slope_steep_lower \
  erydon:hesperion_guilloche_bronze_slope_steep_upper \
  erydon:hesperion_guilloche_bronze_slope_vertical \
  erydon:hesperion_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:hesperion_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
