method=repeat

width=6

height=6

tiles=textures/optifine/ctm/calacattum/0 textures/optifine/ctm/calacattum/1 textures/optifine/ctm/calacattum/2 textures/optifine/ctm/calacattum/3 textures/optifine/ctm/calacattum/4 textures/optifine/ctm/calacattum/5 textures/optifine/ctm/calacattum/6 textures/optifine/ctm/calacattum/7 textures/optifine/ctm/calacattum/8 textures/optifine/ctm/calacattum/9 textures/optifine/ctm/calacattum/10 textures/optifine/ctm/calacattum/11 textures/optifine/ctm/calacattum/12 textures/optifine/ctm/calacattum/13 textures/optifine/ctm/calacattum/14 textures/optifine/ctm/calacattum/15 textures/optifine/ctm/calacattum/16 textures/optifine/ctm/calacattum/17 textures/optifine/ctm/calacattum/18 textures/optifine/ctm/calacattum/19 textures/optifine/ctm/calacattum/20 textures/optifine/ctm/calacattum/21 textures/optifine/ctm/calacattum/22 textures/optifine/ctm/calacattum/23 textures/optifine/ctm/calacattum/24 textures/optifine/ctm/calacattum/25 textures/optifine/ctm/calacattum/26 textures/optifine/ctm/calacattum/27 textures/optifine/ctm/calacattum/28 textures/optifine/ctm/calacattum/29 textures/optifine/ctm/calacattum/30 textures/optifine/ctm/calacattum/31 textures/optifine/ctm/calacattum/32 textures/optifine/ctm/calacattum/33 textures/optifine/ctm/calacattum/34 textures/optifine/ctm/calacattum/35

matchBlocks=erydon:calacattum_block \
  erydon:calacattum_stairs \
  erydon:calacattum_stairs_shallow_bottom \
  erydon:calacattum_stairs_shallow_top \
  erydon:calacattum_slab \
  erydon:calacattum_wall \
  erydon:calacattum_layer \
  erydon:calacattum_layer_multiface \
  erydon:calacattum_layer_vertical \
  erydon:calacattum_slope \
  erydon:calacattum_slope_shallow_upper \
  erydon:calacattum_slope_steep_lower \
  erydon:calacattum_slope_steep_upper \
  erydon:calacattum_slope_shallow_lower \
  erydon:calacattum_slope_vertical \
  erydon:calacattum_slope_vertical_shallow_narrow \
  erydon:calacattum_arch_romanesque \
  erydon:calacattum_slope_vertical_shallow_broad \
  erydon:calacattum_column_circular \
  erydon:calacattum_column_gothic \
  erydon:calacattum_column_square \
  erydon:calacattum_cornice_modern \
  erydon:calacattum_cornice_georgian \
  erydon:calacattum_cornice_guilloche \
  erydon:calacattum_cornice_gothic \
  erydon:calacattum_surround_georgian \
  erydon:calacattum_surround_guilloche \
  erydon:calacattum_surround_gothic_ornate \
  erydon:calacattum_surround_modern \
  erydon:calacattum_stairs_spiral_large \
  erydon:calacattum_light_modern \
  erydon:calacattum_chimney_circular \
  erydon:calacattum_vertical_slice \
  erydon:calacattum_horizontal_slice \
  erydon:calacattum_post \
  erydon:calacattum_wall_georgian \
  erydon:calacattum_alcove_georgian \
  erydon:calacattum_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
