method=repeat
width=6
height=6
tiles=textures/optifine/ctm/calacattum/0 textures/optifine/ctm/calacattum/1 textures/optifine/ctm/calacattum/2 textures/optifine/ctm/calacattum/3 textures/optifine/ctm/calacattum/4 textures/optifine/ctm/calacattum/5 textures/optifine/ctm/calacattum/6 textures/optifine/ctm/calacattum/7 textures/optifine/ctm/calacattum/8 textures/optifine/ctm/calacattum/9 textures/optifine/ctm/calacattum/10 textures/optifine/ctm/calacattum/11 textures/optifine/ctm/calacattum/12 textures/optifine/ctm/calacattum/13 textures/optifine/ctm/calacattum/14 textures/optifine/ctm/calacattum/15 textures/optifine/ctm/calacattum/16 textures/optifine/ctm/calacattum/17 textures/optifine/ctm/calacattum/18 textures/optifine/ctm/calacattum/19 textures/optifine/ctm/calacattum/20 textures/optifine/ctm/calacattum/21 textures/optifine/ctm/calacattum/22 textures/optifine/ctm/calacattum/23 textures/optifine/ctm/calacattum/24 textures/optifine/ctm/calacattum/25 textures/optifine/ctm/calacattum/26 textures/optifine/ctm/calacattum/27 textures/optifine/ctm/calacattum/28 textures/optifine/ctm/calacattum/29 textures/optifine/ctm/calacattum/30 textures/optifine/ctm/calacattum/31 textures/optifine/ctm/calacattum/32 textures/optifine/ctm/calacattum/33 textures/optifine/ctm/calacattum/34 textures/optifine/ctm/calacattum/35

matchBlocks=erydon:calacattum_ceiling_coffered_modern_black_small
matchTiles=erydon:block/calacattum_block

faces=all
connect=block
innerSeams=true
priority=10
