method=repeat

width=6

height=6

tiles=textures/optifine/ctm/gelastrum/0 textures/optifine/ctm/gelastrum/1 textures/optifine/ctm/gelastrum/2 textures/optifine/ctm/gelastrum/3 textures/optifine/ctm/gelastrum/4 textures/optifine/ctm/gelastrum/5 textures/optifine/ctm/gelastrum/6 textures/optifine/ctm/gelastrum/7 textures/optifine/ctm/gelastrum/8 textures/optifine/ctm/gelastrum/9 textures/optifine/ctm/gelastrum/10 textures/optifine/ctm/gelastrum/11 textures/optifine/ctm/gelastrum/12 textures/optifine/ctm/gelastrum/13 textures/optifine/ctm/gelastrum/14 textures/optifine/ctm/gelastrum/15 textures/optifine/ctm/gelastrum/16 textures/optifine/ctm/gelastrum/17 textures/optifine/ctm/gelastrum/18 textures/optifine/ctm/gelastrum/19 textures/optifine/ctm/gelastrum/20 textures/optifine/ctm/gelastrum/21 textures/optifine/ctm/gelastrum/22 textures/optifine/ctm/gelastrum/23 textures/optifine/ctm/gelastrum/24 textures/optifine/ctm/gelastrum/25 textures/optifine/ctm/gelastrum/26 textures/optifine/ctm/gelastrum/27 textures/optifine/ctm/gelastrum/28 textures/optifine/ctm/gelastrum/29 textures/optifine/ctm/gelastrum/30 textures/optifine/ctm/gelastrum/31 textures/optifine/ctm/gelastrum/32 textures/optifine/ctm/gelastrum/33 textures/optifine/ctm/gelastrum/34 textures/optifine/ctm/gelastrum/35

matchBlocks=erydon:gelastrum_block \
  erydon:gelastrum_stairs \
  erydon:gelastrum_stairs_shallow_bottom \
  erydon:gelastrum_stairs_shallow_top \
  erydon:gelastrum_slab \
  erydon:gelastrum_wall \
  erydon:gelastrum_layer \
  erydon:gelastrum_layer_multiface \
  erydon:gelastrum_layer_vertical \
  erydon:gelastrum_slope \
  erydon:gelastrum_slope_shallow_upper \
  erydon:gelastrum_slope_steep_lower \
  erydon:gelastrum_slope_steep_upper \
  erydon:gelastrum_slope_shallow_lower \
  erydon:gelastrum_slope_vertical \
  erydon:gelastrum_slope_vertical_shallow_narrow \
  erydon:gelastrum_arch_romanesque \
  erydon:gelastrum_slope_vertical_shallow_broad \
  erydon:gelastrum_column_circular \
  erydon:gelastrum_column_gothic \
  erydon:gelastrum_column_square \
  erydon:gelastrum_cornice_modern \
  erydon:gelastrum_cornice_georgian \
  erydon:gelastrum_cornice_guilloche \
  erydon:gelastrum_cornice_gothic \
  erydon:gelastrum_surround_georgian \
  erydon:gelastrum_surround_guilloche \
  erydon:gelastrum_surround_gothic_ornate \
  erydon:gelastrum_surround_modern \
  erydon:gelastrum_stairs_spiral_large \
  erydon:gelastrum_light_modern \
  erydon:gelastrum_chimney_circular \
  erydon:gelastrum_vertical_slice \
  erydon:gelastrum_horizontal_slice \
  erydon:gelastrum_post \
  erydon:gelastrum_wall_georgian \
  erydon:gelastrum_alcove_georgian \
  erydon:gelastrum_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
