method=repeat
width=6
height=6
tiles=textures/optifine/ctm/gelastrum/0 textures/optifine/ctm/gelastrum/1 textures/optifine/ctm/gelastrum/2 textures/optifine/ctm/gelastrum/3 textures/optifine/ctm/gelastrum/4 textures/optifine/ctm/gelastrum/5 textures/optifine/ctm/gelastrum/6 textures/optifine/ctm/gelastrum/7 textures/optifine/ctm/gelastrum/8 textures/optifine/ctm/gelastrum/9 textures/optifine/ctm/gelastrum/10 textures/optifine/ctm/gelastrum/11 textures/optifine/ctm/gelastrum/12 textures/optifine/ctm/gelastrum/13 textures/optifine/ctm/gelastrum/14 textures/optifine/ctm/gelastrum/15 textures/optifine/ctm/gelastrum/16 textures/optifine/ctm/gelastrum/17 textures/optifine/ctm/gelastrum/18 textures/optifine/ctm/gelastrum/19 textures/optifine/ctm/gelastrum/20 textures/optifine/ctm/gelastrum/21 textures/optifine/ctm/gelastrum/22 textures/optifine/ctm/gelastrum/23 textures/optifine/ctm/gelastrum/24 textures/optifine/ctm/gelastrum/25 textures/optifine/ctm/gelastrum/26 textures/optifine/ctm/gelastrum/27 textures/optifine/ctm/gelastrum/28 textures/optifine/ctm/gelastrum/29 textures/optifine/ctm/gelastrum/30 textures/optifine/ctm/gelastrum/31 textures/optifine/ctm/gelastrum/32 textures/optifine/ctm/gelastrum/33 textures/optifine/ctm/gelastrum/34 textures/optifine/ctm/gelastrum/35
matchBlocks=erydon:gelastrum_block_silvertrim \
  erydon:gelastrum_block_bronzetrim \
  erydon:gelastrum_block_bronzequatrefoil \
  erydon:gelastrum_block_silverquatrefoil \
  erydon:gelastrum_block_silverrose \
  erydon:gelastrum_block_bronzerose \
  erydon:gelastrum_block_silverguilloche \
  erydon:gelastrum_block_bronzeguilloche
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
