method=repeat

width=6

height=6

tiles=textures/optifine/ctm/portorium_rusticated/0 textures/optifine/ctm/portorium_rusticated/1 textures/optifine/ctm/portorium_rusticated/2 textures/optifine/ctm/portorium_rusticated/3 textures/optifine/ctm/portorium_rusticated/4 textures/optifine/ctm/portorium_rusticated/5 textures/optifine/ctm/portorium_rusticated/6 textures/optifine/ctm/portorium_rusticated/7 textures/optifine/ctm/portorium_rusticated/8 textures/optifine/ctm/portorium_rusticated/9 textures/optifine/ctm/portorium_rusticated/10 textures/optifine/ctm/portorium_rusticated/11 textures/optifine/ctm/portorium_rusticated/12 textures/optifine/ctm/portorium_rusticated/13 textures/optifine/ctm/portorium_rusticated/14 textures/optifine/ctm/portorium_rusticated/15 textures/optifine/ctm/portorium_rusticated/16 textures/optifine/ctm/portorium_rusticated/17 textures/optifine/ctm/portorium_rusticated/18 textures/optifine/ctm/portorium_rusticated/19 textures/optifine/ctm/portorium_rusticated/20 textures/optifine/ctm/portorium_rusticated/21 textures/optifine/ctm/portorium_rusticated/22 textures/optifine/ctm/portorium_rusticated/23 textures/optifine/ctm/portorium_rusticated/24 textures/optifine/ctm/portorium_rusticated/25 textures/optifine/ctm/portorium_rusticated/26 textures/optifine/ctm/portorium_rusticated/27 textures/optifine/ctm/portorium_rusticated/28 textures/optifine/ctm/portorium_rusticated/29 textures/optifine/ctm/portorium_rusticated/30 textures/optifine/ctm/portorium_rusticated/31 textures/optifine/ctm/portorium_rusticated/32 textures/optifine/ctm/portorium_rusticated/33 textures/optifine/ctm/portorium_rusticated/34 textures/optifine/ctm/portorium_rusticated/35

matchBlocks=erydon:portorium_rusticated_block \
  erydon:portorium_rusticated_slab \
  erydon:portorium_rusticated_layer \
  erydon:portorium_rusticated_layer_vertical \
  erydon:portorium_rusticated_slope \
  erydon:portorium_rusticated_slope_shallow_lower \
  erydon:portorium_rusticated_slope_shallow_upper \
  erydon:portorium_rusticated_slope_steep_lower \
  erydon:portorium_rusticated_slope_steep_upper \
  erydon:portorium_rusticated_slope_vertical \
  erydon:portorium_rusticated_slope_vertical_shallow_narrow \
  erydon:portorium_rusticated_slope_vertical_shallow_broad \
  erydon:portorium_rusticated_arch_romanesque \
  erydon:portorium_rusticated_vertical_slice \
  erydon:portorium_rusticated_horizontal_slice \
  erydon:portorium_rusticated_post \
  erydon:portorium_rusticated_stairs \
  erydon:portorium_rusticated_wall \
  erydon:portorium_rusticated_alcove_georgian \
  erydon:portorium_rusticated_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
