method=repeat

width=6

height=6

tiles=textures/optifine/ctm/aterzon/0 textures/optifine/ctm/aterzon/1 textures/optifine/ctm/aterzon/2 textures/optifine/ctm/aterzon/3 textures/optifine/ctm/aterzon/4 textures/optifine/ctm/aterzon/5 textures/optifine/ctm/aterzon/6 textures/optifine/ctm/aterzon/7 textures/optifine/ctm/aterzon/8 textures/optifine/ctm/aterzon/9 textures/optifine/ctm/aterzon/10 textures/optifine/ctm/aterzon/11 textures/optifine/ctm/aterzon/12 textures/optifine/ctm/aterzon/13 textures/optifine/ctm/aterzon/14 textures/optifine/ctm/aterzon/15 textures/optifine/ctm/aterzon/16 textures/optifine/ctm/aterzon/17 textures/optifine/ctm/aterzon/18 textures/optifine/ctm/aterzon/19 textures/optifine/ctm/aterzon/20 textures/optifine/ctm/aterzon/21 textures/optifine/ctm/aterzon/22 textures/optifine/ctm/aterzon/23 textures/optifine/ctm/aterzon/24 textures/optifine/ctm/aterzon/25 textures/optifine/ctm/aterzon/26 textures/optifine/ctm/aterzon/27 textures/optifine/ctm/aterzon/28 textures/optifine/ctm/aterzon/29 textures/optifine/ctm/aterzon/30 textures/optifine/ctm/aterzon/31 textures/optifine/ctm/aterzon/32 textures/optifine/ctm/aterzon/33 textures/optifine/ctm/aterzon/34 textures/optifine/ctm/aterzon/35

matchBlocks=erydon:aterzon_block \
  erydon:aterzon_stairs \
  erydon:aterzon_stairs_shallow_bottom \
  erydon:aterzon_stairs_shallow_top \
  erydon:aterzon_slab \
  erydon:aterzon_wall \
  erydon:aterzon_layer \
  erydon:aterzon_layer_multiface \
  erydon:aterzon_layer_vertical \
  erydon:aterzon_slope \
  erydon:aterzon_slope_shallow_upper \
  erydon:aterzon_slope_steep_lower \
  erydon:aterzon_slope_steep_upper \
  erydon:aterzon_slope_shallow_lower \
  erydon:aterzon_slope_vertical \
  erydon:aterzon_slope_vertical_shallow_narrow \
  erydon:aterzon_arch_romanesque \
  erydon:aterzon_slope_vertical_shallow_broad \
  erydon:aterzon_column_circular \
  erydon:aterzon_column_gothic \
  erydon:aterzon_column_square \
  erydon:aterzon_cornice_modern \
  erydon:aterzon_cornice_georgian \
  erydon:aterzon_cornice_guilloche \
  erydon:aterzon_cornice_gothic \
  erydon:aterzon_surround_georgian \
  erydon:aterzon_surround_guilloche \
  erydon:aterzon_surround_gothic_ornate \
  erydon:aterzon_surround_modern \
  erydon:aterzon_stairs_spiral_large \
  erydon:aterzon_light_modern \
  erydon:aterzon_chimney_circular \
  erydon:aterzon_vertical_slice \
  erydon:aterzon_horizontal_slice \
  erydon:aterzon_post \
  erydon:aterzon_wall_georgian \
  erydon:aterzon_alcove_georgian \
  erydon:aterzon_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
