method=repeat
width=6
height=6
tiles=textures/optifine/ctm/aterzon/0 textures/optifine/ctm/aterzon/1 textures/optifine/ctm/aterzon/2 textures/optifine/ctm/aterzon/3 textures/optifine/ctm/aterzon/4 textures/optifine/ctm/aterzon/5 textures/optifine/ctm/aterzon/6 textures/optifine/ctm/aterzon/7 textures/optifine/ctm/aterzon/8 textures/optifine/ctm/aterzon/9 textures/optifine/ctm/aterzon/10 textures/optifine/ctm/aterzon/11 textures/optifine/ctm/aterzon/12 textures/optifine/ctm/aterzon/13 textures/optifine/ctm/aterzon/14 textures/optifine/ctm/aterzon/15 textures/optifine/ctm/aterzon/16 textures/optifine/ctm/aterzon/17 textures/optifine/ctm/aterzon/18 textures/optifine/ctm/aterzon/19 textures/optifine/ctm/aterzon/20 textures/optifine/ctm/aterzon/21 textures/optifine/ctm/aterzon/22 textures/optifine/ctm/aterzon/23 textures/optifine/ctm/aterzon/24 textures/optifine/ctm/aterzon/25 textures/optifine/ctm/aterzon/26 textures/optifine/ctm/aterzon/27 textures/optifine/ctm/aterzon/28 textures/optifine/ctm/aterzon/29 textures/optifine/ctm/aterzon/30 textures/optifine/ctm/aterzon/31 textures/optifine/ctm/aterzon/32 textures/optifine/ctm/aterzon/33 textures/optifine/ctm/aterzon/34 textures/optifine/ctm/aterzon/35

matchBlocks=erydon:aterzon_ceiling_coffered_modern_white_small
matchTiles=erydon:block/aterzon_block

faces=all
connect=block
innerSeams=true
priority=10
