method=repeat

width=6

height=6

tiles=textures/optifine/ctm/nerium/0 textures/optifine/ctm/nerium/1 textures/optifine/ctm/nerium/2 textures/optifine/ctm/nerium/3 textures/optifine/ctm/nerium/4 textures/optifine/ctm/nerium/5 textures/optifine/ctm/nerium/6 textures/optifine/ctm/nerium/7 textures/optifine/ctm/nerium/8 textures/optifine/ctm/nerium/9 textures/optifine/ctm/nerium/10 textures/optifine/ctm/nerium/11 textures/optifine/ctm/nerium/12 textures/optifine/ctm/nerium/13 textures/optifine/ctm/nerium/14 textures/optifine/ctm/nerium/15 textures/optifine/ctm/nerium/16 textures/optifine/ctm/nerium/17 textures/optifine/ctm/nerium/18 textures/optifine/ctm/nerium/19 textures/optifine/ctm/nerium/20 textures/optifine/ctm/nerium/21 textures/optifine/ctm/nerium/22 textures/optifine/ctm/nerium/23 textures/optifine/ctm/nerium/24 textures/optifine/ctm/nerium/25 textures/optifine/ctm/nerium/26 textures/optifine/ctm/nerium/27 textures/optifine/ctm/nerium/28 textures/optifine/ctm/nerium/29 textures/optifine/ctm/nerium/30 textures/optifine/ctm/nerium/31 textures/optifine/ctm/nerium/32 textures/optifine/ctm/nerium/33 textures/optifine/ctm/nerium/34 textures/optifine/ctm/nerium/35

matchBlocks=erydon:nerium_block \
  erydon:nerium_stairs \
  erydon:nerium_stairs_shallow_bottom \
  erydon:nerium_stairs_shallow_top \
  erydon:nerium_slab \
  erydon:nerium_wall \
  erydon:nerium_layer \
  erydon:nerium_layer_multiface \
  erydon:nerium_layer_vertical \
  erydon:nerium_slope \
  erydon:nerium_slope_shallow_upper \
  erydon:nerium_slope_steep_lower \
  erydon:nerium_slope_steep_upper \
  erydon:nerium_slope_shallow_lower \
  erydon:nerium_slope_vertical \
  erydon:nerium_slope_vertical_shallow_narrow \
  erydon:nerium_arch_romanesque \
  erydon:nerium_slope_vertical_shallow_broad \
  erydon:nerium_column_circular \
  erydon:nerium_column_gothic \
  erydon:nerium_column_square \
  erydon:nerium_cornice_modern \
  erydon:nerium_cornice_georgian \
  erydon:nerium_cornice_guilloche \
  erydon:nerium_cornice_gothic \
  erydon:nerium_surround_georgian \
  erydon:nerium_surround_guilloche \
  erydon:nerium_surround_gothic_ornate \
  erydon:nerium_surround_modern \
  erydon:nerium_stairs_spiral_large \
  erydon:nerium_light_modern \
  erydon:nerium_chimney_circular \
  erydon:nerium_vertical_slice \
  erydon:nerium_horizontal_slice \
  erydon:nerium_post \
  erydon:nerium_wall_georgian \
  erydon:nerium_alcove_georgian \
  erydon:nerium_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
