method=repeat
width=6
height=6
tiles=textures/optifine/ctm/nerium/0 textures/optifine/ctm/nerium/1 textures/optifine/ctm/nerium/2 textures/optifine/ctm/nerium/3 textures/optifine/ctm/nerium/4 textures/optifine/ctm/nerium/5 textures/optifine/ctm/nerium/6 textures/optifine/ctm/nerium/7 textures/optifine/ctm/nerium/8 textures/optifine/ctm/nerium/9 textures/optifine/ctm/nerium/10 textures/optifine/ctm/nerium/11 textures/optifine/ctm/nerium/12 textures/optifine/ctm/nerium/13 textures/optifine/ctm/nerium/14 textures/optifine/ctm/nerium/15 textures/optifine/ctm/nerium/16 textures/optifine/ctm/nerium/17 textures/optifine/ctm/nerium/18 textures/optifine/ctm/nerium/19 textures/optifine/ctm/nerium/20 textures/optifine/ctm/nerium/21 textures/optifine/ctm/nerium/22 textures/optifine/ctm/nerium/23 textures/optifine/ctm/nerium/24 textures/optifine/ctm/nerium/25 textures/optifine/ctm/nerium/26 textures/optifine/ctm/nerium/27 textures/optifine/ctm/nerium/28 textures/optifine/ctm/nerium/29 textures/optifine/ctm/nerium/30 textures/optifine/ctm/nerium/31 textures/optifine/ctm/nerium/32 textures/optifine/ctm/nerium/33 textures/optifine/ctm/nerium/34 textures/optifine/ctm/nerium/35

matchBlocks=erydon:nerium_light_wall
matchTiles=erydon:block/nerium_block

faces=all
connect=block
innerSeams=true
priority=10
