method=repeat
width=6
height=6
tiles=textures/optifine/ctm/nerium/0 textures/optifine/ctm/nerium/1 textures/optifine/ctm/nerium/2 textures/optifine/ctm/nerium/3 textures/optifine/ctm/nerium/4 textures/optifine/ctm/nerium/5 textures/optifine/ctm/nerium/6 textures/optifine/ctm/nerium/7 textures/optifine/ctm/nerium/8 textures/optifine/ctm/nerium/9 textures/optifine/ctm/nerium/10 textures/optifine/ctm/nerium/11 textures/optifine/ctm/nerium/12 textures/optifine/ctm/nerium/13 textures/optifine/ctm/nerium/14 textures/optifine/ctm/nerium/15 textures/optifine/ctm/nerium/16 textures/optifine/ctm/nerium/17 textures/optifine/ctm/nerium/18 textures/optifine/ctm/nerium/19 textures/optifine/ctm/nerium/20 textures/optifine/ctm/nerium/21 textures/optifine/ctm/nerium/22 textures/optifine/ctm/nerium/23 textures/optifine/ctm/nerium/24 textures/optifine/ctm/nerium/25 textures/optifine/ctm/nerium/26 textures/optifine/ctm/nerium/27 textures/optifine/ctm/nerium/28 textures/optifine/ctm/nerium/29 textures/optifine/ctm/nerium/30 textures/optifine/ctm/nerium/31 textures/optifine/ctm/nerium/32 textures/optifine/ctm/nerium/33 textures/optifine/ctm/nerium/34 textures/optifine/ctm/nerium/35
matchBlocks=erydon:nerium_block_silvertrim \
  erydon:nerium_trim_silver_stairs \
  erydon:nerium_trim_silver_stairs_shallow_bottom \
  erydon:nerium_trim_silver_stairs_shallow_top \
  erydon:nerium_trim_silver_layer_multiface \
  erydon:nerium_trim_silver_slope \
  erydon:nerium_trim_silver_slope_shallow_lower \
  erydon:nerium_trim_silver_slope_shallow_upper \
  erydon:nerium_trim_silver_slope_steep_lower \
  erydon:nerium_trim_silver_slope_steep_upper \
  erydon:nerium_trim_silver_slope_vertical \
  erydon:nerium_trim_silver_slope_vertical_shallow_broad \
  erydon:nerium_trim_silver_slope_vertical_shallow_narrow \
  erydon:nerium_block_bronzetrim \
  erydon:nerium_trim_bronze_stairs \
  erydon:nerium_trim_bronze_stairs_shallow_bottom \
  erydon:nerium_trim_bronze_stairs_shallow_top \
  erydon:nerium_trim_bronze_layer_multiface \
  erydon:nerium_trim_bronze_slope \
  erydon:nerium_trim_bronze_slope_shallow_lower \
  erydon:nerium_trim_bronze_slope_shallow_upper \
  erydon:nerium_trim_bronze_slope_steep_lower \
  erydon:nerium_trim_bronze_slope_steep_upper \
  erydon:nerium_trim_bronze_slope_vertical \
  erydon:nerium_trim_bronze_slope_vertical_shallow_broad \
  erydon:nerium_trim_bronze_slope_vertical_shallow_narrow \
  erydon:nerium_block_bronzequatrefoil \
  erydon:nerium_quatrefoil_bronze_stairs \
  erydon:nerium_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:nerium_quatrefoil_bronze_stairs_shallow_top \
  erydon:nerium_quatrefoil_bronze_layer_multiface \
  erydon:nerium_quatrefoil_bronze_slope \
  erydon:nerium_quatrefoil_bronze_slope_shallow_lower \
  erydon:nerium_quatrefoil_bronze_slope_shallow_upper \
  erydon:nerium_quatrefoil_bronze_slope_steep_lower \
  erydon:nerium_quatrefoil_bronze_slope_steep_upper \
  erydon:nerium_quatrefoil_bronze_slope_vertical \
  erydon:nerium_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:nerium_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:nerium_block_silverquatrefoil \
  erydon:nerium_quatrefoil_silver_stairs \
  erydon:nerium_quatrefoil_silver_stairs_shallow_bottom \
  erydon:nerium_quatrefoil_silver_stairs_shallow_top \
  erydon:nerium_quatrefoil_silver_layer_multiface \
  erydon:nerium_quatrefoil_silver_slope \
  erydon:nerium_quatrefoil_silver_slope_shallow_lower \
  erydon:nerium_quatrefoil_silver_slope_shallow_upper \
  erydon:nerium_quatrefoil_silver_slope_steep_lower \
  erydon:nerium_quatrefoil_silver_slope_steep_upper \
  erydon:nerium_quatrefoil_silver_slope_vertical \
  erydon:nerium_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:nerium_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:nerium_block_silverrose \
  erydon:nerium_rosette_silver_stairs \
  erydon:nerium_rosette_silver_stairs_shallow_bottom \
  erydon:nerium_rosette_silver_stairs_shallow_top \
  erydon:nerium_rosette_silver_layer_multiface \
  erydon:nerium_rosette_silver_slope \
  erydon:nerium_rosette_silver_slope_shallow_lower \
  erydon:nerium_rosette_silver_slope_shallow_upper \
  erydon:nerium_rosette_silver_slope_steep_lower \
  erydon:nerium_rosette_silver_slope_steep_upper \
  erydon:nerium_rosette_silver_slope_vertical \
  erydon:nerium_rosette_silver_slope_vertical_shallow_broad \
  erydon:nerium_rosette_silver_slope_vertical_shallow_narrow \
  erydon:nerium_block_bronzerose \
  erydon:nerium_rosette_bronze_stairs \
  erydon:nerium_rosette_bronze_stairs_shallow_bottom \
  erydon:nerium_rosette_bronze_stairs_shallow_top \
  erydon:nerium_rosette_bronze_layer_multiface \
  erydon:nerium_rosette_bronze_slope \
  erydon:nerium_rosette_bronze_slope_shallow_lower \
  erydon:nerium_rosette_bronze_slope_shallow_upper \
  erydon:nerium_rosette_bronze_slope_steep_lower \
  erydon:nerium_rosette_bronze_slope_steep_upper \
  erydon:nerium_rosette_bronze_slope_vertical \
  erydon:nerium_rosette_bronze_slope_vertical_shallow_broad \
  erydon:nerium_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:nerium_block_silverguilloche \
  erydon:nerium_guilloche_silver_stairs \
  erydon:nerium_guilloche_silver_stairs_shallow_bottom \
  erydon:nerium_guilloche_silver_stairs_shallow_top \
  erydon:nerium_guilloche_silver_layer_multiface \
  erydon:nerium_guilloche_silver_slope \
  erydon:nerium_guilloche_silver_slope_shallow_lower \
  erydon:nerium_guilloche_silver_slope_shallow_upper \
  erydon:nerium_guilloche_silver_slope_steep_lower \
  erydon:nerium_guilloche_silver_slope_steep_upper \
  erydon:nerium_guilloche_silver_slope_vertical \
  erydon:nerium_guilloche_silver_slope_vertical_shallow_broad \
  erydon:nerium_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:nerium_block_bronzeguilloche \
  erydon:nerium_guilloche_bronze_stairs \
  erydon:nerium_guilloche_bronze_stairs_shallow_bottom \
  erydon:nerium_guilloche_bronze_stairs_shallow_top \
  erydon:nerium_guilloche_bronze_layer_multiface \
  erydon:nerium_guilloche_bronze_slope \
  erydon:nerium_guilloche_bronze_slope_shallow_lower \
  erydon:nerium_guilloche_bronze_slope_shallow_upper \
  erydon:nerium_guilloche_bronze_slope_steep_lower \
  erydon:nerium_guilloche_bronze_slope_steep_upper \
  erydon:nerium_guilloche_bronze_slope_vertical \
  erydon:nerium_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:nerium_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
