method=repeat

width=6

height=6

tiles=textures/optifine/ctm/rosinium_herringbone_bronze/0 textures/optifine/ctm/rosinium_herringbone_bronze/1 textures/optifine/ctm/rosinium_herringbone_bronze/2 textures/optifine/ctm/rosinium_herringbone_bronze/3 textures/optifine/ctm/rosinium_herringbone_bronze/4 textures/optifine/ctm/rosinium_herringbone_bronze/5 textures/optifine/ctm/rosinium_herringbone_bronze/6 textures/optifine/ctm/rosinium_herringbone_bronze/7 textures/optifine/ctm/rosinium_herringbone_bronze/8 textures/optifine/ctm/rosinium_herringbone_bronze/9 textures/optifine/ctm/rosinium_herringbone_bronze/10 textures/optifine/ctm/rosinium_herringbone_bronze/11 textures/optifine/ctm/rosinium_herringbone_bronze/12 textures/optifine/ctm/rosinium_herringbone_bronze/13 textures/optifine/ctm/rosinium_herringbone_bronze/14 textures/optifine/ctm/rosinium_herringbone_bronze/15 textures/optifine/ctm/rosinium_herringbone_bronze/16 textures/optifine/ctm/rosinium_herringbone_bronze/17 textures/optifine/ctm/rosinium_herringbone_bronze/18 textures/optifine/ctm/rosinium_herringbone_bronze/19 textures/optifine/ctm/rosinium_herringbone_bronze/20 textures/optifine/ctm/rosinium_herringbone_bronze/21 textures/optifine/ctm/rosinium_herringbone_bronze/22 textures/optifine/ctm/rosinium_herringbone_bronze/23 textures/optifine/ctm/rosinium_herringbone_bronze/24 textures/optifine/ctm/rosinium_herringbone_bronze/25 textures/optifine/ctm/rosinium_herringbone_bronze/26 textures/optifine/ctm/rosinium_herringbone_bronze/27 textures/optifine/ctm/rosinium_herringbone_bronze/28 textures/optifine/ctm/rosinium_herringbone_bronze/29 textures/optifine/ctm/rosinium_herringbone_bronze/30 textures/optifine/ctm/rosinium_herringbone_bronze/31 textures/optifine/ctm/rosinium_herringbone_bronze/32 textures/optifine/ctm/rosinium_herringbone_bronze/33 textures/optifine/ctm/rosinium_herringbone_bronze/34 textures/optifine/ctm/rosinium_herringbone_bronze/35

matchBlocks=erydon:rosinium_herringbone_bronze_block \
  erydon:rosinium_herringbone_bronze_slab \
  erydon:rosinium_herringbone_bronze_wall \
  erydon:rosinium_herringbone_bronze_layer \
  erydon:rosinium_herringbone_bronze_layer_multiface \
  erydon:rosinium_herringbone_bronze_layer_vertical \
  erydon:rosinium_herringbone_bronze_slope \
  erydon:rosinium_herringbone_bronze_slope_shallow_upper \
  erydon:rosinium_herringbone_bronze_slope_steep_lower \
  erydon:rosinium_herringbone_bronze_slope_steep_upper \
  erydon:rosinium_herringbone_bronze_slope_shallow_lower \
  erydon:rosinium_herringbone_bronze_slope_vertical \
  erydon:rosinium_herringbone_bronze_slope_vertical_shallow_narrow \
  erydon:rosinium_herringbone_bronze_slope_vertical_shallow_broad \
  erydon:rosinium_herringbone_bronze_vertical_slice \
  erydon:rosinium_herringbone_bronze_horizontal_slice \
  erydon:rosinium_herringbone_bronze_post \
  erydon:rosinium_herringbone_bronze_wall_georgian
faces=top bottom north south east west

connect=block

innerSeams=true

priority=10
