method=repeat
width=6
height=6
tiles=textures/optifine/ctm/kylorion/0 textures/optifine/ctm/kylorion/1 textures/optifine/ctm/kylorion/2 textures/optifine/ctm/kylorion/3 textures/optifine/ctm/kylorion/4 textures/optifine/ctm/kylorion/5 textures/optifine/ctm/kylorion/6 textures/optifine/ctm/kylorion/7 textures/optifine/ctm/kylorion/8 textures/optifine/ctm/kylorion/9 textures/optifine/ctm/kylorion/10 textures/optifine/ctm/kylorion/11 textures/optifine/ctm/kylorion/12 textures/optifine/ctm/kylorion/13 textures/optifine/ctm/kylorion/14 textures/optifine/ctm/kylorion/15 textures/optifine/ctm/kylorion/16 textures/optifine/ctm/kylorion/17 textures/optifine/ctm/kylorion/18 textures/optifine/ctm/kylorion/19 textures/optifine/ctm/kylorion/20 textures/optifine/ctm/kylorion/21 textures/optifine/ctm/kylorion/22 textures/optifine/ctm/kylorion/23 textures/optifine/ctm/kylorion/24 textures/optifine/ctm/kylorion/25 textures/optifine/ctm/kylorion/26 textures/optifine/ctm/kylorion/27 textures/optifine/ctm/kylorion/28 textures/optifine/ctm/kylorion/29 textures/optifine/ctm/kylorion/30 textures/optifine/ctm/kylorion/31 textures/optifine/ctm/kylorion/32 textures/optifine/ctm/kylorion/33 textures/optifine/ctm/kylorion/34 textures/optifine/ctm/kylorion/35

matchBlocks=erydon:kylorion_ceiling_coffered_modern_black_small
matchTiles=erydon:block/kylorion_block

faces=all
connect=block
innerSeams=true
priority=10
