method=repeat
width=6
height=6
tiles=textures/optifine/ctm/noxoplis/0 textures/optifine/ctm/noxoplis/1 textures/optifine/ctm/noxoplis/2 textures/optifine/ctm/noxoplis/3 textures/optifine/ctm/noxoplis/4 textures/optifine/ctm/noxoplis/5 textures/optifine/ctm/noxoplis/6 textures/optifine/ctm/noxoplis/7 textures/optifine/ctm/noxoplis/8 textures/optifine/ctm/noxoplis/9 textures/optifine/ctm/noxoplis/10 textures/optifine/ctm/noxoplis/11 textures/optifine/ctm/noxoplis/12 textures/optifine/ctm/noxoplis/13 textures/optifine/ctm/noxoplis/14 textures/optifine/ctm/noxoplis/15 textures/optifine/ctm/noxoplis/16 textures/optifine/ctm/noxoplis/17 textures/optifine/ctm/noxoplis/18 textures/optifine/ctm/noxoplis/19 textures/optifine/ctm/noxoplis/20 textures/optifine/ctm/noxoplis/21 textures/optifine/ctm/noxoplis/22 textures/optifine/ctm/noxoplis/23 textures/optifine/ctm/noxoplis/24 textures/optifine/ctm/noxoplis/25 textures/optifine/ctm/noxoplis/26 textures/optifine/ctm/noxoplis/27 textures/optifine/ctm/noxoplis/28 textures/optifine/ctm/noxoplis/29 textures/optifine/ctm/noxoplis/30 textures/optifine/ctm/noxoplis/31 textures/optifine/ctm/noxoplis/32 textures/optifine/ctm/noxoplis/33 textures/optifine/ctm/noxoplis/34 textures/optifine/ctm/noxoplis/35

matchBlocks=erydon:noxoplis_ceiling_coffered_modern_white_small
matchTiles=erydon:block/noxoplis_block

faces=all
connect=block
innerSeams=true
priority=10
