method=repeat
width=6
height=6
tiles=textures/optifine/ctm/borealis/0 textures/optifine/ctm/borealis/1 textures/optifine/ctm/borealis/2 textures/optifine/ctm/borealis/3 textures/optifine/ctm/borealis/4 textures/optifine/ctm/borealis/5 textures/optifine/ctm/borealis/6 textures/optifine/ctm/borealis/7 textures/optifine/ctm/borealis/8 textures/optifine/ctm/borealis/9 textures/optifine/ctm/borealis/10 textures/optifine/ctm/borealis/11 textures/optifine/ctm/borealis/12 textures/optifine/ctm/borealis/13 textures/optifine/ctm/borealis/14 textures/optifine/ctm/borealis/15 textures/optifine/ctm/borealis/16 textures/optifine/ctm/borealis/17 textures/optifine/ctm/borealis/18 textures/optifine/ctm/borealis/19 textures/optifine/ctm/borealis/20 textures/optifine/ctm/borealis/21 textures/optifine/ctm/borealis/22 textures/optifine/ctm/borealis/23 textures/optifine/ctm/borealis/24 textures/optifine/ctm/borealis/25 textures/optifine/ctm/borealis/26 textures/optifine/ctm/borealis/27 textures/optifine/ctm/borealis/28 textures/optifine/ctm/borealis/29 textures/optifine/ctm/borealis/30 textures/optifine/ctm/borealis/31 textures/optifine/ctm/borealis/32 textures/optifine/ctm/borealis/33 textures/optifine/ctm/borealis/34 textures/optifine/ctm/borealis/35

matchBlocks=erydon:borealis_ceiling_coffered_georgian_black_small
matchTiles=erydon:block/borealis_block

faces=all
connect=block
innerSeams=true
priority=10
