method=repeat

width=6

height=6

tiles=textures/optifine/ctm/borealis/0 textures/optifine/ctm/borealis/1 textures/optifine/ctm/borealis/2 textures/optifine/ctm/borealis/3 textures/optifine/ctm/borealis/4 textures/optifine/ctm/borealis/5 textures/optifine/ctm/borealis/6 textures/optifine/ctm/borealis/7 textures/optifine/ctm/borealis/8 textures/optifine/ctm/borealis/9 textures/optifine/ctm/borealis/10 textures/optifine/ctm/borealis/11 textures/optifine/ctm/borealis/12 textures/optifine/ctm/borealis/13 textures/optifine/ctm/borealis/14 textures/optifine/ctm/borealis/15 textures/optifine/ctm/borealis/16 textures/optifine/ctm/borealis/17 textures/optifine/ctm/borealis/18 textures/optifine/ctm/borealis/19 textures/optifine/ctm/borealis/20 textures/optifine/ctm/borealis/21 textures/optifine/ctm/borealis/22 textures/optifine/ctm/borealis/23 textures/optifine/ctm/borealis/24 textures/optifine/ctm/borealis/25 textures/optifine/ctm/borealis/26 textures/optifine/ctm/borealis/27 textures/optifine/ctm/borealis/28 textures/optifine/ctm/borealis/29 textures/optifine/ctm/borealis/30 textures/optifine/ctm/borealis/31 textures/optifine/ctm/borealis/32 textures/optifine/ctm/borealis/33 textures/optifine/ctm/borealis/34 textures/optifine/ctm/borealis/35

matchBlocks=erydon:borealis_block \
  erydon:borealis_stairs \
  erydon:borealis_stairs_shallow_bottom \
  erydon:borealis_stairs_shallow_top \
  erydon:borealis_slab \
  erydon:borealis_wall \
  erydon:borealis_layer \
  erydon:borealis_layer_multiface \
  erydon:borealis_layer_vertical \
  erydon:borealis_slope \
  erydon:borealis_slope_shallow_upper \
  erydon:borealis_slope_steep_lower \
  erydon:borealis_slope_steep_upper \
  erydon:borealis_slope_shallow_lower \
  erydon:borealis_slope_vertical \
  erydon:borealis_slope_vertical_shallow_narrow \
  erydon:borealis_arch_romanesque \
  erydon:borealis_slope_vertical_shallow_broad \
  erydon:borealis_column_circular \
  erydon:borealis_column_gothic \
  erydon:borealis_column_square \
  erydon:borealis_cornice_modern \
  erydon:borealis_cornice_georgian \
  erydon:borealis_cornice_guilloche \
  erydon:borealis_cornice_gothic \
  erydon:borealis_surround_georgian \
  erydon:borealis_surround_guilloche \
  erydon:borealis_surround_gothic_ornate \
  erydon:borealis_surround_modern \
  erydon:borealis_stairs_spiral_large \
  erydon:borealis_light_modern \
  erydon:borealis_chimney_circular \
  erydon:borealis_vertical_slice \
  erydon:borealis_horizontal_slice \
  erydon:borealis_post \
  erydon:borealis_wall_georgian \
  erydon:borealis_alcove_georgian \
  erydon:borealis_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
