method=repeat
width=6
height=6
tiles=textures/optifine/ctm/borealis/0 textures/optifine/ctm/borealis/1 textures/optifine/ctm/borealis/2 textures/optifine/ctm/borealis/3 textures/optifine/ctm/borealis/4 textures/optifine/ctm/borealis/5 textures/optifine/ctm/borealis/6 textures/optifine/ctm/borealis/7 textures/optifine/ctm/borealis/8 textures/optifine/ctm/borealis/9 textures/optifine/ctm/borealis/10 textures/optifine/ctm/borealis/11 textures/optifine/ctm/borealis/12 textures/optifine/ctm/borealis/13 textures/optifine/ctm/borealis/14 textures/optifine/ctm/borealis/15 textures/optifine/ctm/borealis/16 textures/optifine/ctm/borealis/17 textures/optifine/ctm/borealis/18 textures/optifine/ctm/borealis/19 textures/optifine/ctm/borealis/20 textures/optifine/ctm/borealis/21 textures/optifine/ctm/borealis/22 textures/optifine/ctm/borealis/23 textures/optifine/ctm/borealis/24 textures/optifine/ctm/borealis/25 textures/optifine/ctm/borealis/26 textures/optifine/ctm/borealis/27 textures/optifine/ctm/borealis/28 textures/optifine/ctm/borealis/29 textures/optifine/ctm/borealis/30 textures/optifine/ctm/borealis/31 textures/optifine/ctm/borealis/32 textures/optifine/ctm/borealis/33 textures/optifine/ctm/borealis/34 textures/optifine/ctm/borealis/35
matchBlocks=erydon:borealis_block_silvertrim \
  erydon:borealis_trim_silver_stairs \
  erydon:borealis_trim_silver_stairs_shallow_bottom \
  erydon:borealis_trim_silver_stairs_shallow_top \
  erydon:borealis_trim_silver_layer_multiface \
  erydon:borealis_trim_silver_slope \
  erydon:borealis_trim_silver_slope_shallow_lower \
  erydon:borealis_trim_silver_slope_shallow_upper \
  erydon:borealis_trim_silver_slope_steep_lower \
  erydon:borealis_trim_silver_slope_steep_upper \
  erydon:borealis_trim_silver_slope_vertical \
  erydon:borealis_trim_silver_slope_vertical_shallow_broad \
  erydon:borealis_trim_silver_slope_vertical_shallow_narrow \
  erydon:borealis_block_bronzetrim \
  erydon:borealis_trim_bronze_stairs \
  erydon:borealis_trim_bronze_stairs_shallow_bottom \
  erydon:borealis_trim_bronze_stairs_shallow_top \
  erydon:borealis_trim_bronze_layer_multiface \
  erydon:borealis_trim_bronze_slope \
  erydon:borealis_trim_bronze_slope_shallow_lower \
  erydon:borealis_trim_bronze_slope_shallow_upper \
  erydon:borealis_trim_bronze_slope_steep_lower \
  erydon:borealis_trim_bronze_slope_steep_upper \
  erydon:borealis_trim_bronze_slope_vertical \
  erydon:borealis_trim_bronze_slope_vertical_shallow_broad \
  erydon:borealis_trim_bronze_slope_vertical_shallow_narrow \
  erydon:borealis_block_bronzequatrefoil \
  erydon:borealis_quatrefoil_bronze_stairs \
  erydon:borealis_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:borealis_quatrefoil_bronze_stairs_shallow_top \
  erydon:borealis_quatrefoil_bronze_layer_multiface \
  erydon:borealis_quatrefoil_bronze_slope \
  erydon:borealis_quatrefoil_bronze_slope_shallow_lower \
  erydon:borealis_quatrefoil_bronze_slope_shallow_upper \
  erydon:borealis_quatrefoil_bronze_slope_steep_lower \
  erydon:borealis_quatrefoil_bronze_slope_steep_upper \
  erydon:borealis_quatrefoil_bronze_slope_vertical \
  erydon:borealis_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:borealis_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:borealis_block_silverquatrefoil \
  erydon:borealis_quatrefoil_silver_stairs \
  erydon:borealis_quatrefoil_silver_stairs_shallow_bottom \
  erydon:borealis_quatrefoil_silver_stairs_shallow_top \
  erydon:borealis_quatrefoil_silver_layer_multiface \
  erydon:borealis_quatrefoil_silver_slope \
  erydon:borealis_quatrefoil_silver_slope_shallow_lower \
  erydon:borealis_quatrefoil_silver_slope_shallow_upper \
  erydon:borealis_quatrefoil_silver_slope_steep_lower \
  erydon:borealis_quatrefoil_silver_slope_steep_upper \
  erydon:borealis_quatrefoil_silver_slope_vertical \
  erydon:borealis_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:borealis_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:borealis_block_silverrose \
  erydon:borealis_rosette_silver_stairs \
  erydon:borealis_rosette_silver_stairs_shallow_bottom \
  erydon:borealis_rosette_silver_stairs_shallow_top \
  erydon:borealis_rosette_silver_layer_multiface \
  erydon:borealis_rosette_silver_slope \
  erydon:borealis_rosette_silver_slope_shallow_lower \
  erydon:borealis_rosette_silver_slope_shallow_upper \
  erydon:borealis_rosette_silver_slope_steep_lower \
  erydon:borealis_rosette_silver_slope_steep_upper \
  erydon:borealis_rosette_silver_slope_vertical \
  erydon:borealis_rosette_silver_slope_vertical_shallow_broad \
  erydon:borealis_rosette_silver_slope_vertical_shallow_narrow \
  erydon:borealis_block_bronzerose \
  erydon:borealis_rosette_bronze_stairs \
  erydon:borealis_rosette_bronze_stairs_shallow_bottom \
  erydon:borealis_rosette_bronze_stairs_shallow_top \
  erydon:borealis_rosette_bronze_layer_multiface \
  erydon:borealis_rosette_bronze_slope \
  erydon:borealis_rosette_bronze_slope_shallow_lower \
  erydon:borealis_rosette_bronze_slope_shallow_upper \
  erydon:borealis_rosette_bronze_slope_steep_lower \
  erydon:borealis_rosette_bronze_slope_steep_upper \
  erydon:borealis_rosette_bronze_slope_vertical \
  erydon:borealis_rosette_bronze_slope_vertical_shallow_broad \
  erydon:borealis_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:borealis_block_silverguilloche \
  erydon:borealis_guilloche_silver_stairs \
  erydon:borealis_guilloche_silver_stairs_shallow_bottom \
  erydon:borealis_guilloche_silver_stairs_shallow_top \
  erydon:borealis_guilloche_silver_layer_multiface \
  erydon:borealis_guilloche_silver_slope \
  erydon:borealis_guilloche_silver_slope_shallow_lower \
  erydon:borealis_guilloche_silver_slope_shallow_upper \
  erydon:borealis_guilloche_silver_slope_steep_lower \
  erydon:borealis_guilloche_silver_slope_steep_upper \
  erydon:borealis_guilloche_silver_slope_vertical \
  erydon:borealis_guilloche_silver_slope_vertical_shallow_broad \
  erydon:borealis_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:borealis_block_bronzeguilloche \
  erydon:borealis_guilloche_bronze_stairs \
  erydon:borealis_guilloche_bronze_stairs_shallow_bottom \
  erydon:borealis_guilloche_bronze_stairs_shallow_top \
  erydon:borealis_guilloche_bronze_layer_multiface \
  erydon:borealis_guilloche_bronze_slope \
  erydon:borealis_guilloche_bronze_slope_shallow_lower \
  erydon:borealis_guilloche_bronze_slope_shallow_upper \
  erydon:borealis_guilloche_bronze_slope_steep_lower \
  erydon:borealis_guilloche_bronze_slope_steep_upper \
  erydon:borealis_guilloche_bronze_slope_vertical \
  erydon:borealis_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:borealis_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
