method=repeat

width=6

height=6

tiles=textures/optifine/ctm/kylorion_glacium_weave_bronze/0 textures/optifine/ctm/kylorion_glacium_weave_bronze/1 textures/optifine/ctm/kylorion_glacium_weave_bronze/2 textures/optifine/ctm/kylorion_glacium_weave_bronze/3 textures/optifine/ctm/kylorion_glacium_weave_bronze/4 textures/optifine/ctm/kylorion_glacium_weave_bronze/5 textures/optifine/ctm/kylorion_glacium_weave_bronze/6 textures/optifine/ctm/kylorion_glacium_weave_bronze/7 textures/optifine/ctm/kylorion_glacium_weave_bronze/8 textures/optifine/ctm/kylorion_glacium_weave_bronze/9 textures/optifine/ctm/kylorion_glacium_weave_bronze/10 textures/optifine/ctm/kylorion_glacium_weave_bronze/11 textures/optifine/ctm/kylorion_glacium_weave_bronze/12 textures/optifine/ctm/kylorion_glacium_weave_bronze/13 textures/optifine/ctm/kylorion_glacium_weave_bronze/14 textures/optifine/ctm/kylorion_glacium_weave_bronze/15 textures/optifine/ctm/kylorion_glacium_weave_bronze/16 textures/optifine/ctm/kylorion_glacium_weave_bronze/17 textures/optifine/ctm/kylorion_glacium_weave_bronze/18 textures/optifine/ctm/kylorion_glacium_weave_bronze/19 textures/optifine/ctm/kylorion_glacium_weave_bronze/20 textures/optifine/ctm/kylorion_glacium_weave_bronze/21 textures/optifine/ctm/kylorion_glacium_weave_bronze/22 textures/optifine/ctm/kylorion_glacium_weave_bronze/23 textures/optifine/ctm/kylorion_glacium_weave_bronze/24 textures/optifine/ctm/kylorion_glacium_weave_bronze/25 textures/optifine/ctm/kylorion_glacium_weave_bronze/26 textures/optifine/ctm/kylorion_glacium_weave_bronze/27 textures/optifine/ctm/kylorion_glacium_weave_bronze/28 textures/optifine/ctm/kylorion_glacium_weave_bronze/29 textures/optifine/ctm/kylorion_glacium_weave_bronze/30 textures/optifine/ctm/kylorion_glacium_weave_bronze/31 textures/optifine/ctm/kylorion_glacium_weave_bronze/32 textures/optifine/ctm/kylorion_glacium_weave_bronze/33 textures/optifine/ctm/kylorion_glacium_weave_bronze/34 textures/optifine/ctm/kylorion_glacium_weave_bronze/35

matchBlocks=erydon:kylorion_glacium_weave_bronze_block \
  erydon:kylorion_glacium_weave_bronze_slab \
  erydon:kylorion_glacium_weave_bronze_wall \
  erydon:kylorion_glacium_weave_bronze_layer \
  erydon:kylorion_glacium_weave_bronze_layer_multiface \
  erydon:kylorion_glacium_weave_bronze_layer_vertical \
  erydon:kylorion_glacium_weave_bronze_slope \
  erydon:kylorion_glacium_weave_bronze_slope_shallow_upper \
  erydon:kylorion_glacium_weave_bronze_slope_steep_lower \
  erydon:kylorion_glacium_weave_bronze_slope_steep_upper \
  erydon:kylorion_glacium_weave_bronze_slope_shallow_lower \
  erydon:kylorion_glacium_weave_bronze_slope_vertical \
  erydon:kylorion_glacium_weave_bronze_slope_vertical_shallow_narrow \
  erydon:kylorion_glacium_weave_bronze_slope_vertical_shallow_broad \
  erydon:kylorion_glacium_weave_bronze_vertical_slice \
  erydon:kylorion_glacium_weave_bronze_horizontal_slice \
  erydon:kylorion_glacium_weave_bronze_post \
  erydon:kylorion_glacium_weave_bronze_wall_georgian
faces=top bottom north south east west

connect=block

innerSeams=true

priority=10
