method=repeat
width=6
height=6
tiles=textures/optifine/ctm/selenephos/0 textures/optifine/ctm/selenephos/1 textures/optifine/ctm/selenephos/2 textures/optifine/ctm/selenephos/3 textures/optifine/ctm/selenephos/4 textures/optifine/ctm/selenephos/5 textures/optifine/ctm/selenephos/6 textures/optifine/ctm/selenephos/7 textures/optifine/ctm/selenephos/8 textures/optifine/ctm/selenephos/9 textures/optifine/ctm/selenephos/10 textures/optifine/ctm/selenephos/11 textures/optifine/ctm/selenephos/12 textures/optifine/ctm/selenephos/13 textures/optifine/ctm/selenephos/14 textures/optifine/ctm/selenephos/15 textures/optifine/ctm/selenephos/16 textures/optifine/ctm/selenephos/17 textures/optifine/ctm/selenephos/18 textures/optifine/ctm/selenephos/19 textures/optifine/ctm/selenephos/20 textures/optifine/ctm/selenephos/21 textures/optifine/ctm/selenephos/22 textures/optifine/ctm/selenephos/23 textures/optifine/ctm/selenephos/24 textures/optifine/ctm/selenephos/25 textures/optifine/ctm/selenephos/26 textures/optifine/ctm/selenephos/27 textures/optifine/ctm/selenephos/28 textures/optifine/ctm/selenephos/29 textures/optifine/ctm/selenephos/30 textures/optifine/ctm/selenephos/31 textures/optifine/ctm/selenephos/32 textures/optifine/ctm/selenephos/33 textures/optifine/ctm/selenephos/34 textures/optifine/ctm/selenephos/35

matchBlocks=erydon:selenephos_ceiling_coffered_modern_white_small
matchTiles=erydon:block/selenephos_block

faces=all
connect=block
innerSeams=true
priority=10
