method=repeat

width=6

height=6

tiles=textures/optifine/ctm/selenephos/0 textures/optifine/ctm/selenephos/1 textures/optifine/ctm/selenephos/2 textures/optifine/ctm/selenephos/3 textures/optifine/ctm/selenephos/4 textures/optifine/ctm/selenephos/5 textures/optifine/ctm/selenephos/6 textures/optifine/ctm/selenephos/7 textures/optifine/ctm/selenephos/8 textures/optifine/ctm/selenephos/9 textures/optifine/ctm/selenephos/10 textures/optifine/ctm/selenephos/11 textures/optifine/ctm/selenephos/12 textures/optifine/ctm/selenephos/13 textures/optifine/ctm/selenephos/14 textures/optifine/ctm/selenephos/15 textures/optifine/ctm/selenephos/16 textures/optifine/ctm/selenephos/17 textures/optifine/ctm/selenephos/18 textures/optifine/ctm/selenephos/19 textures/optifine/ctm/selenephos/20 textures/optifine/ctm/selenephos/21 textures/optifine/ctm/selenephos/22 textures/optifine/ctm/selenephos/23 textures/optifine/ctm/selenephos/24 textures/optifine/ctm/selenephos/25 textures/optifine/ctm/selenephos/26 textures/optifine/ctm/selenephos/27 textures/optifine/ctm/selenephos/28 textures/optifine/ctm/selenephos/29 textures/optifine/ctm/selenephos/30 textures/optifine/ctm/selenephos/31 textures/optifine/ctm/selenephos/32 textures/optifine/ctm/selenephos/33 textures/optifine/ctm/selenephos/34 textures/optifine/ctm/selenephos/35

matchBlocks=erydon:selenephos_block \
  erydon:selenephos_stairs \
  erydon:selenephos_stairs_shallow_bottom \
  erydon:selenephos_stairs_shallow_top \
  erydon:selenephos_slab \
  erydon:selenephos_wall \
  erydon:selenephos_layer \
  erydon:selenephos_layer_multiface \
  erydon:selenephos_layer_vertical \
  erydon:selenephos_slope \
  erydon:selenephos_slope_shallow_upper \
  erydon:selenephos_slope_steep_lower \
  erydon:selenephos_slope_steep_upper \
  erydon:selenephos_slope_shallow_lower \
  erydon:selenephos_slope_vertical \
  erydon:selenephos_slope_vertical_shallow_narrow \
  erydon:selenephos_arch_romanesque \
  erydon:selenephos_slope_vertical_shallow_broad \
  erydon:selenephos_column_circular \
  erydon:selenephos_column_gothic \
  erydon:selenephos_column_square \
  erydon:selenephos_cornice_modern \
  erydon:selenephos_cornice_georgian \
  erydon:selenephos_cornice_guilloche \
  erydon:selenephos_cornice_gothic \
  erydon:selenephos_surround_georgian \
  erydon:selenephos_surround_guilloche \
  erydon:selenephos_surround_gothic_ornate \
  erydon:selenephos_surround_modern \
  erydon:selenephos_stairs_spiral_large \
  erydon:selenephos_light_modern \
  erydon:selenephos_chimney_circular \
  erydon:selenephos_vertical_slice \
  erydon:selenephos_horizontal_slice \
  erydon:selenephos_post \
  erydon:selenephos_wall_georgian \
  erydon:selenephos_alcove_georgian \
  erydon:selenephos_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
