method=repeat

width=6

height=6

tiles=textures/optifine/ctm/mielonyx/0 textures/optifine/ctm/mielonyx/1 textures/optifine/ctm/mielonyx/2 textures/optifine/ctm/mielonyx/3 textures/optifine/ctm/mielonyx/4 textures/optifine/ctm/mielonyx/5 textures/optifine/ctm/mielonyx/6 textures/optifine/ctm/mielonyx/7 textures/optifine/ctm/mielonyx/8 textures/optifine/ctm/mielonyx/9 textures/optifine/ctm/mielonyx/10 textures/optifine/ctm/mielonyx/11 textures/optifine/ctm/mielonyx/12 textures/optifine/ctm/mielonyx/13 textures/optifine/ctm/mielonyx/14 textures/optifine/ctm/mielonyx/15 textures/optifine/ctm/mielonyx/16 textures/optifine/ctm/mielonyx/17 textures/optifine/ctm/mielonyx/18 textures/optifine/ctm/mielonyx/19 textures/optifine/ctm/mielonyx/20 textures/optifine/ctm/mielonyx/21 textures/optifine/ctm/mielonyx/22 textures/optifine/ctm/mielonyx/23 textures/optifine/ctm/mielonyx/24 textures/optifine/ctm/mielonyx/25 textures/optifine/ctm/mielonyx/26 textures/optifine/ctm/mielonyx/27 textures/optifine/ctm/mielonyx/28 textures/optifine/ctm/mielonyx/29 textures/optifine/ctm/mielonyx/30 textures/optifine/ctm/mielonyx/31 textures/optifine/ctm/mielonyx/32 textures/optifine/ctm/mielonyx/33 textures/optifine/ctm/mielonyx/34 textures/optifine/ctm/mielonyx/35

matchBlocks=erydon:mielonyx_block \
  erydon:mielonyx_stairs \
  erydon:mielonyx_stairs_shallow_bottom \
  erydon:mielonyx_stairs_shallow_top \
  erydon:mielonyx_slab \
  erydon:mielonyx_wall \
  erydon:mielonyx_layer \
  erydon:mielonyx_layer_multiface \
  erydon:mielonyx_layer_vertical \
  erydon:mielonyx_slope \
  erydon:mielonyx_slope_shallow_upper \
  erydon:mielonyx_slope_steep_lower \
  erydon:mielonyx_slope_steep_upper \
  erydon:mielonyx_slope_shallow_lower \
  erydon:mielonyx_slope_vertical \
  erydon:mielonyx_slope_vertical_shallow_narrow \
  erydon:mielonyx_arch_romanesque \
  erydon:mielonyx_slope_vertical_shallow_broad \
  erydon:mielonyx_column_circular \
  erydon:mielonyx_column_gothic \
  erydon:mielonyx_column_square \
  erydon:mielonyx_cornice_modern \
  erydon:mielonyx_cornice_georgian \
  erydon:mielonyx_cornice_guilloche \
  erydon:mielonyx_cornice_gothic \
  erydon:mielonyx_surround_georgian \
  erydon:mielonyx_surround_guilloche \
  erydon:mielonyx_surround_gothic_ornate \
  erydon:mielonyx_surround_modern \
  erydon:mielonyx_stairs_spiral_large \
  erydon:mielonyx_light_modern \
  erydon:mielonyx_chimney_circular \
  erydon:mielonyx_vertical_slice \
  erydon:mielonyx_horizontal_slice \
  erydon:mielonyx_post \
  erydon:mielonyx_wall_georgian \
  erydon:mielonyx_alcove_georgian \
  erydon:mielonyx_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
