method=repeat
width=6
height=6
tiles=textures/optifine/ctm/mielonyx/0 textures/optifine/ctm/mielonyx/1 textures/optifine/ctm/mielonyx/2 textures/optifine/ctm/mielonyx/3 textures/optifine/ctm/mielonyx/4 textures/optifine/ctm/mielonyx/5 textures/optifine/ctm/mielonyx/6 textures/optifine/ctm/mielonyx/7 textures/optifine/ctm/mielonyx/8 textures/optifine/ctm/mielonyx/9 textures/optifine/ctm/mielonyx/10 textures/optifine/ctm/mielonyx/11 textures/optifine/ctm/mielonyx/12 textures/optifine/ctm/mielonyx/13 textures/optifine/ctm/mielonyx/14 textures/optifine/ctm/mielonyx/15 textures/optifine/ctm/mielonyx/16 textures/optifine/ctm/mielonyx/17 textures/optifine/ctm/mielonyx/18 textures/optifine/ctm/mielonyx/19 textures/optifine/ctm/mielonyx/20 textures/optifine/ctm/mielonyx/21 textures/optifine/ctm/mielonyx/22 textures/optifine/ctm/mielonyx/23 textures/optifine/ctm/mielonyx/24 textures/optifine/ctm/mielonyx/25 textures/optifine/ctm/mielonyx/26 textures/optifine/ctm/mielonyx/27 textures/optifine/ctm/mielonyx/28 textures/optifine/ctm/mielonyx/29 textures/optifine/ctm/mielonyx/30 textures/optifine/ctm/mielonyx/31 textures/optifine/ctm/mielonyx/32 textures/optifine/ctm/mielonyx/33 textures/optifine/ctm/mielonyx/34 textures/optifine/ctm/mielonyx/35

matchBlocks=erydon:mielonyx_ceiling_coffered_modern_white_small
matchTiles=erydon:block/mielonyx_block

faces=all
connect=block
innerSeams=true
priority=10
