method=repeat

width=6

height=6

tiles=textures/optifine/ctm/sanguenite/0 textures/optifine/ctm/sanguenite/1 textures/optifine/ctm/sanguenite/2 textures/optifine/ctm/sanguenite/3 textures/optifine/ctm/sanguenite/4 textures/optifine/ctm/sanguenite/5 textures/optifine/ctm/sanguenite/6 textures/optifine/ctm/sanguenite/7 textures/optifine/ctm/sanguenite/8 textures/optifine/ctm/sanguenite/9 textures/optifine/ctm/sanguenite/10 textures/optifine/ctm/sanguenite/11 textures/optifine/ctm/sanguenite/12 textures/optifine/ctm/sanguenite/13 textures/optifine/ctm/sanguenite/14 textures/optifine/ctm/sanguenite/15 textures/optifine/ctm/sanguenite/16 textures/optifine/ctm/sanguenite/17 textures/optifine/ctm/sanguenite/18 textures/optifine/ctm/sanguenite/19 textures/optifine/ctm/sanguenite/20 textures/optifine/ctm/sanguenite/21 textures/optifine/ctm/sanguenite/22 textures/optifine/ctm/sanguenite/23 textures/optifine/ctm/sanguenite/24 textures/optifine/ctm/sanguenite/25 textures/optifine/ctm/sanguenite/26 textures/optifine/ctm/sanguenite/27 textures/optifine/ctm/sanguenite/28 textures/optifine/ctm/sanguenite/29 textures/optifine/ctm/sanguenite/30 textures/optifine/ctm/sanguenite/31 textures/optifine/ctm/sanguenite/32 textures/optifine/ctm/sanguenite/33 textures/optifine/ctm/sanguenite/34 textures/optifine/ctm/sanguenite/35

matchBlocks=erydon:sanguenite_block \
  erydon:sanguenite_stairs \
  erydon:sanguenite_stairs_shallow_bottom \
  erydon:sanguenite_stairs_shallow_top \
  erydon:sanguenite_slab \
  erydon:sanguenite_wall \
  erydon:sanguenite_layer \
  erydon:sanguenite_layer_multiface \
  erydon:sanguenite_layer_vertical \
  erydon:sanguenite_slope \
  erydon:sanguenite_slope_shallow_upper \
  erydon:sanguenite_slope_steep_lower \
  erydon:sanguenite_slope_steep_upper \
  erydon:sanguenite_slope_shallow_lower \
  erydon:sanguenite_slope_vertical \
  erydon:sanguenite_slope_vertical_shallow_narrow \
  erydon:sanguenite_arch_romanesque \
  erydon:sanguenite_slope_vertical_shallow_broad \
  erydon:sanguenite_column_circular \
  erydon:sanguenite_column_gothic \
  erydon:sanguenite_column_square \
  erydon:sanguenite_cornice_modern \
  erydon:sanguenite_cornice_georgian \
  erydon:sanguenite_cornice_guilloche \
  erydon:sanguenite_cornice_gothic \
  erydon:sanguenite_surround_georgian \
  erydon:sanguenite_surround_guilloche \
  erydon:sanguenite_surround_gothic_ornate \
  erydon:sanguenite_surround_modern \
  erydon:sanguenite_stairs_spiral_large \
  erydon:sanguenite_light_modern \
  erydon:sanguenite_chimney_circular \
  erydon:sanguenite_vertical_slice \
  erydon:sanguenite_horizontal_slice \
  erydon:sanguenite_post \
  erydon:sanguenite_wall_georgian \
  erydon:sanguenite_alcove_georgian \
  erydon:sanguenite_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
