method=repeat
width=6
height=6
tiles=textures/optifine/ctm/sanguenite/0 textures/optifine/ctm/sanguenite/1 textures/optifine/ctm/sanguenite/2 textures/optifine/ctm/sanguenite/3 textures/optifine/ctm/sanguenite/4 textures/optifine/ctm/sanguenite/5 textures/optifine/ctm/sanguenite/6 textures/optifine/ctm/sanguenite/7 textures/optifine/ctm/sanguenite/8 textures/optifine/ctm/sanguenite/9 textures/optifine/ctm/sanguenite/10 textures/optifine/ctm/sanguenite/11 textures/optifine/ctm/sanguenite/12 textures/optifine/ctm/sanguenite/13 textures/optifine/ctm/sanguenite/14 textures/optifine/ctm/sanguenite/15 textures/optifine/ctm/sanguenite/16 textures/optifine/ctm/sanguenite/17 textures/optifine/ctm/sanguenite/18 textures/optifine/ctm/sanguenite/19 textures/optifine/ctm/sanguenite/20 textures/optifine/ctm/sanguenite/21 textures/optifine/ctm/sanguenite/22 textures/optifine/ctm/sanguenite/23 textures/optifine/ctm/sanguenite/24 textures/optifine/ctm/sanguenite/25 textures/optifine/ctm/sanguenite/26 textures/optifine/ctm/sanguenite/27 textures/optifine/ctm/sanguenite/28 textures/optifine/ctm/sanguenite/29 textures/optifine/ctm/sanguenite/30 textures/optifine/ctm/sanguenite/31 textures/optifine/ctm/sanguenite/32 textures/optifine/ctm/sanguenite/33 textures/optifine/ctm/sanguenite/34 textures/optifine/ctm/sanguenite/35

matchBlocks=erydon:sanguenite_window_arch
matchTiles=erydon:block/sanguenite_block

faces=all
connect=block
innerSeams=true
priority=10
