method=repeat
width=6
height=6
tiles=textures/optifine/ctm/sanguenite/0 textures/optifine/ctm/sanguenite/1 textures/optifine/ctm/sanguenite/2 textures/optifine/ctm/sanguenite/3 textures/optifine/ctm/sanguenite/4 textures/optifine/ctm/sanguenite/5 textures/optifine/ctm/sanguenite/6 textures/optifine/ctm/sanguenite/7 textures/optifine/ctm/sanguenite/8 textures/optifine/ctm/sanguenite/9 textures/optifine/ctm/sanguenite/10 textures/optifine/ctm/sanguenite/11 textures/optifine/ctm/sanguenite/12 textures/optifine/ctm/sanguenite/13 textures/optifine/ctm/sanguenite/14 textures/optifine/ctm/sanguenite/15 textures/optifine/ctm/sanguenite/16 textures/optifine/ctm/sanguenite/17 textures/optifine/ctm/sanguenite/18 textures/optifine/ctm/sanguenite/19 textures/optifine/ctm/sanguenite/20 textures/optifine/ctm/sanguenite/21 textures/optifine/ctm/sanguenite/22 textures/optifine/ctm/sanguenite/23 textures/optifine/ctm/sanguenite/24 textures/optifine/ctm/sanguenite/25 textures/optifine/ctm/sanguenite/26 textures/optifine/ctm/sanguenite/27 textures/optifine/ctm/sanguenite/28 textures/optifine/ctm/sanguenite/29 textures/optifine/ctm/sanguenite/30 textures/optifine/ctm/sanguenite/31 textures/optifine/ctm/sanguenite/32 textures/optifine/ctm/sanguenite/33 textures/optifine/ctm/sanguenite/34 textures/optifine/ctm/sanguenite/35
matchBlocks=erydon:sanguenite_block_silvertrim \
  erydon:sanguenite_trim_silver_stairs \
  erydon:sanguenite_trim_silver_stairs_shallow_bottom \
  erydon:sanguenite_trim_silver_stairs_shallow_top \
  erydon:sanguenite_trim_silver_layer_multiface \
  erydon:sanguenite_trim_silver_slope \
  erydon:sanguenite_trim_silver_slope_shallow_lower \
  erydon:sanguenite_trim_silver_slope_shallow_upper \
  erydon:sanguenite_trim_silver_slope_steep_lower \
  erydon:sanguenite_trim_silver_slope_steep_upper \
  erydon:sanguenite_trim_silver_slope_vertical \
  erydon:sanguenite_trim_silver_slope_vertical_shallow_broad \
  erydon:sanguenite_trim_silver_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_bronzetrim \
  erydon:sanguenite_trim_bronze_stairs \
  erydon:sanguenite_trim_bronze_stairs_shallow_bottom \
  erydon:sanguenite_trim_bronze_stairs_shallow_top \
  erydon:sanguenite_trim_bronze_layer_multiface \
  erydon:sanguenite_trim_bronze_slope \
  erydon:sanguenite_trim_bronze_slope_shallow_lower \
  erydon:sanguenite_trim_bronze_slope_shallow_upper \
  erydon:sanguenite_trim_bronze_slope_steep_lower \
  erydon:sanguenite_trim_bronze_slope_steep_upper \
  erydon:sanguenite_trim_bronze_slope_vertical \
  erydon:sanguenite_trim_bronze_slope_vertical_shallow_broad \
  erydon:sanguenite_trim_bronze_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_bronzequatrefoil \
  erydon:sanguenite_quatrefoil_bronze_stairs \
  erydon:sanguenite_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:sanguenite_quatrefoil_bronze_stairs_shallow_top \
  erydon:sanguenite_quatrefoil_bronze_layer_multiface \
  erydon:sanguenite_quatrefoil_bronze_slope \
  erydon:sanguenite_quatrefoil_bronze_slope_shallow_lower \
  erydon:sanguenite_quatrefoil_bronze_slope_shallow_upper \
  erydon:sanguenite_quatrefoil_bronze_slope_steep_lower \
  erydon:sanguenite_quatrefoil_bronze_slope_steep_upper \
  erydon:sanguenite_quatrefoil_bronze_slope_vertical \
  erydon:sanguenite_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:sanguenite_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_silverquatrefoil \
  erydon:sanguenite_quatrefoil_silver_stairs \
  erydon:sanguenite_quatrefoil_silver_stairs_shallow_bottom \
  erydon:sanguenite_quatrefoil_silver_stairs_shallow_top \
  erydon:sanguenite_quatrefoil_silver_layer_multiface \
  erydon:sanguenite_quatrefoil_silver_slope \
  erydon:sanguenite_quatrefoil_silver_slope_shallow_lower \
  erydon:sanguenite_quatrefoil_silver_slope_shallow_upper \
  erydon:sanguenite_quatrefoil_silver_slope_steep_lower \
  erydon:sanguenite_quatrefoil_silver_slope_steep_upper \
  erydon:sanguenite_quatrefoil_silver_slope_vertical \
  erydon:sanguenite_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:sanguenite_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_silverrose \
  erydon:sanguenite_rosette_silver_stairs \
  erydon:sanguenite_rosette_silver_stairs_shallow_bottom \
  erydon:sanguenite_rosette_silver_stairs_shallow_top \
  erydon:sanguenite_rosette_silver_layer_multiface \
  erydon:sanguenite_rosette_silver_slope \
  erydon:sanguenite_rosette_silver_slope_shallow_lower \
  erydon:sanguenite_rosette_silver_slope_shallow_upper \
  erydon:sanguenite_rosette_silver_slope_steep_lower \
  erydon:sanguenite_rosette_silver_slope_steep_upper \
  erydon:sanguenite_rosette_silver_slope_vertical \
  erydon:sanguenite_rosette_silver_slope_vertical_shallow_broad \
  erydon:sanguenite_rosette_silver_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_bronzerose \
  erydon:sanguenite_rosette_bronze_stairs \
  erydon:sanguenite_rosette_bronze_stairs_shallow_bottom \
  erydon:sanguenite_rosette_bronze_stairs_shallow_top \
  erydon:sanguenite_rosette_bronze_layer_multiface \
  erydon:sanguenite_rosette_bronze_slope \
  erydon:sanguenite_rosette_bronze_slope_shallow_lower \
  erydon:sanguenite_rosette_bronze_slope_shallow_upper \
  erydon:sanguenite_rosette_bronze_slope_steep_lower \
  erydon:sanguenite_rosette_bronze_slope_steep_upper \
  erydon:sanguenite_rosette_bronze_slope_vertical \
  erydon:sanguenite_rosette_bronze_slope_vertical_shallow_broad \
  erydon:sanguenite_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_silverguilloche \
  erydon:sanguenite_guilloche_silver_stairs \
  erydon:sanguenite_guilloche_silver_stairs_shallow_bottom \
  erydon:sanguenite_guilloche_silver_stairs_shallow_top \
  erydon:sanguenite_guilloche_silver_layer_multiface \
  erydon:sanguenite_guilloche_silver_slope \
  erydon:sanguenite_guilloche_silver_slope_shallow_lower \
  erydon:sanguenite_guilloche_silver_slope_shallow_upper \
  erydon:sanguenite_guilloche_silver_slope_steep_lower \
  erydon:sanguenite_guilloche_silver_slope_steep_upper \
  erydon:sanguenite_guilloche_silver_slope_vertical \
  erydon:sanguenite_guilloche_silver_slope_vertical_shallow_broad \
  erydon:sanguenite_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:sanguenite_block_bronzeguilloche \
  erydon:sanguenite_guilloche_bronze_stairs \
  erydon:sanguenite_guilloche_bronze_stairs_shallow_bottom \
  erydon:sanguenite_guilloche_bronze_stairs_shallow_top \
  erydon:sanguenite_guilloche_bronze_layer_multiface \
  erydon:sanguenite_guilloche_bronze_slope \
  erydon:sanguenite_guilloche_bronze_slope_shallow_lower \
  erydon:sanguenite_guilloche_bronze_slope_shallow_upper \
  erydon:sanguenite_guilloche_bronze_slope_steep_lower \
  erydon:sanguenite_guilloche_bronze_slope_steep_upper \
  erydon:sanguenite_guilloche_bronze_slope_vertical \
  erydon:sanguenite_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:sanguenite_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
