method=repeat
width=6
height=6
tiles=textures/optifine/ctm/laurentium/0 textures/optifine/ctm/laurentium/1 textures/optifine/ctm/laurentium/2 textures/optifine/ctm/laurentium/3 textures/optifine/ctm/laurentium/4 textures/optifine/ctm/laurentium/5 textures/optifine/ctm/laurentium/6 textures/optifine/ctm/laurentium/7 textures/optifine/ctm/laurentium/8 textures/optifine/ctm/laurentium/9 textures/optifine/ctm/laurentium/10 textures/optifine/ctm/laurentium/11 textures/optifine/ctm/laurentium/12 textures/optifine/ctm/laurentium/13 textures/optifine/ctm/laurentium/14 textures/optifine/ctm/laurentium/15 textures/optifine/ctm/laurentium/16 textures/optifine/ctm/laurentium/17 textures/optifine/ctm/laurentium/18 textures/optifine/ctm/laurentium/19 textures/optifine/ctm/laurentium/20 textures/optifine/ctm/laurentium/21 textures/optifine/ctm/laurentium/22 textures/optifine/ctm/laurentium/23 textures/optifine/ctm/laurentium/24 textures/optifine/ctm/laurentium/25 textures/optifine/ctm/laurentium/26 textures/optifine/ctm/laurentium/27 textures/optifine/ctm/laurentium/28 textures/optifine/ctm/laurentium/29 textures/optifine/ctm/laurentium/30 textures/optifine/ctm/laurentium/31 textures/optifine/ctm/laurentium/32 textures/optifine/ctm/laurentium/33 textures/optifine/ctm/laurentium/34 textures/optifine/ctm/laurentium/35

matchBlocks=erydon:laurentium_ceiling_coffered_modern_black_small
matchTiles=erydon:block/laurentium_block

faces=all
connect=block
innerSeams=true
priority=10
