method=repeat

width=6

height=6

tiles=textures/optifine/ctm/laurentium/0 textures/optifine/ctm/laurentium/1 textures/optifine/ctm/laurentium/2 textures/optifine/ctm/laurentium/3 textures/optifine/ctm/laurentium/4 textures/optifine/ctm/laurentium/5 textures/optifine/ctm/laurentium/6 textures/optifine/ctm/laurentium/7 textures/optifine/ctm/laurentium/8 textures/optifine/ctm/laurentium/9 textures/optifine/ctm/laurentium/10 textures/optifine/ctm/laurentium/11 textures/optifine/ctm/laurentium/12 textures/optifine/ctm/laurentium/13 textures/optifine/ctm/laurentium/14 textures/optifine/ctm/laurentium/15 textures/optifine/ctm/laurentium/16 textures/optifine/ctm/laurentium/17 textures/optifine/ctm/laurentium/18 textures/optifine/ctm/laurentium/19 textures/optifine/ctm/laurentium/20 textures/optifine/ctm/laurentium/21 textures/optifine/ctm/laurentium/22 textures/optifine/ctm/laurentium/23 textures/optifine/ctm/laurentium/24 textures/optifine/ctm/laurentium/25 textures/optifine/ctm/laurentium/26 textures/optifine/ctm/laurentium/27 textures/optifine/ctm/laurentium/28 textures/optifine/ctm/laurentium/29 textures/optifine/ctm/laurentium/30 textures/optifine/ctm/laurentium/31 textures/optifine/ctm/laurentium/32 textures/optifine/ctm/laurentium/33 textures/optifine/ctm/laurentium/34 textures/optifine/ctm/laurentium/35

matchBlocks=erydon:laurentium_block \
  erydon:laurentium_stairs \
  erydon:laurentium_stairs_shallow_bottom \
  erydon:laurentium_stairs_shallow_top \
  erydon:laurentium_slab \
  erydon:laurentium_wall \
  erydon:laurentium_layer \
  erydon:laurentium_layer_multiface \
  erydon:laurentium_layer_vertical \
  erydon:laurentium_slope \
  erydon:laurentium_slope_shallow_upper \
  erydon:laurentium_slope_steep_lower \
  erydon:laurentium_slope_steep_upper \
  erydon:laurentium_slope_shallow_lower \
  erydon:laurentium_slope_vertical \
  erydon:laurentium_slope_vertical_shallow_narrow \
  erydon:laurentium_arch_romanesque \
  erydon:laurentium_slope_vertical_shallow_broad \
  erydon:laurentium_column_circular \
  erydon:laurentium_column_gothic \
  erydon:laurentium_column_square \
  erydon:laurentium_cornice_modern \
  erydon:laurentium_cornice_georgian \
  erydon:laurentium_cornice_guilloche \
  erydon:laurentium_cornice_gothic \
  erydon:laurentium_surround_georgian \
  erydon:laurentium_surround_guilloche \
  erydon:laurentium_surround_gothic_ornate \
  erydon:laurentium_surround_modern \
  erydon:laurentium_stairs_spiral_large \
  erydon:laurentium_light_modern \
  erydon:laurentium_chimney_circular \
  erydon:laurentium_vertical_slice \
  erydon:laurentium_horizontal_slice \
  erydon:laurentium_post \
  erydon:laurentium_wall_georgian \
  erydon:laurentium_alcove_georgian \
  erydon:laurentium_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
