method=repeat
width=6
height=6
tiles=textures/optifine/ctm/laurentium/0 textures/optifine/ctm/laurentium/1 textures/optifine/ctm/laurentium/2 textures/optifine/ctm/laurentium/3 textures/optifine/ctm/laurentium/4 textures/optifine/ctm/laurentium/5 textures/optifine/ctm/laurentium/6 textures/optifine/ctm/laurentium/7 textures/optifine/ctm/laurentium/8 textures/optifine/ctm/laurentium/9 textures/optifine/ctm/laurentium/10 textures/optifine/ctm/laurentium/11 textures/optifine/ctm/laurentium/12 textures/optifine/ctm/laurentium/13 textures/optifine/ctm/laurentium/14 textures/optifine/ctm/laurentium/15 textures/optifine/ctm/laurentium/16 textures/optifine/ctm/laurentium/17 textures/optifine/ctm/laurentium/18 textures/optifine/ctm/laurentium/19 textures/optifine/ctm/laurentium/20 textures/optifine/ctm/laurentium/21 textures/optifine/ctm/laurentium/22 textures/optifine/ctm/laurentium/23 textures/optifine/ctm/laurentium/24 textures/optifine/ctm/laurentium/25 textures/optifine/ctm/laurentium/26 textures/optifine/ctm/laurentium/27 textures/optifine/ctm/laurentium/28 textures/optifine/ctm/laurentium/29 textures/optifine/ctm/laurentium/30 textures/optifine/ctm/laurentium/31 textures/optifine/ctm/laurentium/32 textures/optifine/ctm/laurentium/33 textures/optifine/ctm/laurentium/34 textures/optifine/ctm/laurentium/35
matchBlocks=erydon:laurentium_block_silvertrim \
  erydon:laurentium_trim_silver_stairs \
  erydon:laurentium_trim_silver_stairs_shallow_bottom \
  erydon:laurentium_trim_silver_stairs_shallow_top \
  erydon:laurentium_trim_silver_layer_multiface \
  erydon:laurentium_trim_silver_slope \
  erydon:laurentium_trim_silver_slope_shallow_lower \
  erydon:laurentium_trim_silver_slope_shallow_upper \
  erydon:laurentium_trim_silver_slope_steep_lower \
  erydon:laurentium_trim_silver_slope_steep_upper \
  erydon:laurentium_trim_silver_slope_vertical \
  erydon:laurentium_trim_silver_slope_vertical_shallow_broad \
  erydon:laurentium_trim_silver_slope_vertical_shallow_narrow \
  erydon:laurentium_block_bronzetrim \
  erydon:laurentium_trim_bronze_stairs \
  erydon:laurentium_trim_bronze_stairs_shallow_bottom \
  erydon:laurentium_trim_bronze_stairs_shallow_top \
  erydon:laurentium_trim_bronze_layer_multiface \
  erydon:laurentium_trim_bronze_slope \
  erydon:laurentium_trim_bronze_slope_shallow_lower \
  erydon:laurentium_trim_bronze_slope_shallow_upper \
  erydon:laurentium_trim_bronze_slope_steep_lower \
  erydon:laurentium_trim_bronze_slope_steep_upper \
  erydon:laurentium_trim_bronze_slope_vertical \
  erydon:laurentium_trim_bronze_slope_vertical_shallow_broad \
  erydon:laurentium_trim_bronze_slope_vertical_shallow_narrow \
  erydon:laurentium_block_bronzequatrefoil \
  erydon:laurentium_quatrefoil_bronze_stairs \
  erydon:laurentium_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:laurentium_quatrefoil_bronze_stairs_shallow_top \
  erydon:laurentium_quatrefoil_bronze_layer_multiface \
  erydon:laurentium_quatrefoil_bronze_slope \
  erydon:laurentium_quatrefoil_bronze_slope_shallow_lower \
  erydon:laurentium_quatrefoil_bronze_slope_shallow_upper \
  erydon:laurentium_quatrefoil_bronze_slope_steep_lower \
  erydon:laurentium_quatrefoil_bronze_slope_steep_upper \
  erydon:laurentium_quatrefoil_bronze_slope_vertical \
  erydon:laurentium_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:laurentium_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:laurentium_block_silverquatrefoil \
  erydon:laurentium_quatrefoil_silver_stairs \
  erydon:laurentium_quatrefoil_silver_stairs_shallow_bottom \
  erydon:laurentium_quatrefoil_silver_stairs_shallow_top \
  erydon:laurentium_quatrefoil_silver_layer_multiface \
  erydon:laurentium_quatrefoil_silver_slope \
  erydon:laurentium_quatrefoil_silver_slope_shallow_lower \
  erydon:laurentium_quatrefoil_silver_slope_shallow_upper \
  erydon:laurentium_quatrefoil_silver_slope_steep_lower \
  erydon:laurentium_quatrefoil_silver_slope_steep_upper \
  erydon:laurentium_quatrefoil_silver_slope_vertical \
  erydon:laurentium_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:laurentium_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:laurentium_block_silverrose \
  erydon:laurentium_rosette_silver_stairs \
  erydon:laurentium_rosette_silver_stairs_shallow_bottom \
  erydon:laurentium_rosette_silver_stairs_shallow_top \
  erydon:laurentium_rosette_silver_layer_multiface \
  erydon:laurentium_rosette_silver_slope \
  erydon:laurentium_rosette_silver_slope_shallow_lower \
  erydon:laurentium_rosette_silver_slope_shallow_upper \
  erydon:laurentium_rosette_silver_slope_steep_lower \
  erydon:laurentium_rosette_silver_slope_steep_upper \
  erydon:laurentium_rosette_silver_slope_vertical \
  erydon:laurentium_rosette_silver_slope_vertical_shallow_broad \
  erydon:laurentium_rosette_silver_slope_vertical_shallow_narrow \
  erydon:laurentium_block_bronzerose \
  erydon:laurentium_rosette_bronze_stairs \
  erydon:laurentium_rosette_bronze_stairs_shallow_bottom \
  erydon:laurentium_rosette_bronze_stairs_shallow_top \
  erydon:laurentium_rosette_bronze_layer_multiface \
  erydon:laurentium_rosette_bronze_slope \
  erydon:laurentium_rosette_bronze_slope_shallow_lower \
  erydon:laurentium_rosette_bronze_slope_shallow_upper \
  erydon:laurentium_rosette_bronze_slope_steep_lower \
  erydon:laurentium_rosette_bronze_slope_steep_upper \
  erydon:laurentium_rosette_bronze_slope_vertical \
  erydon:laurentium_rosette_bronze_slope_vertical_shallow_broad \
  erydon:laurentium_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:laurentium_block_silverguilloche \
  erydon:laurentium_guilloche_silver_stairs \
  erydon:laurentium_guilloche_silver_stairs_shallow_bottom \
  erydon:laurentium_guilloche_silver_stairs_shallow_top \
  erydon:laurentium_guilloche_silver_layer_multiface \
  erydon:laurentium_guilloche_silver_slope \
  erydon:laurentium_guilloche_silver_slope_shallow_lower \
  erydon:laurentium_guilloche_silver_slope_shallow_upper \
  erydon:laurentium_guilloche_silver_slope_steep_lower \
  erydon:laurentium_guilloche_silver_slope_steep_upper \
  erydon:laurentium_guilloche_silver_slope_vertical \
  erydon:laurentium_guilloche_silver_slope_vertical_shallow_broad \
  erydon:laurentium_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:laurentium_block_bronzeguilloche \
  erydon:laurentium_guilloche_bronze_stairs \
  erydon:laurentium_guilloche_bronze_stairs_shallow_bottom \
  erydon:laurentium_guilloche_bronze_stairs_shallow_top \
  erydon:laurentium_guilloche_bronze_layer_multiface \
  erydon:laurentium_guilloche_bronze_slope \
  erydon:laurentium_guilloche_bronze_slope_shallow_lower \
  erydon:laurentium_guilloche_bronze_slope_shallow_upper \
  erydon:laurentium_guilloche_bronze_slope_steep_lower \
  erydon:laurentium_guilloche_bronze_slope_steep_upper \
  erydon:laurentium_guilloche_bronze_slope_vertical \
  erydon:laurentium_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:laurentium_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
