method=repeat
width=6
height=6
tiles=textures/optifine/ctm/hesperion_aged/0 textures/optifine/ctm/hesperion_aged/1 textures/optifine/ctm/hesperion_aged/2 textures/optifine/ctm/hesperion_aged/3 textures/optifine/ctm/hesperion_aged/4 textures/optifine/ctm/hesperion_aged/5 textures/optifine/ctm/hesperion_aged/6 textures/optifine/ctm/hesperion_aged/7 textures/optifine/ctm/hesperion_aged/8 textures/optifine/ctm/hesperion_aged/9 textures/optifine/ctm/hesperion_aged/10 textures/optifine/ctm/hesperion_aged/11 textures/optifine/ctm/hesperion_aged/12 textures/optifine/ctm/hesperion_aged/13 textures/optifine/ctm/hesperion_aged/14 textures/optifine/ctm/hesperion_aged/15 textures/optifine/ctm/hesperion_aged/16 textures/optifine/ctm/hesperion_aged/17 textures/optifine/ctm/hesperion_aged/18 textures/optifine/ctm/hesperion_aged/19 textures/optifine/ctm/hesperion_aged/20 textures/optifine/ctm/hesperion_aged/21 textures/optifine/ctm/hesperion_aged/22 textures/optifine/ctm/hesperion_aged/23 textures/optifine/ctm/hesperion_aged/24 textures/optifine/ctm/hesperion_aged/25 textures/optifine/ctm/hesperion_aged/26 textures/optifine/ctm/hesperion_aged/27 textures/optifine/ctm/hesperion_aged/28 textures/optifine/ctm/hesperion_aged/29 textures/optifine/ctm/hesperion_aged/30 textures/optifine/ctm/hesperion_aged/31 textures/optifine/ctm/hesperion_aged/32 textures/optifine/ctm/hesperion_aged/33 textures/optifine/ctm/hesperion_aged/34 textures/optifine/ctm/hesperion_aged/35
matchBlocks=erydon:hesperion_block_aged \
  erydon:hesperion_stairs_aged \
  erydon:hesperion_stairs_shallow_bottom_aged \
  erydon:hesperion_stairs_shallow_top_aged \
  erydon:hesperion_slab_aged \
  erydon:hesperion_wall_aged \
  erydon:hesperion_layer_aged \
  erydon:hesperion_layer_multiface_aged \
  erydon:hesperion_layer_vertical_aged \
  erydon:hesperion_slope_aged \
  erydon:hesperion_slope_shallow_upper_aged \
  erydon:hesperion_slope_steep_lower_aged \
  erydon:hesperion_slope_steep_upper_aged \
  erydon:hesperion_slope_shallow_lower_aged \
  erydon:hesperion_slope_vertical_aged \
  erydon:hesperion_slope_vertical_shallow_narrow_aged \
  erydon:hesperion_arch_romanesque_aged \
  erydon:hesperion_slope_vertical_shallow_broad_aged \
  erydon:hesperion_column_circular_aged \
  erydon:hesperion_aged_column_gothic \
  erydon:hesperion_column_square_aged \
  erydon:hesperion_cornice_modern_aged \
  erydon:hesperion_cornice_georgian_aged \
  erydon:hesperion_cornice_guilloche_aged \
  erydon:hesperion_aged_cornice_gothic \
  erydon:hesperion_surround_georgian_aged \
  erydon:hesperion_surround_guilloche_aged \
  erydon:hesperion_aged_surround_gothic_ornate \
  erydon:hesperion_surround_modern_aged \
  erydon:hesperion_stairs_spiral_large_aged \
  erydon:hesperion_chimney_circular_aged \
  erydon:hesperion_vertical_slice_aged \
  erydon:hesperion_horizontal_slice_aged \
  erydon:hesperion_post_aged \
  erydon:hesperion_wall_georgian_aged \
  erydon:hesperion_aged_alcove_georgian \
  erydon:hesperion_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
