method=repeat
width=6
height=6
tiles=textures/optifine/ctm/gelastrum_aged/0 textures/optifine/ctm/gelastrum_aged/1 textures/optifine/ctm/gelastrum_aged/2 textures/optifine/ctm/gelastrum_aged/3 textures/optifine/ctm/gelastrum_aged/4 textures/optifine/ctm/gelastrum_aged/5 textures/optifine/ctm/gelastrum_aged/6 textures/optifine/ctm/gelastrum_aged/7 textures/optifine/ctm/gelastrum_aged/8 textures/optifine/ctm/gelastrum_aged/9 textures/optifine/ctm/gelastrum_aged/10 textures/optifine/ctm/gelastrum_aged/11 textures/optifine/ctm/gelastrum_aged/12 textures/optifine/ctm/gelastrum_aged/13 textures/optifine/ctm/gelastrum_aged/14 textures/optifine/ctm/gelastrum_aged/15 textures/optifine/ctm/gelastrum_aged/16 textures/optifine/ctm/gelastrum_aged/17 textures/optifine/ctm/gelastrum_aged/18 textures/optifine/ctm/gelastrum_aged/19 textures/optifine/ctm/gelastrum_aged/20 textures/optifine/ctm/gelastrum_aged/21 textures/optifine/ctm/gelastrum_aged/22 textures/optifine/ctm/gelastrum_aged/23 textures/optifine/ctm/gelastrum_aged/24 textures/optifine/ctm/gelastrum_aged/25 textures/optifine/ctm/gelastrum_aged/26 textures/optifine/ctm/gelastrum_aged/27 textures/optifine/ctm/gelastrum_aged/28 textures/optifine/ctm/gelastrum_aged/29 textures/optifine/ctm/gelastrum_aged/30 textures/optifine/ctm/gelastrum_aged/31 textures/optifine/ctm/gelastrum_aged/32 textures/optifine/ctm/gelastrum_aged/33 textures/optifine/ctm/gelastrum_aged/34 textures/optifine/ctm/gelastrum_aged/35
matchBlocks=erydon:gelastrum_block_aged \
  erydon:gelastrum_stairs_aged \
  erydon:gelastrum_stairs_shallow_bottom_aged \
  erydon:gelastrum_stairs_shallow_top_aged \
  erydon:gelastrum_slab_aged \
  erydon:gelastrum_wall_aged \
  erydon:gelastrum_layer_aged \
  erydon:gelastrum_layer_multiface_aged \
  erydon:gelastrum_layer_vertical_aged \
  erydon:gelastrum_slope_aged \
  erydon:gelastrum_slope_shallow_upper_aged \
  erydon:gelastrum_slope_steep_lower_aged \
  erydon:gelastrum_slope_steep_upper_aged \
  erydon:gelastrum_slope_shallow_lower_aged \
  erydon:gelastrum_slope_vertical_aged \
  erydon:gelastrum_slope_vertical_shallow_narrow_aged \
  erydon:gelastrum_arch_romanesque_aged \
  erydon:gelastrum_slope_vertical_shallow_broad_aged \
  erydon:gelastrum_column_circular_aged \
  erydon:gelastrum_aged_column_gothic \
  erydon:gelastrum_column_square_aged \
  erydon:gelastrum_cornice_modern_aged \
  erydon:gelastrum_cornice_georgian_aged \
  erydon:gelastrum_cornice_guilloche_aged \
  erydon:gelastrum_aged_cornice_gothic \
  erydon:gelastrum_surround_georgian_aged \
  erydon:gelastrum_surround_guilloche_aged \
  erydon:gelastrum_aged_surround_gothic_ornate \
  erydon:gelastrum_surround_modern_aged \
  erydon:gelastrum_stairs_spiral_large_aged \
  erydon:gelastrum_chimney_circular_aged \
  erydon:gelastrum_vertical_slice_aged \
  erydon:gelastrum_horizontal_slice_aged \
  erydon:gelastrum_post_aged \
  erydon:gelastrum_wall_georgian_aged \
  erydon:gelastrum_aged_alcove_georgian \
  erydon:gelastrum_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
