method=repeat
width=6
height=6
tiles=textures/optifine/ctm/chrysonyx_aged/0 textures/optifine/ctm/chrysonyx_aged/1 textures/optifine/ctm/chrysonyx_aged/2 textures/optifine/ctm/chrysonyx_aged/3 textures/optifine/ctm/chrysonyx_aged/4 textures/optifine/ctm/chrysonyx_aged/5 textures/optifine/ctm/chrysonyx_aged/6 textures/optifine/ctm/chrysonyx_aged/7 textures/optifine/ctm/chrysonyx_aged/8 textures/optifine/ctm/chrysonyx_aged/9 textures/optifine/ctm/chrysonyx_aged/10 textures/optifine/ctm/chrysonyx_aged/11 textures/optifine/ctm/chrysonyx_aged/12 textures/optifine/ctm/chrysonyx_aged/13 textures/optifine/ctm/chrysonyx_aged/14 textures/optifine/ctm/chrysonyx_aged/15 textures/optifine/ctm/chrysonyx_aged/16 textures/optifine/ctm/chrysonyx_aged/17 textures/optifine/ctm/chrysonyx_aged/18 textures/optifine/ctm/chrysonyx_aged/19 textures/optifine/ctm/chrysonyx_aged/20 textures/optifine/ctm/chrysonyx_aged/21 textures/optifine/ctm/chrysonyx_aged/22 textures/optifine/ctm/chrysonyx_aged/23 textures/optifine/ctm/chrysonyx_aged/24 textures/optifine/ctm/chrysonyx_aged/25 textures/optifine/ctm/chrysonyx_aged/26 textures/optifine/ctm/chrysonyx_aged/27 textures/optifine/ctm/chrysonyx_aged/28 textures/optifine/ctm/chrysonyx_aged/29 textures/optifine/ctm/chrysonyx_aged/30 textures/optifine/ctm/chrysonyx_aged/31 textures/optifine/ctm/chrysonyx_aged/32 textures/optifine/ctm/chrysonyx_aged/33 textures/optifine/ctm/chrysonyx_aged/34 textures/optifine/ctm/chrysonyx_aged/35
matchBlocks=erydon:chrysonyx_block_aged \
  erydon:chrysonyx_stairs_aged \
  erydon:chrysonyx_stairs_shallow_bottom_aged \
  erydon:chrysonyx_stairs_shallow_top_aged \
  erydon:chrysonyx_slab_aged \
  erydon:chrysonyx_wall_aged \
  erydon:chrysonyx_layer_aged \
  erydon:chrysonyx_layer_multiface_aged \
  erydon:chrysonyx_layer_vertical_aged \
  erydon:chrysonyx_slope_aged \
  erydon:chrysonyx_slope_shallow_upper_aged \
  erydon:chrysonyx_slope_steep_lower_aged \
  erydon:chrysonyx_slope_steep_upper_aged \
  erydon:chrysonyx_slope_shallow_lower_aged \
  erydon:chrysonyx_slope_vertical_aged \
  erydon:chrysonyx_slope_vertical_shallow_narrow_aged \
  erydon:chrysonyx_arch_romanesque_aged \
  erydon:chrysonyx_slope_vertical_shallow_broad_aged \
  erydon:chrysonyx_column_circular_aged \
  erydon:chrysonyx_aged_column_gothic \
  erydon:chrysonyx_column_square_aged \
  erydon:chrysonyx_cornice_modern_aged \
  erydon:chrysonyx_cornice_georgian_aged \
  erydon:chrysonyx_cornice_guilloche_aged \
  erydon:chrysonyx_aged_cornice_gothic \
  erydon:chrysonyx_surround_georgian_aged \
  erydon:chrysonyx_surround_guilloche_aged \
  erydon:chrysonyx_aged_surround_gothic_ornate \
  erydon:chrysonyx_surround_modern_aged \
  erydon:chrysonyx_stairs_spiral_large_aged \
  erydon:chrysonyx_chimney_circular_aged \
  erydon:chrysonyx_vertical_slice_aged \
  erydon:chrysonyx_horizontal_slice_aged \
  erydon:chrysonyx_post_aged \
  erydon:chrysonyx_wall_georgian_aged \
  erydon:chrysonyx_aged_alcove_georgian \
  erydon:chrysonyx_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
