method=repeat
width=6
height=6
tiles=textures/optifine/ctm/striatus/0 textures/optifine/ctm/striatus/1 textures/optifine/ctm/striatus/2 textures/optifine/ctm/striatus/3 textures/optifine/ctm/striatus/4 textures/optifine/ctm/striatus/5 textures/optifine/ctm/striatus/6 textures/optifine/ctm/striatus/7 textures/optifine/ctm/striatus/8 textures/optifine/ctm/striatus/9 textures/optifine/ctm/striatus/10 textures/optifine/ctm/striatus/11 textures/optifine/ctm/striatus/12 textures/optifine/ctm/striatus/13 textures/optifine/ctm/striatus/14 textures/optifine/ctm/striatus/15 textures/optifine/ctm/striatus/16 textures/optifine/ctm/striatus/17 textures/optifine/ctm/striatus/18 textures/optifine/ctm/striatus/19 textures/optifine/ctm/striatus/20 textures/optifine/ctm/striatus/21 textures/optifine/ctm/striatus/22 textures/optifine/ctm/striatus/23 textures/optifine/ctm/striatus/24 textures/optifine/ctm/striatus/25 textures/optifine/ctm/striatus/26 textures/optifine/ctm/striatus/27 textures/optifine/ctm/striatus/28 textures/optifine/ctm/striatus/29 textures/optifine/ctm/striatus/30 textures/optifine/ctm/striatus/31 textures/optifine/ctm/striatus/32 textures/optifine/ctm/striatus/33 textures/optifine/ctm/striatus/34 textures/optifine/ctm/striatus/35

matchBlocks=erydon:striatus_light_wall
matchTiles=erydon:block/striatus_block

faces=all
connect=block
innerSeams=true
priority=10
