method=repeat

width=6

height=6

tiles=textures/optifine/ctm/selenephos_ashlar/0 textures/optifine/ctm/selenephos_ashlar/1 textures/optifine/ctm/selenephos_ashlar/2 textures/optifine/ctm/selenephos_ashlar/3 textures/optifine/ctm/selenephos_ashlar/4 textures/optifine/ctm/selenephos_ashlar/5 textures/optifine/ctm/selenephos_ashlar/6 textures/optifine/ctm/selenephos_ashlar/7 textures/optifine/ctm/selenephos_ashlar/8 textures/optifine/ctm/selenephos_ashlar/9 textures/optifine/ctm/selenephos_ashlar/10 textures/optifine/ctm/selenephos_ashlar/11 textures/optifine/ctm/selenephos_ashlar/12 textures/optifine/ctm/selenephos_ashlar/13 textures/optifine/ctm/selenephos_ashlar/14 textures/optifine/ctm/selenephos_ashlar/15 textures/optifine/ctm/selenephos_ashlar/16 textures/optifine/ctm/selenephos_ashlar/17 textures/optifine/ctm/selenephos_ashlar/18 textures/optifine/ctm/selenephos_ashlar/19 textures/optifine/ctm/selenephos_ashlar/20 textures/optifine/ctm/selenephos_ashlar/21 textures/optifine/ctm/selenephos_ashlar/22 textures/optifine/ctm/selenephos_ashlar/23 textures/optifine/ctm/selenephos_ashlar/24 textures/optifine/ctm/selenephos_ashlar/25 textures/optifine/ctm/selenephos_ashlar/26 textures/optifine/ctm/selenephos_ashlar/27 textures/optifine/ctm/selenephos_ashlar/28 textures/optifine/ctm/selenephos_ashlar/29 textures/optifine/ctm/selenephos_ashlar/30 textures/optifine/ctm/selenephos_ashlar/31 textures/optifine/ctm/selenephos_ashlar/32 textures/optifine/ctm/selenephos_ashlar/33 textures/optifine/ctm/selenephos_ashlar/34 textures/optifine/ctm/selenephos_ashlar/35

matchBlocks=erydon:selenephos_ashlar_block \
  erydon:selenephos_ashlar_slab \
  erydon:selenephos_ashlar_wall \
  erydon:selenephos_ashlar_layer \
  erydon:selenephos_ashlar_layer_multiface \
  erydon:selenephos_ashlar_layer_vertical \
  erydon:selenephos_ashlar_slope \
  erydon:selenephos_ashlar_slope_shallow_upper \
  erydon:selenephos_ashlar_slope_steep_lower \
  erydon:selenephos_ashlar_slope_steep_upper \
  erydon:selenephos_ashlar_slope_shallow_lower \
  erydon:selenephos_ashlar_slope_vertical \
  erydon:selenephos_ashlar_stairs_spiral_large \
  erydon:selenephos_ashlar_slope_vertical_shallow_narrow \
  erydon:selenephos_ashlar_arch_romanesque \
  erydon:selenephos_ashlar_slope_vertical_shallow_broad \
  erydon:selenephos_ashlar_chimney_circular \
  erydon:selenephos_ashlar_vertical_slice \
  erydon:selenephos_ashlar_horizontal_slice \
  erydon:selenephos_ashlar_post \
  erydon:selenephos_ashlar_wall_georgian \
  erydon:selenephos_ashlar_alcove_georgian \
  erydon:selenephos_ashlar_alcove_gothic
faces=top bottom north south east west

connect=block

innerSeams=true

priority=10
