method=repeat

width=6

height=6

tiles=textures/optifine/ctm/psamatheon/0 textures/optifine/ctm/psamatheon/1 textures/optifine/ctm/psamatheon/2 textures/optifine/ctm/psamatheon/3 textures/optifine/ctm/psamatheon/4 textures/optifine/ctm/psamatheon/5 textures/optifine/ctm/psamatheon/6 textures/optifine/ctm/psamatheon/7 textures/optifine/ctm/psamatheon/8 textures/optifine/ctm/psamatheon/9 textures/optifine/ctm/psamatheon/10 textures/optifine/ctm/psamatheon/11 textures/optifine/ctm/psamatheon/12 textures/optifine/ctm/psamatheon/13 textures/optifine/ctm/psamatheon/14 textures/optifine/ctm/psamatheon/15 textures/optifine/ctm/psamatheon/16 textures/optifine/ctm/psamatheon/17 textures/optifine/ctm/psamatheon/18 textures/optifine/ctm/psamatheon/19 textures/optifine/ctm/psamatheon/20 textures/optifine/ctm/psamatheon/21 textures/optifine/ctm/psamatheon/22 textures/optifine/ctm/psamatheon/23 textures/optifine/ctm/psamatheon/24 textures/optifine/ctm/psamatheon/25 textures/optifine/ctm/psamatheon/26 textures/optifine/ctm/psamatheon/27 textures/optifine/ctm/psamatheon/28 textures/optifine/ctm/psamatheon/29 textures/optifine/ctm/psamatheon/30 textures/optifine/ctm/psamatheon/31 textures/optifine/ctm/psamatheon/32 textures/optifine/ctm/psamatheon/33 textures/optifine/ctm/psamatheon/34 textures/optifine/ctm/psamatheon/35

matchBlocks=erydon:psamatheon_block \
  erydon:psamatheon_stairs \
  erydon:psamatheon_stairs_shallow_bottom \
  erydon:psamatheon_stairs_shallow_top \
  erydon:psamatheon_slab \
  erydon:psamatheon_wall \
  erydon:psamatheon_layer \
  erydon:psamatheon_layer_multiface \
  erydon:psamatheon_layer_vertical \
  erydon:psamatheon_slope \
  erydon:psamatheon_slope_shallow_upper \
  erydon:psamatheon_slope_steep_lower \
  erydon:psamatheon_slope_steep_upper \
  erydon:psamatheon_slope_shallow_lower \
  erydon:psamatheon_slope_vertical \
  erydon:psamatheon_slope_vertical_shallow_narrow \
  erydon:psamatheon_arch_romanesque \
  erydon:psamatheon_slope_vertical_shallow_broad \
  erydon:psamatheon_column_circular \
  erydon:psamatheon_column_gothic \
  erydon:psamatheon_column_square \
  erydon:psamatheon_cornice_modern \
  erydon:psamatheon_cornice_georgian \
  erydon:psamatheon_cornice_guilloche \
  erydon:psamatheon_cornice_gothic \
  erydon:psamatheon_surround_georgian \
  erydon:psamatheon_surround_guilloche \
  erydon:psamatheon_surround_gothic_ornate \
  erydon:psamatheon_surround_modern \
  erydon:psamatheon_stairs_spiral_large \
  erydon:psamatheon_light_modern \
  erydon:psamatheon_chimney_circular \
  erydon:psamatheon_vertical_slice \
  erydon:psamatheon_horizontal_slice \
  erydon:psamatheon_post \
  erydon:psamatheon_wall_georgian \
  erydon:psamatheon_alcove_georgian \
  erydon:psamatheon_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
