method=repeat
width=6
height=6
tiles=textures/optifine/ctm/psamatheon/0 textures/optifine/ctm/psamatheon/1 textures/optifine/ctm/psamatheon/2 textures/optifine/ctm/psamatheon/3 textures/optifine/ctm/psamatheon/4 textures/optifine/ctm/psamatheon/5 textures/optifine/ctm/psamatheon/6 textures/optifine/ctm/psamatheon/7 textures/optifine/ctm/psamatheon/8 textures/optifine/ctm/psamatheon/9 textures/optifine/ctm/psamatheon/10 textures/optifine/ctm/psamatheon/11 textures/optifine/ctm/psamatheon/12 textures/optifine/ctm/psamatheon/13 textures/optifine/ctm/psamatheon/14 textures/optifine/ctm/psamatheon/15 textures/optifine/ctm/psamatheon/16 textures/optifine/ctm/psamatheon/17 textures/optifine/ctm/psamatheon/18 textures/optifine/ctm/psamatheon/19 textures/optifine/ctm/psamatheon/20 textures/optifine/ctm/psamatheon/21 textures/optifine/ctm/psamatheon/22 textures/optifine/ctm/psamatheon/23 textures/optifine/ctm/psamatheon/24 textures/optifine/ctm/psamatheon/25 textures/optifine/ctm/psamatheon/26 textures/optifine/ctm/psamatheon/27 textures/optifine/ctm/psamatheon/28 textures/optifine/ctm/psamatheon/29 textures/optifine/ctm/psamatheon/30 textures/optifine/ctm/psamatheon/31 textures/optifine/ctm/psamatheon/32 textures/optifine/ctm/psamatheon/33 textures/optifine/ctm/psamatheon/34 textures/optifine/ctm/psamatheon/35

matchBlocks=erydon:psamatheon_window_arch
matchTiles=erydon:block/psamatheon_block

faces=all
connect=block
innerSeams=true
priority=10
