method=repeat
width=6
height=6
tiles=textures/optifine/ctm/kelastrion/0 textures/optifine/ctm/kelastrion/1 textures/optifine/ctm/kelastrion/2 textures/optifine/ctm/kelastrion/3 textures/optifine/ctm/kelastrion/4 textures/optifine/ctm/kelastrion/5 textures/optifine/ctm/kelastrion/6 textures/optifine/ctm/kelastrion/7 textures/optifine/ctm/kelastrion/8 textures/optifine/ctm/kelastrion/9 textures/optifine/ctm/kelastrion/10 textures/optifine/ctm/kelastrion/11 textures/optifine/ctm/kelastrion/12 textures/optifine/ctm/kelastrion/13 textures/optifine/ctm/kelastrion/14 textures/optifine/ctm/kelastrion/15 textures/optifine/ctm/kelastrion/16 textures/optifine/ctm/kelastrion/17 textures/optifine/ctm/kelastrion/18 textures/optifine/ctm/kelastrion/19 textures/optifine/ctm/kelastrion/20 textures/optifine/ctm/kelastrion/21 textures/optifine/ctm/kelastrion/22 textures/optifine/ctm/kelastrion/23 textures/optifine/ctm/kelastrion/24 textures/optifine/ctm/kelastrion/25 textures/optifine/ctm/kelastrion/26 textures/optifine/ctm/kelastrion/27 textures/optifine/ctm/kelastrion/28 textures/optifine/ctm/kelastrion/29 textures/optifine/ctm/kelastrion/30 textures/optifine/ctm/kelastrion/31 textures/optifine/ctm/kelastrion/32 textures/optifine/ctm/kelastrion/33 textures/optifine/ctm/kelastrion/34 textures/optifine/ctm/kelastrion/35

matchBlocks=erydon:kelastrion_window_arch
matchTiles=erydon:block/kelastrion_block

faces=all
connect=block
innerSeams=true
priority=10
