method=repeat

width=6

height=6

tiles=textures/optifine/ctm/kelastrion/0 textures/optifine/ctm/kelastrion/1 textures/optifine/ctm/kelastrion/2 textures/optifine/ctm/kelastrion/3 textures/optifine/ctm/kelastrion/4 textures/optifine/ctm/kelastrion/5 textures/optifine/ctm/kelastrion/6 textures/optifine/ctm/kelastrion/7 textures/optifine/ctm/kelastrion/8 textures/optifine/ctm/kelastrion/9 textures/optifine/ctm/kelastrion/10 textures/optifine/ctm/kelastrion/11 textures/optifine/ctm/kelastrion/12 textures/optifine/ctm/kelastrion/13 textures/optifine/ctm/kelastrion/14 textures/optifine/ctm/kelastrion/15 textures/optifine/ctm/kelastrion/16 textures/optifine/ctm/kelastrion/17 textures/optifine/ctm/kelastrion/18 textures/optifine/ctm/kelastrion/19 textures/optifine/ctm/kelastrion/20 textures/optifine/ctm/kelastrion/21 textures/optifine/ctm/kelastrion/22 textures/optifine/ctm/kelastrion/23 textures/optifine/ctm/kelastrion/24 textures/optifine/ctm/kelastrion/25 textures/optifine/ctm/kelastrion/26 textures/optifine/ctm/kelastrion/27 textures/optifine/ctm/kelastrion/28 textures/optifine/ctm/kelastrion/29 textures/optifine/ctm/kelastrion/30 textures/optifine/ctm/kelastrion/31 textures/optifine/ctm/kelastrion/32 textures/optifine/ctm/kelastrion/33 textures/optifine/ctm/kelastrion/34 textures/optifine/ctm/kelastrion/35

matchBlocks=erydon:kelastrion_block \
  erydon:kelastrion_stairs \
  erydon:kelastrion_stairs_shallow_bottom \
  erydon:kelastrion_stairs_shallow_top \
  erydon:kelastrion_slab \
  erydon:kelastrion_wall \
  erydon:kelastrion_layer \
  erydon:kelastrion_layer_multiface \
  erydon:kelastrion_layer_vertical \
  erydon:kelastrion_slope \
  erydon:kelastrion_slope_shallow_upper \
  erydon:kelastrion_slope_steep_lower \
  erydon:kelastrion_slope_steep_upper \
  erydon:kelastrion_slope_shallow_lower \
  erydon:kelastrion_slope_vertical \
  erydon:kelastrion_slope_vertical_shallow_narrow \
  erydon:kelastrion_arch_romanesque \
  erydon:kelastrion_slope_vertical_shallow_broad \
  erydon:kelastrion_column_circular \
  erydon:kelastrion_column_gothic \
  erydon:kelastrion_column_square \
  erydon:kelastrion_cornice_modern \
  erydon:kelastrion_cornice_georgian \
  erydon:kelastrion_cornice_guilloche \
  erydon:kelastrion_cornice_gothic \
  erydon:kelastrion_surround_georgian \
  erydon:kelastrion_surround_guilloche \
  erydon:kelastrion_surround_gothic_ornate \
  erydon:kelastrion_surround_modern \
  erydon:kelastrion_stairs_spiral_large \
  erydon:kelastrion_light_modern \
  erydon:kelastrion_chimney_circular \
  erydon:kelastrion_vertical_slice \
  erydon:kelastrion_horizontal_slice \
  erydon:kelastrion_post \
  erydon:kelastrion_wall_georgian \
  erydon:kelastrion_alcove_georgian \
  erydon:kelastrion_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
