method=repeat
width=6
height=6
tiles=textures/optifine/ctm/porphyros_aged/0 textures/optifine/ctm/porphyros_aged/1 textures/optifine/ctm/porphyros_aged/2 textures/optifine/ctm/porphyros_aged/3 textures/optifine/ctm/porphyros_aged/4 textures/optifine/ctm/porphyros_aged/5 textures/optifine/ctm/porphyros_aged/6 textures/optifine/ctm/porphyros_aged/7 textures/optifine/ctm/porphyros_aged/8 textures/optifine/ctm/porphyros_aged/9 textures/optifine/ctm/porphyros_aged/10 textures/optifine/ctm/porphyros_aged/11 textures/optifine/ctm/porphyros_aged/12 textures/optifine/ctm/porphyros_aged/13 textures/optifine/ctm/porphyros_aged/14 textures/optifine/ctm/porphyros_aged/15 textures/optifine/ctm/porphyros_aged/16 textures/optifine/ctm/porphyros_aged/17 textures/optifine/ctm/porphyros_aged/18 textures/optifine/ctm/porphyros_aged/19 textures/optifine/ctm/porphyros_aged/20 textures/optifine/ctm/porphyros_aged/21 textures/optifine/ctm/porphyros_aged/22 textures/optifine/ctm/porphyros_aged/23 textures/optifine/ctm/porphyros_aged/24 textures/optifine/ctm/porphyros_aged/25 textures/optifine/ctm/porphyros_aged/26 textures/optifine/ctm/porphyros_aged/27 textures/optifine/ctm/porphyros_aged/28 textures/optifine/ctm/porphyros_aged/29 textures/optifine/ctm/porphyros_aged/30 textures/optifine/ctm/porphyros_aged/31 textures/optifine/ctm/porphyros_aged/32 textures/optifine/ctm/porphyros_aged/33 textures/optifine/ctm/porphyros_aged/34 textures/optifine/ctm/porphyros_aged/35
matchBlocks=erydon:porphyros_block_aged \
  erydon:porphyros_stairs_aged \
  erydon:porphyros_stairs_shallow_bottom_aged \
  erydon:porphyros_stairs_shallow_top_aged \
  erydon:porphyros_slab_aged \
  erydon:porphyros_wall_aged \
  erydon:porphyros_layer_aged \
  erydon:porphyros_layer_multiface_aged \
  erydon:porphyros_layer_vertical_aged \
  erydon:porphyros_slope_aged \
  erydon:porphyros_slope_shallow_upper_aged \
  erydon:porphyros_slope_steep_lower_aged \
  erydon:porphyros_slope_steep_upper_aged \
  erydon:porphyros_slope_shallow_lower_aged \
  erydon:porphyros_slope_vertical_aged \
  erydon:porphyros_slope_vertical_shallow_narrow_aged \
  erydon:porphyros_arch_romanesque_aged \
  erydon:porphyros_slope_vertical_shallow_broad_aged \
  erydon:porphyros_column_circular_aged \
  erydon:porphyros_aged_column_gothic \
  erydon:porphyros_column_square_aged \
  erydon:porphyros_cornice_modern_aged \
  erydon:porphyros_cornice_georgian_aged \
  erydon:porphyros_cornice_guilloche_aged \
  erydon:porphyros_aged_cornice_gothic \
  erydon:porphyros_surround_georgian_aged \
  erydon:porphyros_surround_guilloche_aged \
  erydon:porphyros_aged_surround_gothic_ornate \
  erydon:porphyros_surround_modern_aged \
  erydon:porphyros_stairs_spiral_large_aged \
  erydon:porphyros_chimney_circular_aged \
  erydon:porphyros_vertical_slice_aged \
  erydon:porphyros_horizontal_slice_aged \
  erydon:porphyros_post_aged \
  erydon:porphyros_wall_georgian_aged \
  erydon:porphyros_aged_alcove_georgian \
  erydon:porphyros_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
