method=repeat

width=6

height=6

tiles=textures/optifine/ctm/portorium/0 textures/optifine/ctm/portorium/1 textures/optifine/ctm/portorium/2 textures/optifine/ctm/portorium/3 textures/optifine/ctm/portorium/4 textures/optifine/ctm/portorium/5 textures/optifine/ctm/portorium/6 textures/optifine/ctm/portorium/7 textures/optifine/ctm/portorium/8 textures/optifine/ctm/portorium/9 textures/optifine/ctm/portorium/10 textures/optifine/ctm/portorium/11 textures/optifine/ctm/portorium/12 textures/optifine/ctm/portorium/13 textures/optifine/ctm/portorium/14 textures/optifine/ctm/portorium/15 textures/optifine/ctm/portorium/16 textures/optifine/ctm/portorium/17 textures/optifine/ctm/portorium/18 textures/optifine/ctm/portorium/19 textures/optifine/ctm/portorium/20 textures/optifine/ctm/portorium/21 textures/optifine/ctm/portorium/22 textures/optifine/ctm/portorium/23 textures/optifine/ctm/portorium/24 textures/optifine/ctm/portorium/25 textures/optifine/ctm/portorium/26 textures/optifine/ctm/portorium/27 textures/optifine/ctm/portorium/28 textures/optifine/ctm/portorium/29 textures/optifine/ctm/portorium/30 textures/optifine/ctm/portorium/31 textures/optifine/ctm/portorium/32 textures/optifine/ctm/portorium/33 textures/optifine/ctm/portorium/34 textures/optifine/ctm/portorium/35

matchBlocks=erydon:portorium_block \
  erydon:portorium_stairs \
  erydon:portorium_stairs_shallow_bottom \
  erydon:portorium_stairs_shallow_top \
  erydon:portorium_slab \
  erydon:portorium_wall \
  erydon:portorium_layer \
  erydon:portorium_layer_multiface \
  erydon:portorium_layer_vertical \
  erydon:portorium_slope \
  erydon:portorium_slope_shallow_upper \
  erydon:portorium_slope_steep_lower \
  erydon:portorium_slope_steep_upper \
  erydon:portorium_slope_shallow_lower \
  erydon:portorium_slope_vertical \
  erydon:portorium_slope_vertical_shallow_narrow \
  erydon:portorium_arch_romanesque \
  erydon:portorium_slope_vertical_shallow_broad \
  erydon:portorium_column_circular \
  erydon:portorium_column_gothic \
  erydon:portorium_column_square \
  erydon:portorium_cornice_modern \
  erydon:portorium_cornice_georgian \
  erydon:portorium_cornice_guilloche \
  erydon:portorium_cornice_gothic \
  erydon:portorium_surround_georgian \
  erydon:portorium_surround_guilloche \
  erydon:portorium_surround_gothic_ornate \
  erydon:portorium_surround_modern \
  erydon:portorium_stairs_spiral_large \
  erydon:portorium_light_modern \
  erydon:portorium_chimney_circular \
  erydon:portorium_vertical_slice \
  erydon:portorium_horizontal_slice \
  erydon:portorium_post \
  erydon:portorium_wall_georgian \
  erydon:portorium_alcove_georgian \
  erydon:portorium_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
