method=repeat
width=6
height=6
tiles=textures/optifine/ctm/portorium/0 textures/optifine/ctm/portorium/1 textures/optifine/ctm/portorium/2 textures/optifine/ctm/portorium/3 textures/optifine/ctm/portorium/4 textures/optifine/ctm/portorium/5 textures/optifine/ctm/portorium/6 textures/optifine/ctm/portorium/7 textures/optifine/ctm/portorium/8 textures/optifine/ctm/portorium/9 textures/optifine/ctm/portorium/10 textures/optifine/ctm/portorium/11 textures/optifine/ctm/portorium/12 textures/optifine/ctm/portorium/13 textures/optifine/ctm/portorium/14 textures/optifine/ctm/portorium/15 textures/optifine/ctm/portorium/16 textures/optifine/ctm/portorium/17 textures/optifine/ctm/portorium/18 textures/optifine/ctm/portorium/19 textures/optifine/ctm/portorium/20 textures/optifine/ctm/portorium/21 textures/optifine/ctm/portorium/22 textures/optifine/ctm/portorium/23 textures/optifine/ctm/portorium/24 textures/optifine/ctm/portorium/25 textures/optifine/ctm/portorium/26 textures/optifine/ctm/portorium/27 textures/optifine/ctm/portorium/28 textures/optifine/ctm/portorium/29 textures/optifine/ctm/portorium/30 textures/optifine/ctm/portorium/31 textures/optifine/ctm/portorium/32 textures/optifine/ctm/portorium/33 textures/optifine/ctm/portorium/34 textures/optifine/ctm/portorium/35
matchBlocks=erydon:portorium_block_silvertrim \
  erydon:portorium_trim_silver_stairs \
  erydon:portorium_trim_silver_stairs_shallow_bottom \
  erydon:portorium_trim_silver_stairs_shallow_top \
  erydon:portorium_trim_silver_layer_multiface \
  erydon:portorium_trim_silver_slope \
  erydon:portorium_trim_silver_slope_shallow_lower \
  erydon:portorium_trim_silver_slope_shallow_upper \
  erydon:portorium_trim_silver_slope_steep_lower \
  erydon:portorium_trim_silver_slope_steep_upper \
  erydon:portorium_trim_silver_slope_vertical \
  erydon:portorium_trim_silver_slope_vertical_shallow_broad \
  erydon:portorium_trim_silver_slope_vertical_shallow_narrow \
  erydon:portorium_block_bronzetrim \
  erydon:portorium_trim_bronze_stairs \
  erydon:portorium_trim_bronze_stairs_shallow_bottom \
  erydon:portorium_trim_bronze_stairs_shallow_top \
  erydon:portorium_trim_bronze_layer_multiface \
  erydon:portorium_trim_bronze_slope \
  erydon:portorium_trim_bronze_slope_shallow_lower \
  erydon:portorium_trim_bronze_slope_shallow_upper \
  erydon:portorium_trim_bronze_slope_steep_lower \
  erydon:portorium_trim_bronze_slope_steep_upper \
  erydon:portorium_trim_bronze_slope_vertical \
  erydon:portorium_trim_bronze_slope_vertical_shallow_broad \
  erydon:portorium_trim_bronze_slope_vertical_shallow_narrow \
  erydon:portorium_block_bronzequatrefoil \
  erydon:portorium_quatrefoil_bronze_stairs \
  erydon:portorium_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:portorium_quatrefoil_bronze_stairs_shallow_top \
  erydon:portorium_quatrefoil_bronze_layer_multiface \
  erydon:portorium_quatrefoil_bronze_slope \
  erydon:portorium_quatrefoil_bronze_slope_shallow_lower \
  erydon:portorium_quatrefoil_bronze_slope_shallow_upper \
  erydon:portorium_quatrefoil_bronze_slope_steep_lower \
  erydon:portorium_quatrefoil_bronze_slope_steep_upper \
  erydon:portorium_quatrefoil_bronze_slope_vertical \
  erydon:portorium_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:portorium_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:portorium_block_silverquatrefoil \
  erydon:portorium_quatrefoil_silver_stairs \
  erydon:portorium_quatrefoil_silver_stairs_shallow_bottom \
  erydon:portorium_quatrefoil_silver_stairs_shallow_top \
  erydon:portorium_quatrefoil_silver_layer_multiface \
  erydon:portorium_quatrefoil_silver_slope \
  erydon:portorium_quatrefoil_silver_slope_shallow_lower \
  erydon:portorium_quatrefoil_silver_slope_shallow_upper \
  erydon:portorium_quatrefoil_silver_slope_steep_lower \
  erydon:portorium_quatrefoil_silver_slope_steep_upper \
  erydon:portorium_quatrefoil_silver_slope_vertical \
  erydon:portorium_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:portorium_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:portorium_block_silverrose \
  erydon:portorium_rosette_silver_stairs \
  erydon:portorium_rosette_silver_stairs_shallow_bottom \
  erydon:portorium_rosette_silver_stairs_shallow_top \
  erydon:portorium_rosette_silver_layer_multiface \
  erydon:portorium_rosette_silver_slope \
  erydon:portorium_rosette_silver_slope_shallow_lower \
  erydon:portorium_rosette_silver_slope_shallow_upper \
  erydon:portorium_rosette_silver_slope_steep_lower \
  erydon:portorium_rosette_silver_slope_steep_upper \
  erydon:portorium_rosette_silver_slope_vertical \
  erydon:portorium_rosette_silver_slope_vertical_shallow_broad \
  erydon:portorium_rosette_silver_slope_vertical_shallow_narrow \
  erydon:portorium_block_bronzerose \
  erydon:portorium_rosette_bronze_stairs \
  erydon:portorium_rosette_bronze_stairs_shallow_bottom \
  erydon:portorium_rosette_bronze_stairs_shallow_top \
  erydon:portorium_rosette_bronze_layer_multiface \
  erydon:portorium_rosette_bronze_slope \
  erydon:portorium_rosette_bronze_slope_shallow_lower \
  erydon:portorium_rosette_bronze_slope_shallow_upper \
  erydon:portorium_rosette_bronze_slope_steep_lower \
  erydon:portorium_rosette_bronze_slope_steep_upper \
  erydon:portorium_rosette_bronze_slope_vertical \
  erydon:portorium_rosette_bronze_slope_vertical_shallow_broad \
  erydon:portorium_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:portorium_block_silverguilloche \
  erydon:portorium_guilloche_silver_stairs \
  erydon:portorium_guilloche_silver_stairs_shallow_bottom \
  erydon:portorium_guilloche_silver_stairs_shallow_top \
  erydon:portorium_guilloche_silver_layer_multiface \
  erydon:portorium_guilloche_silver_slope \
  erydon:portorium_guilloche_silver_slope_shallow_lower \
  erydon:portorium_guilloche_silver_slope_shallow_upper \
  erydon:portorium_guilloche_silver_slope_steep_lower \
  erydon:portorium_guilloche_silver_slope_steep_upper \
  erydon:portorium_guilloche_silver_slope_vertical \
  erydon:portorium_guilloche_silver_slope_vertical_shallow_broad \
  erydon:portorium_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:portorium_block_bronzeguilloche \
  erydon:portorium_guilloche_bronze_stairs \
  erydon:portorium_guilloche_bronze_stairs_shallow_bottom \
  erydon:portorium_guilloche_bronze_stairs_shallow_top \
  erydon:portorium_guilloche_bronze_layer_multiface \
  erydon:portorium_guilloche_bronze_slope \
  erydon:portorium_guilloche_bronze_slope_shallow_lower \
  erydon:portorium_guilloche_bronze_slope_shallow_upper \
  erydon:portorium_guilloche_bronze_slope_steep_lower \
  erydon:portorium_guilloche_bronze_slope_steep_upper \
  erydon:portorium_guilloche_bronze_slope_vertical \
  erydon:portorium_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:portorium_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
