method=repeat
width=6
height=6
tiles=textures/optifine/ctm/noxoplis_aged/0 textures/optifine/ctm/noxoplis_aged/1 textures/optifine/ctm/noxoplis_aged/2 textures/optifine/ctm/noxoplis_aged/3 textures/optifine/ctm/noxoplis_aged/4 textures/optifine/ctm/noxoplis_aged/5 textures/optifine/ctm/noxoplis_aged/6 textures/optifine/ctm/noxoplis_aged/7 textures/optifine/ctm/noxoplis_aged/8 textures/optifine/ctm/noxoplis_aged/9 textures/optifine/ctm/noxoplis_aged/10 textures/optifine/ctm/noxoplis_aged/11 textures/optifine/ctm/noxoplis_aged/12 textures/optifine/ctm/noxoplis_aged/13 textures/optifine/ctm/noxoplis_aged/14 textures/optifine/ctm/noxoplis_aged/15 textures/optifine/ctm/noxoplis_aged/16 textures/optifine/ctm/noxoplis_aged/17 textures/optifine/ctm/noxoplis_aged/18 textures/optifine/ctm/noxoplis_aged/19 textures/optifine/ctm/noxoplis_aged/20 textures/optifine/ctm/noxoplis_aged/21 textures/optifine/ctm/noxoplis_aged/22 textures/optifine/ctm/noxoplis_aged/23 textures/optifine/ctm/noxoplis_aged/24 textures/optifine/ctm/noxoplis_aged/25 textures/optifine/ctm/noxoplis_aged/26 textures/optifine/ctm/noxoplis_aged/27 textures/optifine/ctm/noxoplis_aged/28 textures/optifine/ctm/noxoplis_aged/29 textures/optifine/ctm/noxoplis_aged/30 textures/optifine/ctm/noxoplis_aged/31 textures/optifine/ctm/noxoplis_aged/32 textures/optifine/ctm/noxoplis_aged/33 textures/optifine/ctm/noxoplis_aged/34 textures/optifine/ctm/noxoplis_aged/35
matchBlocks=erydon:noxoplis_block_aged \
  erydon:noxoplis_stairs_aged \
  erydon:noxoplis_stairs_shallow_bottom_aged \
  erydon:noxoplis_stairs_shallow_top_aged \
  erydon:noxoplis_slab_aged \
  erydon:noxoplis_wall_aged \
  erydon:noxoplis_layer_aged \
  erydon:noxoplis_layer_multiface_aged \
  erydon:noxoplis_layer_vertical_aged \
  erydon:noxoplis_slope_aged \
  erydon:noxoplis_slope_shallow_upper_aged \
  erydon:noxoplis_slope_steep_lower_aged \
  erydon:noxoplis_slope_steep_upper_aged \
  erydon:noxoplis_slope_shallow_lower_aged \
  erydon:noxoplis_slope_vertical_aged \
  erydon:noxoplis_slope_vertical_shallow_narrow_aged \
  erydon:noxoplis_arch_romanesque_aged \
  erydon:noxoplis_slope_vertical_shallow_broad_aged \
  erydon:noxoplis_column_circular_aged \
  erydon:noxoplis_aged_column_gothic \
  erydon:noxoplis_column_square_aged \
  erydon:noxoplis_cornice_modern_aged \
  erydon:noxoplis_cornice_georgian_aged \
  erydon:noxoplis_cornice_guilloche_aged \
  erydon:noxoplis_aged_cornice_gothic \
  erydon:noxoplis_surround_georgian_aged \
  erydon:noxoplis_surround_guilloche_aged \
  erydon:noxoplis_aged_surround_gothic_ornate \
  erydon:noxoplis_surround_modern_aged \
  erydon:noxoplis_stairs_spiral_large_aged \
  erydon:noxoplis_chimney_circular_aged \
  erydon:noxoplis_vertical_slice_aged \
  erydon:noxoplis_horizontal_slice_aged \
  erydon:noxoplis_post_aged \
  erydon:noxoplis_wall_georgian_aged \
  erydon:noxoplis_aged_alcove_georgian \
  erydon:noxoplis_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
