method=repeat
width=6
height=6
tiles=textures/optifine/ctm/etruscus_rock/0 textures/optifine/ctm/etruscus_rock/1 textures/optifine/ctm/etruscus_rock/2 textures/optifine/ctm/etruscus_rock/3 textures/optifine/ctm/etruscus_rock/4 textures/optifine/ctm/etruscus_rock/5 textures/optifine/ctm/etruscus_rock/6 textures/optifine/ctm/etruscus_rock/7 textures/optifine/ctm/etruscus_rock/8 textures/optifine/ctm/etruscus_rock/9 textures/optifine/ctm/etruscus_rock/10 textures/optifine/ctm/etruscus_rock/11 textures/optifine/ctm/etruscus_rock/12 textures/optifine/ctm/etruscus_rock/13 textures/optifine/ctm/etruscus_rock/14 textures/optifine/ctm/etruscus_rock/15 textures/optifine/ctm/etruscus_rock/16 textures/optifine/ctm/etruscus_rock/17 textures/optifine/ctm/etruscus_rock/18 textures/optifine/ctm/etruscus_rock/19 textures/optifine/ctm/etruscus_rock/20 textures/optifine/ctm/etruscus_rock/21 textures/optifine/ctm/etruscus_rock/22 textures/optifine/ctm/etruscus_rock/23 textures/optifine/ctm/etruscus_rock/24 textures/optifine/ctm/etruscus_rock/25 textures/optifine/ctm/etruscus_rock/26 textures/optifine/ctm/etruscus_rock/27 textures/optifine/ctm/etruscus_rock/28 textures/optifine/ctm/etruscus_rock/29 textures/optifine/ctm/etruscus_rock/30 textures/optifine/ctm/etruscus_rock/31 textures/optifine/ctm/etruscus_rock/32 textures/optifine/ctm/etruscus_rock/33 textures/optifine/ctm/etruscus_rock/34 textures/optifine/ctm/etruscus_rock/35
matchBlocks=erydon:etruscus_rock_block \
  erydon:etruscus_rock_slab \
  erydon:etruscus_rock_layer \
  erydon:etruscus_rock_layer_vertical \
  erydon:etruscus_rock_slope \
  erydon:etruscus_rock_slope_shallow_lower \
  erydon:etruscus_rock_slope_shallow_upper \
  erydon:etruscus_rock_slope_steep_lower \
  erydon:etruscus_rock_slope_steep_upper \
  erydon:etruscus_rock_slope_vertical \
  erydon:etruscus_rock_slope_vertical_shallow_narrow \
  erydon:etruscus_rock_slope_vertical_shallow_broad \
  erydon:etruscus_rock_arch_romanesque \
  erydon:etruscus_rock_slice_vertical \
  erydon:etruscus_rock_slice_horizontal \
  erydon:etruscus_rock_post \
  erydon:etruscus_rock_stairs \
  erydon:etruscus_rock_wall \
  erydon:etruscus_rock_alcove_georgian \
  erydon:etruscus_rock_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
