method=repeat
width=6
height=6
tiles=textures/optifine/ctm/mielonyx_aged/0 textures/optifine/ctm/mielonyx_aged/1 textures/optifine/ctm/mielonyx_aged/2 textures/optifine/ctm/mielonyx_aged/3 textures/optifine/ctm/mielonyx_aged/4 textures/optifine/ctm/mielonyx_aged/5 textures/optifine/ctm/mielonyx_aged/6 textures/optifine/ctm/mielonyx_aged/7 textures/optifine/ctm/mielonyx_aged/8 textures/optifine/ctm/mielonyx_aged/9 textures/optifine/ctm/mielonyx_aged/10 textures/optifine/ctm/mielonyx_aged/11 textures/optifine/ctm/mielonyx_aged/12 textures/optifine/ctm/mielonyx_aged/13 textures/optifine/ctm/mielonyx_aged/14 textures/optifine/ctm/mielonyx_aged/15 textures/optifine/ctm/mielonyx_aged/16 textures/optifine/ctm/mielonyx_aged/17 textures/optifine/ctm/mielonyx_aged/18 textures/optifine/ctm/mielonyx_aged/19 textures/optifine/ctm/mielonyx_aged/20 textures/optifine/ctm/mielonyx_aged/21 textures/optifine/ctm/mielonyx_aged/22 textures/optifine/ctm/mielonyx_aged/23 textures/optifine/ctm/mielonyx_aged/24 textures/optifine/ctm/mielonyx_aged/25 textures/optifine/ctm/mielonyx_aged/26 textures/optifine/ctm/mielonyx_aged/27 textures/optifine/ctm/mielonyx_aged/28 textures/optifine/ctm/mielonyx_aged/29 textures/optifine/ctm/mielonyx_aged/30 textures/optifine/ctm/mielonyx_aged/31 textures/optifine/ctm/mielonyx_aged/32 textures/optifine/ctm/mielonyx_aged/33 textures/optifine/ctm/mielonyx_aged/34 textures/optifine/ctm/mielonyx_aged/35
matchBlocks=erydon:mielonyx_block_aged \
  erydon:mielonyx_stairs_aged \
  erydon:mielonyx_stairs_shallow_bottom_aged \
  erydon:mielonyx_stairs_shallow_top_aged \
  erydon:mielonyx_slab_aged \
  erydon:mielonyx_wall_aged \
  erydon:mielonyx_layer_aged \
  erydon:mielonyx_layer_multiface_aged \
  erydon:mielonyx_layer_vertical_aged \
  erydon:mielonyx_slope_aged \
  erydon:mielonyx_slope_shallow_upper_aged \
  erydon:mielonyx_slope_steep_lower_aged \
  erydon:mielonyx_slope_steep_upper_aged \
  erydon:mielonyx_slope_shallow_lower_aged \
  erydon:mielonyx_slope_vertical_aged \
  erydon:mielonyx_slope_vertical_shallow_narrow_aged \
  erydon:mielonyx_arch_romanesque_aged \
  erydon:mielonyx_slope_vertical_shallow_broad_aged \
  erydon:mielonyx_column_circular_aged \
  erydon:mielonyx_aged_column_gothic \
  erydon:mielonyx_column_square_aged \
  erydon:mielonyx_cornice_modern_aged \
  erydon:mielonyx_cornice_georgian_aged \
  erydon:mielonyx_cornice_guilloche_aged \
  erydon:mielonyx_aged_cornice_gothic \
  erydon:mielonyx_surround_georgian_aged \
  erydon:mielonyx_surround_guilloche_aged \
  erydon:mielonyx_aged_surround_gothic_ornate \
  erydon:mielonyx_surround_modern_aged \
  erydon:mielonyx_stairs_spiral_large_aged \
  erydon:mielonyx_chimney_circular_aged \
  erydon:mielonyx_vertical_slice_aged \
  erydon:mielonyx_horizontal_slice_aged \
  erydon:mielonyx_post_aged \
  erydon:mielonyx_wall_georgian_aged \
  erydon:mielonyx_aged_alcove_georgian \
  erydon:mielonyx_aged_alcove_gothic
faces=all
connect=block
innerSeams=true
priority=10
