method=repeat
width=6
height=6
tiles=textures/optifine/ctm/chalstrom/0 textures/optifine/ctm/chalstrom/1 textures/optifine/ctm/chalstrom/2 textures/optifine/ctm/chalstrom/3 textures/optifine/ctm/chalstrom/4 textures/optifine/ctm/chalstrom/5 textures/optifine/ctm/chalstrom/6 textures/optifine/ctm/chalstrom/7 textures/optifine/ctm/chalstrom/8 textures/optifine/ctm/chalstrom/9 textures/optifine/ctm/chalstrom/10 textures/optifine/ctm/chalstrom/11 textures/optifine/ctm/chalstrom/12 textures/optifine/ctm/chalstrom/13 textures/optifine/ctm/chalstrom/14 textures/optifine/ctm/chalstrom/15 textures/optifine/ctm/chalstrom/16 textures/optifine/ctm/chalstrom/17 textures/optifine/ctm/chalstrom/18 textures/optifine/ctm/chalstrom/19 textures/optifine/ctm/chalstrom/20 textures/optifine/ctm/chalstrom/21 textures/optifine/ctm/chalstrom/22 textures/optifine/ctm/chalstrom/23 textures/optifine/ctm/chalstrom/24 textures/optifine/ctm/chalstrom/25 textures/optifine/ctm/chalstrom/26 textures/optifine/ctm/chalstrom/27 textures/optifine/ctm/chalstrom/28 textures/optifine/ctm/chalstrom/29 textures/optifine/ctm/chalstrom/30 textures/optifine/ctm/chalstrom/31 textures/optifine/ctm/chalstrom/32 textures/optifine/ctm/chalstrom/33 textures/optifine/ctm/chalstrom/34 textures/optifine/ctm/chalstrom/35

matchBlocks=erydon:chalstrom_ceiling_coffered_georgian_black_small
matchTiles=erydon:block/chalstrom_block

faces=all
connect=block
innerSeams=true
priority=10
