method=repeat

width=6

height=6

tiles=textures/optifine/ctm/chalstrom/0 textures/optifine/ctm/chalstrom/1 textures/optifine/ctm/chalstrom/2 textures/optifine/ctm/chalstrom/3 textures/optifine/ctm/chalstrom/4 textures/optifine/ctm/chalstrom/5 textures/optifine/ctm/chalstrom/6 textures/optifine/ctm/chalstrom/7 textures/optifine/ctm/chalstrom/8 textures/optifine/ctm/chalstrom/9 textures/optifine/ctm/chalstrom/10 textures/optifine/ctm/chalstrom/11 textures/optifine/ctm/chalstrom/12 textures/optifine/ctm/chalstrom/13 textures/optifine/ctm/chalstrom/14 textures/optifine/ctm/chalstrom/15 textures/optifine/ctm/chalstrom/16 textures/optifine/ctm/chalstrom/17 textures/optifine/ctm/chalstrom/18 textures/optifine/ctm/chalstrom/19 textures/optifine/ctm/chalstrom/20 textures/optifine/ctm/chalstrom/21 textures/optifine/ctm/chalstrom/22 textures/optifine/ctm/chalstrom/23 textures/optifine/ctm/chalstrom/24 textures/optifine/ctm/chalstrom/25 textures/optifine/ctm/chalstrom/26 textures/optifine/ctm/chalstrom/27 textures/optifine/ctm/chalstrom/28 textures/optifine/ctm/chalstrom/29 textures/optifine/ctm/chalstrom/30 textures/optifine/ctm/chalstrom/31 textures/optifine/ctm/chalstrom/32 textures/optifine/ctm/chalstrom/33 textures/optifine/ctm/chalstrom/34 textures/optifine/ctm/chalstrom/35

matchBlocks=erydon:chalstrom_block \
  erydon:chalstrom_stairs \
  erydon:chalstrom_stairs_shallow_bottom \
  erydon:chalstrom_stairs_shallow_top \
  erydon:chalstrom_slab \
  erydon:chalstrom_wall \
  erydon:chalstrom_layer \
  erydon:chalstrom_layer_multiface \
  erydon:chalstrom_layer_vertical \
  erydon:chalstrom_slope \
  erydon:chalstrom_slope_shallow_upper \
  erydon:chalstrom_slope_steep_lower \
  erydon:chalstrom_slope_steep_upper \
  erydon:chalstrom_slope_shallow_lower \
  erydon:chalstrom_slope_vertical \
  erydon:chalstrom_slope_vertical_shallow_narrow \
  erydon:chalstrom_arch_romanesque \
  erydon:chalstrom_slope_vertical_shallow_broad \
  erydon:chalstrom_column_circular \
  erydon:chalstrom_column_gothic \
  erydon:chalstrom_column_square \
  erydon:chalstrom_cornice_modern \
  erydon:chalstrom_cornice_georgian \
  erydon:chalstrom_cornice_guilloche \
  erydon:chalstrom_cornice_gothic \
  erydon:chalstrom_surround_georgian \
  erydon:chalstrom_surround_guilloche \
  erydon:chalstrom_surround_gothic_ornate \
  erydon:chalstrom_surround_modern \
  erydon:chalstrom_stairs_spiral_large \
  erydon:chalstrom_light_modern \
  erydon:chalstrom_chimney_circular \
  erydon:chalstrom_vertical_slice \
  erydon:chalstrom_horizontal_slice \
  erydon:chalstrom_post \
  erydon:chalstrom_wall_georgian \
  erydon:chalstrom_alcove_georgian \
  erydon:chalstrom_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
