method=repeat
width=6
height=6
tiles=textures/optifine/ctm/rosinium/0 textures/optifine/ctm/rosinium/1 textures/optifine/ctm/rosinium/2 textures/optifine/ctm/rosinium/3 textures/optifine/ctm/rosinium/4 textures/optifine/ctm/rosinium/5 textures/optifine/ctm/rosinium/6 textures/optifine/ctm/rosinium/7 textures/optifine/ctm/rosinium/8 textures/optifine/ctm/rosinium/9 textures/optifine/ctm/rosinium/10 textures/optifine/ctm/rosinium/11 textures/optifine/ctm/rosinium/12 textures/optifine/ctm/rosinium/13 textures/optifine/ctm/rosinium/14 textures/optifine/ctm/rosinium/15 textures/optifine/ctm/rosinium/16 textures/optifine/ctm/rosinium/17 textures/optifine/ctm/rosinium/18 textures/optifine/ctm/rosinium/19 textures/optifine/ctm/rosinium/20 textures/optifine/ctm/rosinium/21 textures/optifine/ctm/rosinium/22 textures/optifine/ctm/rosinium/23 textures/optifine/ctm/rosinium/24 textures/optifine/ctm/rosinium/25 textures/optifine/ctm/rosinium/26 textures/optifine/ctm/rosinium/27 textures/optifine/ctm/rosinium/28 textures/optifine/ctm/rosinium/29 textures/optifine/ctm/rosinium/30 textures/optifine/ctm/rosinium/31 textures/optifine/ctm/rosinium/32 textures/optifine/ctm/rosinium/33 textures/optifine/ctm/rosinium/34 textures/optifine/ctm/rosinium/35

matchBlocks=erydon:rosinium_ceiling_coffered_guilloche_black_small
matchTiles=erydon:block/rosinium_block

faces=all
connect=block
innerSeams=true
priority=10
