method=repeat

width=6

height=6

tiles=textures/optifine/ctm/rosinium/0 textures/optifine/ctm/rosinium/1 textures/optifine/ctm/rosinium/2 textures/optifine/ctm/rosinium/3 textures/optifine/ctm/rosinium/4 textures/optifine/ctm/rosinium/5 textures/optifine/ctm/rosinium/6 textures/optifine/ctm/rosinium/7 textures/optifine/ctm/rosinium/8 textures/optifine/ctm/rosinium/9 textures/optifine/ctm/rosinium/10 textures/optifine/ctm/rosinium/11 textures/optifine/ctm/rosinium/12 textures/optifine/ctm/rosinium/13 textures/optifine/ctm/rosinium/14 textures/optifine/ctm/rosinium/15 textures/optifine/ctm/rosinium/16 textures/optifine/ctm/rosinium/17 textures/optifine/ctm/rosinium/18 textures/optifine/ctm/rosinium/19 textures/optifine/ctm/rosinium/20 textures/optifine/ctm/rosinium/21 textures/optifine/ctm/rosinium/22 textures/optifine/ctm/rosinium/23 textures/optifine/ctm/rosinium/24 textures/optifine/ctm/rosinium/25 textures/optifine/ctm/rosinium/26 textures/optifine/ctm/rosinium/27 textures/optifine/ctm/rosinium/28 textures/optifine/ctm/rosinium/29 textures/optifine/ctm/rosinium/30 textures/optifine/ctm/rosinium/31 textures/optifine/ctm/rosinium/32 textures/optifine/ctm/rosinium/33 textures/optifine/ctm/rosinium/34 textures/optifine/ctm/rosinium/35

matchBlocks=erydon:rosinium_block \
  erydon:rosinium_stairs \
  erydon:rosinium_stairs_shallow_bottom \
  erydon:rosinium_stairs_shallow_top \
  erydon:rosinium_slab \
  erydon:rosinium_wall \
  erydon:rosinium_layer \
  erydon:rosinium_layer_multiface \
  erydon:rosinium_layer_vertical \
  erydon:rosinium_slope \
  erydon:rosinium_slope_shallow_upper \
  erydon:rosinium_slope_steep_lower \
  erydon:rosinium_slope_steep_upper \
  erydon:rosinium_slope_shallow_lower \
  erydon:rosinium_slope_vertical \
  erydon:rosinium_slope_vertical_shallow_narrow \
  erydon:rosinium_arch_romanesque \
  erydon:rosinium_slope_vertical_shallow_broad \
  erydon:rosinium_column_circular \
  erydon:rosinium_column_gothic \
  erydon:rosinium_column_square \
  erydon:rosinium_cornice_modern \
  erydon:rosinium_cornice_georgian \
  erydon:rosinium_cornice_guilloche \
  erydon:rosinium_cornice_gothic \
  erydon:rosinium_surround_georgian \
  erydon:rosinium_surround_guilloche \
  erydon:rosinium_surround_gothic_ornate \
  erydon:rosinium_surround_modern \
  erydon:rosinium_stairs_spiral_large \
  erydon:rosinium_light_modern \
  erydon:rosinium_chimney_circular \
  erydon:rosinium_vertical_slice \
  erydon:rosinium_horizontal_slice \
  erydon:rosinium_post \
  erydon:rosinium_wall_georgian \
  erydon:rosinium_alcove_georgian \
  erydon:rosinium_alcove_gothic
faces=all

connect=block

innerSeams=true

priority=10
