method=repeat

width=6

height=6

tiles=textures/optifine/ctm/borealis_herringbone_grout/0 textures/optifine/ctm/borealis_herringbone_grout/1 textures/optifine/ctm/borealis_herringbone_grout/2 textures/optifine/ctm/borealis_herringbone_grout/3 textures/optifine/ctm/borealis_herringbone_grout/4 textures/optifine/ctm/borealis_herringbone_grout/5 textures/optifine/ctm/borealis_herringbone_grout/6 textures/optifine/ctm/borealis_herringbone_grout/7 textures/optifine/ctm/borealis_herringbone_grout/8 textures/optifine/ctm/borealis_herringbone_grout/9 textures/optifine/ctm/borealis_herringbone_grout/10 textures/optifine/ctm/borealis_herringbone_grout/11 textures/optifine/ctm/borealis_herringbone_grout/12 textures/optifine/ctm/borealis_herringbone_grout/13 textures/optifine/ctm/borealis_herringbone_grout/14 textures/optifine/ctm/borealis_herringbone_grout/15 textures/optifine/ctm/borealis_herringbone_grout/16 textures/optifine/ctm/borealis_herringbone_grout/17 textures/optifine/ctm/borealis_herringbone_grout/18 textures/optifine/ctm/borealis_herringbone_grout/19 textures/optifine/ctm/borealis_herringbone_grout/20 textures/optifine/ctm/borealis_herringbone_grout/21 textures/optifine/ctm/borealis_herringbone_grout/22 textures/optifine/ctm/borealis_herringbone_grout/23 textures/optifine/ctm/borealis_herringbone_grout/24 textures/optifine/ctm/borealis_herringbone_grout/25 textures/optifine/ctm/borealis_herringbone_grout/26 textures/optifine/ctm/borealis_herringbone_grout/27 textures/optifine/ctm/borealis_herringbone_grout/28 textures/optifine/ctm/borealis_herringbone_grout/29 textures/optifine/ctm/borealis_herringbone_grout/30 textures/optifine/ctm/borealis_herringbone_grout/31 textures/optifine/ctm/borealis_herringbone_grout/32 textures/optifine/ctm/borealis_herringbone_grout/33 textures/optifine/ctm/borealis_herringbone_grout/34 textures/optifine/ctm/borealis_herringbone_grout/35

matchBlocks=erydon:borealis_herringbone_grout_block \
  erydon:borealis_herringbone_grout_slab \
  erydon:borealis_herringbone_grout_wall \
  erydon:borealis_herringbone_grout_layer \
  erydon:borealis_herringbone_grout_layer_multiface \
  erydon:borealis_herringbone_grout_layer_vertical \
  erydon:borealis_herringbone_grout_slope \
  erydon:borealis_herringbone_grout_slope_shallow_upper \
  erydon:borealis_herringbone_grout_slope_steep_lower \
  erydon:borealis_herringbone_grout_slope_steep_upper \
  erydon:borealis_herringbone_grout_slope_shallow_lower \
  erydon:borealis_herringbone_grout_slope_vertical \
  erydon:borealis_herringbone_grout_slope_vertical_shallow_narrow \
  erydon:borealis_herringbone_grout_slope_vertical_shallow_broad \
  erydon:borealis_herringbone_grout_vertical_slice \
  erydon:borealis_herringbone_grout_horizontal_slice \
  erydon:borealis_herringbone_grout_post \
  erydon:borealis_herringbone_grout_wall_georgian
faces=top bottom north south east west

connect=block

innerSeams=true

priority=10
