method=repeat
width=6
height=6
tiles=textures/optifine/ctm/brectite/0 textures/optifine/ctm/brectite/1 textures/optifine/ctm/brectite/2 textures/optifine/ctm/brectite/3 textures/optifine/ctm/brectite/4 textures/optifine/ctm/brectite/5 textures/optifine/ctm/brectite/6 textures/optifine/ctm/brectite/7 textures/optifine/ctm/brectite/8 textures/optifine/ctm/brectite/9 textures/optifine/ctm/brectite/10 textures/optifine/ctm/brectite/11 textures/optifine/ctm/brectite/12 textures/optifine/ctm/brectite/13 textures/optifine/ctm/brectite/14 textures/optifine/ctm/brectite/15 textures/optifine/ctm/brectite/16 textures/optifine/ctm/brectite/17 textures/optifine/ctm/brectite/18 textures/optifine/ctm/brectite/19 textures/optifine/ctm/brectite/20 textures/optifine/ctm/brectite/21 textures/optifine/ctm/brectite/22 textures/optifine/ctm/brectite/23 textures/optifine/ctm/brectite/24 textures/optifine/ctm/brectite/25 textures/optifine/ctm/brectite/26 textures/optifine/ctm/brectite/27 textures/optifine/ctm/brectite/28 textures/optifine/ctm/brectite/29 textures/optifine/ctm/brectite/30 textures/optifine/ctm/brectite/31 textures/optifine/ctm/brectite/32 textures/optifine/ctm/brectite/33 textures/optifine/ctm/brectite/34 textures/optifine/ctm/brectite/35
matchBlocks=erydon:brectite_block_silvertrim \
  erydon:brectite_trim_silver_stairs \
  erydon:brectite_trim_silver_stairs_shallow_bottom \
  erydon:brectite_trim_silver_stairs_shallow_top \
  erydon:brectite_trim_silver_layer_multiface \
  erydon:brectite_trim_silver_slope \
  erydon:brectite_trim_silver_slope_shallow_lower \
  erydon:brectite_trim_silver_slope_shallow_upper \
  erydon:brectite_trim_silver_slope_steep_lower \
  erydon:brectite_trim_silver_slope_steep_upper \
  erydon:brectite_trim_silver_slope_vertical \
  erydon:brectite_trim_silver_slope_vertical_shallow_broad \
  erydon:brectite_trim_silver_slope_vertical_shallow_narrow \
  erydon:brectite_block_bronzetrim \
  erydon:brectite_trim_bronze_stairs \
  erydon:brectite_trim_bronze_stairs_shallow_bottom \
  erydon:brectite_trim_bronze_stairs_shallow_top \
  erydon:brectite_trim_bronze_layer_multiface \
  erydon:brectite_trim_bronze_slope \
  erydon:brectite_trim_bronze_slope_shallow_lower \
  erydon:brectite_trim_bronze_slope_shallow_upper \
  erydon:brectite_trim_bronze_slope_steep_lower \
  erydon:brectite_trim_bronze_slope_steep_upper \
  erydon:brectite_trim_bronze_slope_vertical \
  erydon:brectite_trim_bronze_slope_vertical_shallow_broad \
  erydon:brectite_trim_bronze_slope_vertical_shallow_narrow \
  erydon:brectite_block_bronzequatrefoil \
  erydon:brectite_quatrefoil_bronze_stairs \
  erydon:brectite_quatrefoil_bronze_stairs_shallow_bottom \
  erydon:brectite_quatrefoil_bronze_stairs_shallow_top \
  erydon:brectite_quatrefoil_bronze_layer_multiface \
  erydon:brectite_quatrefoil_bronze_slope \
  erydon:brectite_quatrefoil_bronze_slope_shallow_lower \
  erydon:brectite_quatrefoil_bronze_slope_shallow_upper \
  erydon:brectite_quatrefoil_bronze_slope_steep_lower \
  erydon:brectite_quatrefoil_bronze_slope_steep_upper \
  erydon:brectite_quatrefoil_bronze_slope_vertical \
  erydon:brectite_quatrefoil_bronze_slope_vertical_shallow_broad \
  erydon:brectite_quatrefoil_bronze_slope_vertical_shallow_narrow \
  erydon:brectite_block_silverquatrefoil \
  erydon:brectite_quatrefoil_silver_stairs \
  erydon:brectite_quatrefoil_silver_stairs_shallow_bottom \
  erydon:brectite_quatrefoil_silver_stairs_shallow_top \
  erydon:brectite_quatrefoil_silver_layer_multiface \
  erydon:brectite_quatrefoil_silver_slope \
  erydon:brectite_quatrefoil_silver_slope_shallow_lower \
  erydon:brectite_quatrefoil_silver_slope_shallow_upper \
  erydon:brectite_quatrefoil_silver_slope_steep_lower \
  erydon:brectite_quatrefoil_silver_slope_steep_upper \
  erydon:brectite_quatrefoil_silver_slope_vertical \
  erydon:brectite_quatrefoil_silver_slope_vertical_shallow_broad \
  erydon:brectite_quatrefoil_silver_slope_vertical_shallow_narrow \
  erydon:brectite_block_silverrose \
  erydon:brectite_rosette_silver_stairs \
  erydon:brectite_rosette_silver_stairs_shallow_bottom \
  erydon:brectite_rosette_silver_stairs_shallow_top \
  erydon:brectite_rosette_silver_layer_multiface \
  erydon:brectite_rosette_silver_slope \
  erydon:brectite_rosette_silver_slope_shallow_lower \
  erydon:brectite_rosette_silver_slope_shallow_upper \
  erydon:brectite_rosette_silver_slope_steep_lower \
  erydon:brectite_rosette_silver_slope_steep_upper \
  erydon:brectite_rosette_silver_slope_vertical \
  erydon:brectite_rosette_silver_slope_vertical_shallow_broad \
  erydon:brectite_rosette_silver_slope_vertical_shallow_narrow \
  erydon:brectite_block_bronzerose \
  erydon:brectite_rosette_bronze_stairs \
  erydon:brectite_rosette_bronze_stairs_shallow_bottom \
  erydon:brectite_rosette_bronze_stairs_shallow_top \
  erydon:brectite_rosette_bronze_layer_multiface \
  erydon:brectite_rosette_bronze_slope \
  erydon:brectite_rosette_bronze_slope_shallow_lower \
  erydon:brectite_rosette_bronze_slope_shallow_upper \
  erydon:brectite_rosette_bronze_slope_steep_lower \
  erydon:brectite_rosette_bronze_slope_steep_upper \
  erydon:brectite_rosette_bronze_slope_vertical \
  erydon:brectite_rosette_bronze_slope_vertical_shallow_broad \
  erydon:brectite_rosette_bronze_slope_vertical_shallow_narrow \
  erydon:brectite_block_silverguilloche \
  erydon:brectite_guilloche_silver_stairs \
  erydon:brectite_guilloche_silver_stairs_shallow_bottom \
  erydon:brectite_guilloche_silver_stairs_shallow_top \
  erydon:brectite_guilloche_silver_layer_multiface \
  erydon:brectite_guilloche_silver_slope \
  erydon:brectite_guilloche_silver_slope_shallow_lower \
  erydon:brectite_guilloche_silver_slope_shallow_upper \
  erydon:brectite_guilloche_silver_slope_steep_lower \
  erydon:brectite_guilloche_silver_slope_steep_upper \
  erydon:brectite_guilloche_silver_slope_vertical \
  erydon:brectite_guilloche_silver_slope_vertical_shallow_broad \
  erydon:brectite_guilloche_silver_slope_vertical_shallow_narrow \
  erydon:brectite_block_bronzeguilloche \
  erydon:brectite_guilloche_bronze_stairs \
  erydon:brectite_guilloche_bronze_stairs_shallow_bottom \
  erydon:brectite_guilloche_bronze_stairs_shallow_top \
  erydon:brectite_guilloche_bronze_layer_multiface \
  erydon:brectite_guilloche_bronze_slope \
  erydon:brectite_guilloche_bronze_slope_shallow_lower \
  erydon:brectite_guilloche_bronze_slope_shallow_upper \
  erydon:brectite_guilloche_bronze_slope_steep_lower \
  erydon:brectite_guilloche_bronze_slope_steep_upper \
  erydon:brectite_guilloche_bronze_slope_vertical \
  erydon:brectite_guilloche_bronze_slope_vertical_shallow_broad \
  erydon:brectite_guilloche_bronze_slope_vertical_shallow_narrow
faces=top bottom north south east west
connect=block
innerSeams=true
priority=10
